### PR TITLE
Fix cppcoreguidelines-special-member-functions warning reported by cl…

### LINKED ISSUE #1093: Fix `cppcoreguidelines-special-member-functions` warning reported by clang-tidy
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-kvrocks/issues) and found no similar issues.

### Motivation

*This issue is tracked by #1029.*

***We welcome new contributors to take these issues as a beginning of a deep dive to kvrocks***

Currently we have enabled lots of clang-tidy checks, but there are so many reports already exist in the kvrocks code, so we cannot treat these report as errors to block future PR with some clang-tidy reported warnings in CI.

Hence the goal of this issue is to solve all `cppcoreguidelines-special-member-functions` tagged clang-tidy reports, and then enable `warnings-as-errors` for this specific check in `.clang-tidy`.

To get clang-tidy reports for latest kvrocks code, there are several ways: you can run `./x.py check tidy` locally, or check the log of the latest run of GitHub Actions on the unstable branch (e.g. https://github.com/apache/incubator-kvrocks/actions/runs/3449328741/jobs/5757148924#step:8:916). To be friendly for new contributors, we list all `cppcoreguidelines-special-member-functions` tagged reports below, so in normal cases you can just follow the log below and fix them one by one.

```log
/home/runner/work/incubator-kvrocks/incubator-kvrocks/src/stats/log_collector.cc:112:16: warning: class 'LogCollector' defines a non-default destructor but does not define a copy constructor, a copy assignment operator, a move constructor or a move assignment operator [cppcoreguidelines-special-member-functions]
template class LogCollector<SlowEntry>;
               ^
/home/runner/work/incubator-kvrocks/incubator-kvrocks/src/stats/log_collector.cc:113:16: warning: class 'LogCollector' defines a non-default destructor but does not define a copy constructor, a copy assignment operator, a move constructor or a move assignment operator [cppcoreguidelines-special-member-functions]
template class LogCollector<PerfEntry>;
               ^
/home/runner/work/incubator-kvrocks/incubator-kvrocks/src/commands/redis_cmd.cc:1661:7: warning: class 'CommandBPop' defines a non-default destructor but does not define a copy constructor, a copy assignment operator, a move constructor or a move assignment operator [cppcoreguidelines-special-member-functions]
class CommandBPop : public Commander {
      ^
```

Some of these reports will give modification suggestions in the log, you can refer to them directly; otherwise, you need to understand the content of the warning and combine your C++ knowledge to fix it. (Fortunately, most reports (except those by clang static analyzer) are intuitive and easy to fix.)

When you fixed these all reports listed above, you can now add the check `cppcoreguidelines-special-member-functions` to `warnings-as-errors` in `.clang-tidy` (in the root dir of the repo): We show a sample diff below to illustrate how to modify `.clang-tidy`:

```diff
--- a/.clang-tidy
+++ b/.clang-tidy
@@ -1,7 +1,7 @@
 # refer to https://clang.llvm.org/extra/clang-tidy/checks/list.html
 Checks: ...

-WarningsAsErrors: ...
+WarningsAsErrors: ..., cppcoreguidelines-special-member-functions
```

Then, if all of the above are completed, congratulations, you can submit a PR for your changes now!

### Solution

_No response_

### Are you willing to submit a PR?

- [ ] I'm willing to submit a PR!

### PR DESCRIPTION
**Pull request by maochongxin**
This close #1093

### CODE REVIEW

File: src/commands/redis_cmd.cc [hunk 1]
```diff
@@ -1661,6 +1661,15 @@ class CommandRPop : public CommandPop {
...
  public:
   explicit CommandBPop(bool left) : left_(left) {}
+
+  CommandBPop() = default;
+
+  // Not copyable
+  CommandBPop(const CommandBPop &) = delete;
+  CommandBPop(CommandBPop &&) = delete;
+  CommandBPop &operator=(const CommandBPop &) = delete;
+  CommandBPop &operator=(CommandBPop &&) = delete;
```
Comment (PragmaTwice) [inline src/commands/redis_cmd.cc]:
```suggestion
  CommandBPop(const CommandBPop &) = delete;
  CommandBPop &operator=(const CommandBPop &) = delete;
```

File: src/stats/log_collector.h [hunk 2]
```diff
@@ -56,6 +56,9 @@ class PerfEntry {
 template <class T>
 class LogCollector {
  public:
+  LogCollector() = default;
+  LogCollector(const LogCollector<T> &) = delete;
+  LogCollector &operator=(const LogCollector<T> &) = delete;
```
Comment (PragmaTwice) [inline src/stats/log_collector.h]:
```suggestion
  LogCollector(const LogCollector &) = delete;
  LogCollector &operator=(const LogCollector &) = delete;
```

**Review by PragmaTwice — APPROVED** [review]

**Review by git-hulk — APPROVED** [review]

**Comment by PragmaTwice** [comment]
Thanks for your contribution!
