### PR TITLE
Fix load namespaces from the config file would ignore case-sensitive

### LINKED ISSUE #640: namespace  is case-sensitive but namespace configed in file is not and namespace command does
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-kvrocks/issues) and found no similar issues.

### Version

1.3.3

### Minimal reproduce step

add namespace with command 

>> namespace add "Big_case_namespace" "anypass"
ok

then 
restart the instance ,get namespace info
>> namespace get *
1) big_case_namespace
2) anypass

### What did you expect to see?

when restart we should get a namespace named "Big_case_namespace" not "big_case_namespace", it makes data could not be access with auth "anypass",it point to another namespace with lowercase

### What did you see instead?

>> namespace get *
1) big_case_namespace
2) anypass

### Anything Else?

config with namespace and command has the same result

### Are you willing to submit a PR?

- [X] I'm willing to submit a PR!

### PR DESCRIPTION
**Pull request by fishery86**
[fix]:load namespace from config file with case-sensitive issue:#640

This closes #640

### CODE REVIEW

File: src/config.cc [hunk 1]
```diff
@@ -523,17 +523,19 @@ Status Config::parseConfigFromString(std::string input, int line_number) {
...
   if (kv[1] == "\"\"") return Status::OK();
 
-  kv[0] = Util::ToLower(kv[0]);
-  auto iter = fields_.find(kv[0]);
+  std::string configKey = Util::ToLower(kv[0]);
+  if (!strncasecmp(kv[0].data(), "namespace.", 10)) {
+      // namespace should keep key case-sensitive
+      configKey = kv[0];
+      tokens[kv[1]] = kv[0].substr(10, kv[0].size() - 10);
+  }
```
Comment (PragmaTwice) [inline src/config.cc]:
```suggestion
  const char ns_str[] = "namespace.";
  size_t ns_str_size = sizeof(ns_str) - 1;
  if (!strncasecmp(kv[0].data(), ns_str, ns_str_size)) {
      // namespace should keep key case-sensitive
      configKey = kv[0];
      tokens[kv[1]] = kv[0].substr(ns_str_size);
  }
```
I think we should avoid any magic number, e.g. `10` here : )

File: src/config.cc [hunk 2]
```diff
@@ -523,17 +523,21 @@ Status Config::parseConfigFromString(std::string input, int line_number) {
...
-  auto iter = fields_.find(kv[0]);
+  std::string configKey = Util::ToLower(kv[0]);
+  const char ns_str[] = "namespace.";
+  size_t ns_str_size = sizeof(ns_str) - 1;
+  if (!strncasecmp(kv[0].data(), ns_str, ns_str_size)) {
+      // namespace should keep key case-sensitive
+      configKey = kv[0];
+      tokens[kv[1]] = kv[0].substr(ns_str_size);
+  }
+  auto iter = fields_.find(configKey);
```
Comment (git-hulk) [inline src/config.cc]:
```suggestion
  std::string field_key = Util::ToLower(kv[0]);
  const char ns_str[] = "namespace.";
  size_t ns_str_size = sizeof(ns_str) - 1;
  if (!strncasecmp(kv[0].data(), ns_str, ns_str_size)) {
      // namespace should keep key case-sensitive
      field_key = kv[0];
      tokens[kv[1]] = kv[0].substr(ns_str_size);
  }
  auto iter = fields_.find(field_key);
```

Comment (git-hulk) [reply src/config.cc]: The variable name should be spliced by `_` instead of CamelCase. Sorry that we didn't claim the code style clearly in our contribution guide.

**Review by git-hulk — APPROVED** [review]
LGTM, thanks @fishery86

**Review by PragmaTwice — APPROVED** [review]
LGTM

**Comment by git-hulk** [comment]
Thanks for your contribution again @fishery86
