### PR TITLE
Fix the slave may crash when restoring the db

### LINKED ISSUE #603: The slave would crash when restoring the db from checkpoint error
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-kvrocks/issues) and found no similar issues.

### Version

2.0.6

### Minimal reproduce step

1. slaveof `x.x.x.x`
2. remove some files to fail the restore db process

### What did you expect to see?

The slave should serve with the old database

### What did you see instead?

image

### Anything Else?

_No response_

### Are you willing to submit a PR?

- [x] I'm willing to submit a PR!

### PR DESCRIPTION
**Pull request by git-hulk**
The db pointer was forbidden to use when restoring the db, but we
didn't check the loading status in `recordInstantaneousMetrics`
in the server's cron thread. We can skip all the cron operations
when restoring the db instead of checking status one by one.

This closes #603

### CODE REVIEW

**Review by ShooterIT — APPROVED** [review]

**Review by tisonkun — APPROVED** [review]
LGTM

File: src/server.cc [hunk 1]
```diff
@@ -558,8 +558,15 @@ void Server::cron() {
     if (storage_->IsClosing()) continue;
```
Comment (ShooterIT) [inline src/server.cc:558]: @git-hulk here we already check db is closing, are you sure kvrock would execute the next code

Comment (git-hulk) [reply src/server.cc:558]: Yes, there still have the window between `closing` and the db pointer is ready, since we set it to `true` at the begin of the open db.

Comment (ShooterIT) [reply src/server.cc:558]: ok, thanks
