### PR TITLE
Fix server crash when receiving the empty inline command

### LINKED ISSUE #1908: Ooops! kvrocks version 2.6.0 (commit cac0ade4) got signal: Segmentation fault (11)
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/kvrocks/issues) and found no similar issues.

### Version

2.6.0

### Minimal reproduce step

-

### What did you expect to see?

-

### What did you see instead?
```
root@host:/home/redis/var/log# cat kvrocks.ERROR
Log file created at: 2023/11/24 10:45:56
Running on machine: redis-kvsenior01-210027.i.nease.net
Running duration (h:mm:ss): 0:00:00
Log line format: [IWEF]yyyymmdd hh:mm:ss.uuuuuu threadid file:line] msg
E20231124 10:45:56.856230  5147 main.cc:85] ======= Ooops! kvrocks version 2.6.0 (commit cac0ade4) got signal: Segmentation fault (11) =======
E20231124 10:45:56.856793  5147 main.cc:102] /lib/x86_64-linux-gnu/libpthread.so.0(+0x14140) [0x7f45cb08d140]
E20231124 10:45:56.857265  5147 main.cc:100] /home/redis/server/2.6.0/bin/kvrocks(+0x217769) [0x560584630769]  redis::Connection::ExecuteCommands()
E20231124 10:45:56.857934  5147 main.cc:100] /home/redis/server/2.6.0/bin/kvrocks(+0x1605ac) [0x5605845795ac]  EvbufCallbackBase<>::readCB()
E20231124 10:45:56.858131  5147 main.cc:100] /home/redis/server/2.6.0/bin/kvrocks(+0x7b0dee) [0x560584bc9dee]  bufferevent_run_deferred_callbacks_unlocked
E20231124 10:45:56.858312  5147 main.cc:100] /home/redis/server/2.6.0/bin/kvrocks(+0x7b738d) [0x560584bd038d]  event_process_active_single_queue
E20231124 10:45:56.858755  5147 main.cc:100] /home/redis/server/2.6.0/bin/kvrocks(+0x7b7d4f) [0x560584bd0d4f]  event_base_loop
E20231124 10:45:56.859345  5147 main.cc:100] /home/redis/server/2.6.0/bin/kvrocks(+0x23af1d) [0x560584653f1d]  _ZNSt6thread11_State_implINS_8_InvokerISt5tupleIJZN4util12CreateThreadIZN12WorkerThread5StartEvEUlvE_EE8StatusOrIS_EPKcT_EUlvE_EEEEE6_M_runEv.lto_priv.0
E20231124 10:45:56.859525  5147 main.cc:100] /home/redis/server/2.6.0/bin/kvrocks(+0x9aa7b0) [0x560584dc37b0]  execute_native_thread_routine
E20231124 10:45:56.859648  5147 main.cc:100] /lib/x86_64-linux-gnu/libpthread.so.0(+0x8ea7) [0x7f45cb081ea7]   start_thread
E20231124 10:45:56.859750  5147 main.cc:100] /lib/x86_64-linux-gnu/libc.so.6(clone+0x3f) [0x7f45cae6ddef]      clone

```

### Anything Else?

_No response_

### Are you willing to submit a PR?

- [ ] I'm willing to submit a PR!

### PR DESCRIPTION
**Pull request by git-hulk**
Currently, we didn't check if the token array is empty before using it,
so it will crash if receive a request with a query like ` \r\n`.
This only happens in the inline command situation since the multi-bulk protocol
will ignore the request if the length is <= 0.

This fixes #1908

### CODE REVIEW

**Review by enjoy-binbin — APPROVED** [review]

**Review by PragmaTwice — APPROVED** [review]

File: src/server/redis_connection.cc [hunk 1]
```diff
@@ -307,6 +307,7 @@ void Connection::ExecuteCommands(std::deque<CommandTokens> *to_process_cmds) {
   while (!to_process_cmds->empty()) {
     auto cmd_tokens = to_process_cmds->front();
```
Comment (mapleFU) [inline src/server/redis_connection.cc:308]: nit: should we `std::move(to_process_cmds->front())`?

Comment (git-hulk) [reply src/server/redis_connection.cc:308]: Yes, but guess we can do it in other PR to make the context clear.
