### PR TITLE
Fix `modernize-avoid-bind` warning reported by clang-tidy

### LINKED ISSUE #1094: Fix `modernize-avoid-bind` warning reported by clang-tidy
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-kvrocks/issues) and found no similar issues.

### Motivation

*This issue is tracked by #1029.*

***We welcome new contributors to take these issues as a beginning of a deep dive to kvrocks***

Currently we have enabled lots of clang-tidy checks, but there are so many reports already exist in the kvrocks code, so we cannot treat these report as errors to block future PR with some clang-tidy reported warnings in CI.

Hence the goal of this issue is to solve all `modernize-avoid-bind` tagged clang-tidy reports, and then enable `warnings-as-errors` for this specific check in `.clang-tidy`.

To get clang-tidy reports for latest kvrocks code, there are several ways: you can run `./x.py check tidy` locally, or check the log of the latest run of GitHub Actions on the unstable branch (e.g. https://github.com/apache/incubator-kvrocks/actions/runs/3449328741/jobs/5757148924#step:8:916). To be friendly for new contributors, we list all `modernize-avoid-bind` tagged reports below, so in normal cases you can just follow the log below and fix them one by one.

```log
/home/runner/work/incubator-kvrocks/incubator-kvrocks/src/cluster/cluster.cc:322:25: warning: prefer a lambda to std::bind [modernize-avoid-bind]
      conn->close_cb_ = std::bind(&SlotImport::StopForLinkError, svr_->slot_import_, conn->GetFD());
                        ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
                        [ObjectPtr = svr_->slot_import_, capture0 = conn->GetFD()] { ObjectPtr->StopForLinkError(capture0); }
/home/runner/work/incubator-kvrocks/incubator-kvrocks/src/commands/redis_cmd.cc:3733:11: warning: prefer a lambda to std::bind [modernize-avoid-bind]
          std::bind(SubscribeCommandReply, output, "unsubscribe", std::placeholders::_1, std::placeholders::_2));
          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
          [output](auto && PH1, auto && PH2) { return SubscribeCommandReply(output, "unsubscribe", std::forward<decltype(PH1)>(PH1), std::forward<decltype(PH2)>(PH2)); }
/home/runner/work/incubator-kvrocks/incubator-kvrocks/src/commands/redis_cmd.cc:3761:11: warning: prefer a lambda to std::bind [modernize-avoid-bind]
          std::bind(SubscribeCommandReply, output, "punsubscribe", std::placeholders::_1, std::placeholders::_2));
          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
          [output](auto && PH1, auto && PH2) { return SubscribeCommandReply(output, "punsubscribe", std::forward<decltype(PH1)>(PH1), std::forward<decltype(PH2)>(PH2)); }
```

Some of these reports will give modification suggestions in the log, you can refer to them directly; otherwise, you need to understand the content of the warning and combine your C++ knowledge to fix it. (Fortunately, most reports (except those by clang static analyzer) are intuitive and easy to fix.)

When you fixed these all reports listed above, you can now add the check `modernize-avoid-bind` to `warnings-as-errors` in `.clang-tidy` (in the root dir of the repo): We show a sample diff below to illustrate how to modify `.clang-tidy`:

```diff
--- a/.clang-tidy
+++ b/.clang-tidy
@@ -1,7 +1,7 @@
 # refer to https://clang.llvm.org/extra/clang-tidy/checks/list.html
 Checks: ...

-WarningsAsErrors: ...
+WarningsAsErrors: ..., modernize-avoid-bind
```

Then, if all of the above are completed, congratulations, you can submit a PR for your changes now!

### Solution

_No response_

### Are you willing to submit a PR?

- [ ] I'm willing to submit a PR!

### PR DESCRIPTION
**Pull request by Phoeniwx**
This close #1094

### CODE REVIEW

File: src/commands/redis_cmd.cc [hunk 1]
```diff
@@ -3730,7 +3730,10 @@ class CommandUnSubscribe : public Commander {
   Status Execute(Server *svr, Connection *conn, std::string *output) override {
     if (args_.size() == 1) {
       conn->UnSubscribeAll(
-          std::bind(SubscribeCommandReply, output, "unsubscribe", std::placeholders::_1, std::placeholders::_2));
+          [output](const std::string &sub_name, int num){SubscribeCommandReply(output, "unsubscribe", sub_name, num);}
+      );
+      // conn->UnSubscribeAll(
+      //     std::bind(SubscribeCommandReply, output, "unsubscribe", std::placeholders::_1, std::placeholders::_2));
```
Comment (tanruixiang) [inline src/commands/redis_cmd.cc]: It looks like the comments were forgotten to delete.

File: src/commands/redis_cmd.cc [hunk 2]
```diff
@@ -3758,7 +3761,10 @@ class CommandPUnSubscribe : public Commander {
   Status Execute(Server *svr, Connection *conn, std::string *output) override {
     if (args_.size() == 1) {
       conn->PUnSubscribeAll(
-          std::bind(SubscribeCommandReply, output, "punsubscribe", std::placeholders::_1, std::placeholders::_2));
+          [output](const std::string &sub_name, int num) {SubscribeCommandReply(output, "punsubscribe", sub_name, num);}
+      );
+      // conn->PUnSubscribeAll(
+      //     std::bind(SubscribeCommandReply, output, "punsubscribe", std::placeholders::_1, std::placeholders::_2));
```
Comment (tanruixiang) [inline src/commands/redis_cmd.cc]: It looks like the comments were forgotten to delete.

File: src/cluster/cluster.cc [hunk 3]
```diff
@@ -319,7 +319,8 @@ Status Cluster::ImportSlot(Redis::Connection *conn, int slot, int state) {
       conn->SetImporting();
       myself_->importing_slot_ = slot;
       // Set link error callback
-      conn->close_cb_ = std::bind(&SlotImport::StopForLinkError, svr_->slot_import_, conn->GetFD());
+      // conn->close_cb_ = std::bind(&SlotImport::StopForLinkError, svr_->slot_import_, conn->GetFD());
```
Comment (tanruixiang) [inline src/cluster/cluster.cc]: It looks like the comments were forgotten to delete.

**Review by tanruixiang — COMMENTED** [review]
Thank you for your contribution. It looks like there is some original code that forgot to remove.  By the way, you need to add the check to `.clang-tidy` and resolve conflicts. And use ` ./x.py format` to format code.

File: src/cluster/cluster.cc [hunk 4]
```diff
@@ -319,7 +319,8 @@ Status Cluster::ImportSlot(Redis::Connection *conn, int slot, int state) {
...
+      conn->close_cb_ = [ObjectPtr = svr_->slot_import_, captureFd = conn->GetFD()](int fd) {ObjectPtr->StopForLinkError(captureFd);};
```
Comment (torwig) [inline src/cluster/cluster.cc]: To be consistent, please use variables `object_ptr` (snake case) instead of `ObjectPtr` (camel case). `captureFd` as well.

File: src/commands/redis_cmd.cc [hunk 5]
```diff
@@ -3730,7 +3730,10 @@ class CommandUnSubscribe : public Commander {
   Status Execute(Server *svr, Connection *conn, std::string *output) override {
     if (args_.size() == 1) {
       conn->UnSubscribeAll(
-          std::bind(SubscribeCommandReply, output, "unsubscribe", std::placeholders::_1, std::placeholders::_2));
+          [output](const std::string &sub_name, int num){SubscribeCommandReply(output, "unsubscribe", sub_name, num);}
+      );
+      // conn->UnSubscribeAll(
```
Comment (torwig) [inline src/commands/redis_cmd.cc]: I think that it's better to remove the code than comment it out.

File: src/commands/redis_cmd.cc [hunk 6]
```diff
@@ -3758,7 +3761,10 @@ class CommandPUnSubscribe : public Commander {
   Status Execute(Server *svr, Connection *conn, std::string *output) override {
     if (args_.size() == 1) {
       conn->PUnSubscribeAll(
-          std::bind(SubscribeCommandReply, output, "punsubscribe", std::placeholders::_1, std::placeholders::_2));
+          [output](const std::string &sub_name, int num) {SubscribeCommandReply(output, "punsubscribe", sub_name, num);}
+      );
+      // conn->PUnSubscribeAll(
```
Comment (torwig) [inline src/commands/redis_cmd.cc]: And here as well (remove instead of comment out).

**Comment by Phoeniwx** [comment]
Sorry guys, I ve removed old commented code, renamed variables, formatted code and updated .clang-tidy

File: src/cluster/cluster.cc [hunk 7]
```diff
@@ -319,7 +319,9 @@ Status Cluster::ImportSlot(Redis::Connection *conn, int slot, int state) {
       conn->SetImporting();
       myself_->importing_slot_ = slot;
       // Set link error callback
-      conn->close_cb_ = std::bind(&SlotImport::StopForLinkError, svr_->slot_import_, conn->GetFD());
+      conn->close_cb_ = [object_ptr = svr_->slot_import_, capture_fd = conn->GetFD()](int fd) {
```
Comment (PragmaTwice) [inline src/cluster/cluster.cc:322]: Why is there an additional parameter `int fd`?

Comment (PragmaTwice) [reply src/cluster/cluster.cc:322]: Oh, I notice the type definition. Sorry.

Comment (Phoeniwx) [reply src/cluster/cluster.cc:322]: `conn->close_cb_ is` a `std::function<void (int)>`, so I add a `int fd`

File: .clang-tidy [hunk 8]
```diff
@@ -1,7 +1,8 @@
...
 
-WarningsAsErrors: clang-analyzer-*, -clang-analyzer-security.insecureAPI.rand, cppcoreguidelines-interfaces-global-init, cppcoreguidelines-no-malloc, cppcoreguidelines-slicing, google-*, modernize-use-emplace, modernize-use-equals-default, modernize-use-equals-delete, performance-implicit-conversion-in-loop, performance-inefficient-algorithm, performance-move-constructor-init, performance-no-automatic-move, performance-trivially-destructible, performance-type-promotion-in-math-fn, performance-unnecessary-copy-initialization, modernize-use-bool-literals, performance-unnecessary-value-param, modernize-make-unique, performance-for-range-copy, performance-faster-string-find, modernize-redundant-void-arg
+
```
Comment (PragmaTwice) [inline .clang-tidy]:
```suggestion
```

**Review by PragmaTwice — APPROVED** [review]

**Review by torwig — APPROVED** [review]

**Comment by PragmaTwice** [comment]
Thanks for your contribution!
