### PR TITLE
Fix data race when joining the task runner

### LINKED ISSUE #1448: Data race in TBB::concurrent_queue when running integrate tests
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-kvrocks/issues) and found no similar issues.

### Version

unstable

### Minimal reproduce step

detail logs: https://github.com/apache/incubator-kvrocks/actions/runs/5015903443/jobs/8992316856?pr=1446

### What did you expect to see?

all tests are passed

### What did you see instead?

one of them crashed when running

### Anything Else?

_No response_

### Are you willing to submit a PR?

- [ ] I'm willing to submit a PR!

### PR DESCRIPTION
**Pull request by git-hulk**
This may close #1448 

Currently, server->Join will join the task runner before the cron thread, so it may have the data race since the cron thread may access the task runner as well. We can avoid this by removing the task runner join which will do in the task runner destructor.

### CODE REVIEW

**Review by torwig — DISMISSED** [review]
Good catch.
Sounds legitimate to me.

**Comment by git-hulk** [comment]
@torwig Thanks for your quick review.

**Comment by PragmaTwice** [comment]
Could you specify the location of another Join call of the task runner?

**Comment by git-hulk** [comment]
> Could you specify the location of another Join call of the task runner?

Sure, the TaskRunner destructor will join as well: https://github.com/apache/incubator-kvrocks/blob/unstable/src/common/task_runner.h#L49

**Review by PragmaTwice — DISMISSED** [review]
LGTM. Although a dtor with a long time waiting may cause some misunderstanding.

**Comment by git-hulk** [comment]
> LGTM. Although a dtor with a long time waiting may cause some misunderstanding.

Yes, I think we can remove the Cancel and Join in dtor since the Server::Stop will cancel the task runner first. Can take a look again. @PragmaTwice @torwig

**Comment by torwig** [comment]
@git-hulk Yes, `Server::Stop` will cancel and `Server::Join` will join all threads.
Additionally, here https://github.com/apache/incubator-kvrocks/blob/unstable/src/common/task_runner.cc#L48 should we stop joining threads when the first call to `util::ThreadJoin` or just log an error and continue joining other threads?

**Comment by git-hulk** [comment]
> @git-hulk Yes, `Server::Stop` will cancel and `Server::Join` will join all threads. Additionally, here https://github.com/apache/incubator-kvrocks/blob/unstable/src/common/task_runner.cc#L48 should we stop joining threads when the first call to `util::ThreadJoin` or just log an error and continue joining other threads?

oooh, my bad. I didn't see that, updated.

File: src/server/server.cc [hunk 1]
```diff
@@ -230,15 +230,15 @@ void Server::Join() {
...
-    LOG(WARNING) << s.Msg();
-  }
   if (auto s = util::ThreadJoin(cron_thread_); !s) {
     LOG(WARNING) << "Cron thread operation failed: " << s.Msg();
   }
   if (auto s = util::ThreadJoin(compaction_checker_thread_); !s) {
     LOG(WARNING) << "Compaction checker thread operation failed: " << s.Msg();
   }
+  if (auto s = task_runner_.Join(); !s) {
+    LOG(WARNING) << "Task runner thread operation failed: " << s.Msg();
```
Comment (git-hulk) [inline src/server/server.cc]:
```suggestion
    LOG(WARNING) << s.Msg();
```

**Comment by torwig** [comment]
@git-hulk My idea was to change the loop to the following:

```
for (auto &thread : threads_) {
  if (auto s = util::ThreadJoin(thread); !s) {
    LOG(WARNING) << "Failed to join thread: " << s.Msg();
    continue;
  }
}
```

What do you think about that? @PragmaTwice What is your opinion on that?

**Comment by git-hulk** [comment]
> LOG(WARNING) << "Failed to join thread: " << s.Msg();

Yes, it's good to only log an error when failing to join since other places like the worker thread only prints an error.

**Comment by git-hulk** [comment]
> @git-hulk My idea was to change the loop to the following:
> 
> ```
> for (auto &thread : threads_) {
>   if (auto s = util::ThreadJoin(thread); !s) {
>     LOG(WARNING) << "Failed to join thread: " << s.Msg();
>     continue;
>   }
> }
> ```
> 
> What do you think about that? @PragmaTwice What is your opinion on that?

Yes, it's good to only log an error when failing to join since other places like the worker thread only print an error.

**Comment by PragmaTwice** [comment]
> @git-hulk My idea was to change the loop to the following:
> 
> ```
> for (auto &thread : threads_) {
>   if (auto s = util::ThreadJoin(thread); !s) {
>     LOG(WARNING) << "Failed to join thread: " << s.Msg();
>     continue;
>   }
> }
> ```
> 
> What do you think about that? @PragmaTwice What is your opinion on that?

Seems good to me.

**Review by torwig — DISMISSED** [review]

File: src/common/task_runner.h [hunk 2]
```diff
@@ -42,13 +42,7 @@ class TaskRunner {
...
   TaskRunner(const TaskRunner&) = delete;
   TaskRunner& operator=(const TaskRunner&) = delete;
-
-  ~TaskRunner() {
-    if (state_ != Stopped) {
-      Cancel();
-      auto _ = Join();
-    }
-  }
+  ~TaskRunner() = default;
```
Comment (PragmaTwice) [inline src/common/task_runner.h]: Seems we need some guarantee for this object? i.e. the behavior will be **undefined** while the taskrunner is destructed and the attached threads are still running, which is dangerous.

Can refer to std::jthread (https://en.cppreference.com/w/cpp/thread/jthread/~jthread) and std::thread (https://en.cppreference.com/w/cpp/thread/thread/~thread).

The previous dtor build such a guarantee like std::jthread, but I think we can call `Join` explicitly as far as possible to prevent misunderstanding. Removing such dtor cannot help the situation.

Comment (git-hulk) [reply src/common/task_runner.h]: The data race may be caused by the task runner's `Join` function will clear the concurrent queue, so it could be fixed after moving to the last one to join. It's good for me to keep the Cancel and Join in dctor.

**Review by PragmaTwice — APPROVED** [review]

**Review by torwig — APPROVED** [review]

**Comment by git-hulk** [comment]
Thanks all, merging...
