### PR TITLE
fix(namespace): didn't reload namespaces from DB after the full sync

### LINKED ISSUE #2520: Didn't load namespaces into memory after full syncing the db from master node
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/kvrocks/issues) and found no similar issues.

### Version

2.9.0

### Minimal reproduce step

The master contains 17 namespaces with around 500,000 keys in total.

1. Execute `SLAVE OF <master>` on the slave.

3. After the `master_link_status: up`, run `NAMESPACE GET *` on the slave.

### What did you expect to see?

The slave should display all namespaces, identical to the master.

### What did you see instead?

Only the default namespace is displayed.

After restarting the slave server, all namespaces are visible.

Performing any operation on the namespaces on the master (e.g., adding or deleting) causes all namespaces to become visible on the slave.

### Anything Else?

Master Log:

```
I20240903 09:49:47.686094     1 main.cc:142] kvrocks version 2.9.0
I20240903 09:49:48.516047     1 event_listener.cc:177] [event_listener/table_file_created] column family: default, file path: /var/lib/kvrocks/db/000787.sst, file size: 21418974, job_id: 1, reason: recovery, status: OK
I20240903 09:49:48.535416     1 event_listener.cc:177] [event_listener/table_file_created] column family: metadata, file path: /var/lib/kvrocks/db/000788.sst, file size: 2638811, job_id: 1, reason: recovery, status: OK
I20240903 09:49:48.537494     1 event_listener.cc:177] [event_listener/table_file_created] column family: propagate, file path: /var/lib/kvrocks/db/000789.sst, file size: 1737, job_id: 1, reason: recovery, status: OK
I20240903 09:49:48.579883     1 storage.cc:387] [storage] Success to load the data from disk: 880 ms
I20240903 09:49:48.582392     1 worker.cc:72] [worker] Listening on: 0.0.0.0:6666
I20240903 09:49:48.582553     1 worker.cc:72] [worker] Listening on: 0.0.0.0:6666
I20240903 09:49:48.582653     1 worker.cc:72] [worker] Listening on: 0.0.0.0:6666
I20240903 09:49:48.582748     1 worker.cc:72] [worker] Listening on: 0.0.0.0:6666
I20240903 09:49:48.582841     1 worker.cc:72] [worker] Listening on: 0.0.0.0:6666
I20240903 09:49:48.582938     1 worker.cc:72] [worker] Listening on: 0.0.0.0:6666
I20240903 09:49:48.583042     1 worker.cc:72] [worker] Listening on: 0.0.0.0:6666
I20240903 09:49:48.592422     1 worker.cc:72] [worker] Listening on: 0.0.0.0:6666
I20240903 09:49:48.592732     1 worker.cc:564] [worker] Thread #140582884210368 started
I20240903 09:49:48.592758     1 worker.cc:564] [worker] Thread #140582898886336 started
I20240903 09:49:48.592778     1 worker.cc:564] [worker] Thread #140582909376192 started
I20240903 09:49:48.592809     1 worker.cc:564] [worker] Thread #140582986966720 started
I20240903 09:49:48.592924     1 worker.cc:564] [worker] Thread #140582974387904 started
I20240903 09:49:48.592953     1 worker.cc:564] [worker] Thread #140582963898048 started
I20240903 09:49:48.593073     1 worker.cc:564] [worker] Thread #140582934542016 started
I20240903 09:49:48.593104     1 worker.cc:564] [worker] Thread #140582921955008 started
I20240903 09:49:48.593710     1 server.cc:228] [server] Ready to accept connections
I20240903 09:50:18.392220    31 cmd_replication.cc:60] Slave 10.0.1.182:45896, listening port: 6666, announce ip: 10.0.1.182 asks for synchronization with next sequence: 1 replication id: not supported, and local sequence: 25585719
I20240903 09:50:18.400365    61 storage.cc:975] [storage] Create checkpoint successfully
I20240903 09:50:18.400447    61 cmd_replication.cc:242] [replication] Succeed sending full data file info to 10.0.1.182
I20240903 09:50:18.556877    65 cmd_replication.cc:297] [replication] Succeed sending file 000787.sst to 10.0.1.182
I20240903 09:50:18.607342    63 cmd_replication.cc:297] [replication] Succeed sending file 000774.sst to 10.0.1.182
I20240903 09:50:18.671141    65 cmd_replication.cc:297] [replication] Succeed sending file 000647.sst to 10.0.1.182
I20240903 09:50:18.807121    63 cmd_replication.cc:297] [replication] Succeed sending file 000782.sst to 10.0.1.182
I20240903 09:50:18.870740    65 cmd_replication.cc:297] [replication] Succeed sending file 000781.sst to 10.0.1.182
I20240903 09:50:18.939994    63 cmd_replication.cc:297] [replication] Succeed sending file 000613.sst to 10.0.1.182
I20240903 09:50:19.002041    62 cmd_replication.cc:297] [replication] Succeed sending file 000780.sst to 10.0.1.182
I20240903 09:50:19.012153    65 cmd_replication.cc:297] [replication] Succeed sending file 000616.sst to 10.0.1.182
I20240903 09:50:19.118355    62 cmd_replication.cc:297] [replication] Succeed sending file 000764.sst to 10.0.1.182
I20240903 09:50:19.150846    65 cmd_replication.cc:297] [replication] Succeed sending file 000028.sst to 10.0.1.182
I20240903 09:50:19.267230    64 cmd_replication.cc:297] [replication] Succeed sending file 000784.sst to 10.0.1.182
I20240903 09:50:19.308533    62 cmd_replication.cc:297] [replication] Succeed sending file 000607.sst to 10.0.1.182
I20240903 09:50:19.420279    63 cmd_replication.cc:297] [replication] Succeed sending file 000181.sst to 10.0.1.182
I20240903 09:50:19.686789    65 cmd_replication.cc:297] [replication] Succeed sending file 000118.sst to 10.0.1.182
I20240903 09:50:20.542193    65 cmd_replication.cc:297] [replication] Succeed sending file 000650.sst to 10.0.1.182
I20240903 09:50:20.626637    62 cmd_replication.cc:297] [replication] Succeed sending file 000635.sst to 10.0.1.182
I20240903 09:50:20.643808    64 cmd_replication.cc:297] [replication] Succeed sending file 000627.sst to 10.0.1.182
I20240903 09:50:20.724064    65 cmd_replication.cc:297] [replication] Succeed sending file 000677.sst to 10.0.1.182
I20240903 09:50:20.908425    65 cmd_replication.cc:297] [replication] Succeed sending file 000697.sst to 10.0.1.182
I20240903 09:50:21.044257    64 cmd_replication.cc:297] [replication] Succeed sending file 000633.sst to 10.0.1.182
I20240903 09:50:21.064903    65 cmd_replication.cc:297] [replication] Succeed sending file 000735.sst to 10.0.1.182
I20240903 09:50:21.170583    63 cmd_replication.cc:297] [replication] Succeed sending file 000092.sst to 10.0.1.182
I20240903 09:50:21.206207    64 cmd_replication.cc:297] [replication] Succeed sending file 000634.sst to 10.0.1.182
I20240903 09:50:21.229301    65 cmd_replication.cc:297] [replication] Succeed sending file 000754.sst to 10.0.1.182
I20240903 09:50:21.636394    62 cmd_replication.cc:297] [replication] Succeed sending file 000068.sst to 10.0.1.182
I20240903 09:50:21.734787    63 cmd_replication.cc:297] [replication] Succeed sending file 000171.sst to 10.0.1.182
I20240903 09:50:21.791790    63 cmd_replication.cc:297] [replication] Succeed sending file 000676.sst to 10.0.1.182
I20240903 09:50:21.792598    64 cmd_replication.cc:297] [replication] Succeed sending file 000025.sst to 10.0.1.182
I20240903 09:50:21.826874    62 cmd_replication.cc:297] [replication] Succeed sending file 000150.sst to 10.0.1.182
I20240903 09:50:21.871572    63 cmd_replication.cc:297] [replication] Succeed sending file 000694.sst to 10.0.1.182
I20240903 09:50:22.038069    62 cmd_replication.cc:297] [replication] Succeed sending file 000675.sst to 10.0.1.182
I20240903 09:50:22.093640    63 cmd_replication.cc:297] [replication] Succeed sending file 000714.sst to 10.0.1.182
I20240903 09:50:22.106451    65 cmd_replication.cc:297] [replication] Succeed sending file 000334.sst to 10.0.1.182
I20240903 09:50:22.213804    62 cmd_replication.cc:297] [replication] Succeed sending file 000693.sst to 10.0.1.182
I20240903 09:50:22.266535    64 cmd_replication.cc:297] [replication] Succeed sending file 000180.sst to 10.0.1.182
I20240903 09:50:22.301229    63 cmd_replication.cc:297] [replication] Succeed sending file 000738.sst to 10.0.1.182
I20240903 09:50:22.418737    62 cmd_replication.cc:297] [replication] Succeed sending file 000712.sst to 10.0.1.182
I20240903 09:50:22.432060    64 cmd_replication.cc:297] [replication] Succeed sending file 000674.sst to 10.0.1.182
I20240903 09:50:22.472507    62 cmd_replication.cc:297] [replication] Succeed sending file 000736.sst to 10.0.1.182
I20240903 09:50:22.532148    64 cmd_replication.cc:297] [replication] Succeed sending file 000692.sst to 10.0.1.182
I20240903 09:50:22.618152    63 cmd_replication.cc:297] [replication] Succeed sending file 000765.sst to 10.0.1.182
I20240903 09:50:22.681921    62 cmd_replication.cc:297] [replication] Succeed sending file 000763.sst to 10.0.1.182
I20240903 09:50:22.699340    64 cmd_replication.cc:297] [replication] Succeed sending file 000713.sst to 10.0.1.182
I20240903 09:50:22.804975    64 cmd_replication.cc:297] [replication] Succeed sending file 000734.sst to 10.0.1.182
I20240903 09:50:22.831521    65 cmd_replication.cc:297] [replication] Succeed sending file 000284.sst to 10.0.1.182
I20240903 09:50:23.016659    64 cmd_replication.cc:297] [replication] Succeed sending file 000753.sst to 10.0.1.182
I20240903 09:50:23.470240    64 cmd_replication.cc:297] [replication] Succeed sending file 000335.sst to 10.0.1.182
I20240903 09:50:23.524123    65 cmd_replication.cc:297] [replication] Succeed sending file 000444.sst to 10.0.1.182
I20240903 09:50:23.630766    63 cmd_replication.cc:297] [replication] Succeed sending file 000256.sst to 10.0.1.182
I20240903 09:50:23.833221    62 cmd_replication.cc:297] [replication] Succeed sending file 000231.sst to 10.0.1.182
I20240903 09:50:24.542541    65 cmd_replication.cc:297] [replication] Succeed sending file 000599.sst to 10.0.1.182
I20240903 09:50:24.630250    64 cmd_replication.cc:297] [replication] Succeed sending file 000302.sst to 10.0.1.182
I20240903 09:50:24.730253    65 cmd_replication.cc:297] [replication] Succeed sending file 000353.sst to 10.0.1.182
I20240903 09:50:24.801339    65 cmd_replication.cc:297] [replication] Succeed sending file 000374.sst to 10.0.1.182
I20240903 09:50:24.809365    65 cmd_replication.cc:297] [replication] Succeed sending file 000788.sst to 10.0.1.182
I20240903 09:50:24.817632    65 cmd_replication.cc:297] [replication] Succeed sending file 000133.sst to 10.0.1.182
I20240903 09:50:24.862268    65 cmd_replication.cc:297] [replication] Succeed sending file 000214.sst to 10.0.1.182
I20240903 09:50:24.862474    65 cmd_replication.cc:297] [replication] Succeed sending file 000660.sst to 10.0.1.182
I20240903 09:50:24.873200    63 cmd_replication.cc:297] [replication] Succeed sending file 000411.sst to 10.0.1.182
I20240903 09:50:24.927126    62 cmd_replication.cc:297] [replication] Succeed sending file 000319.sst to 10.0.1.182
I20240903 09:50:25.391821    63 cmd_replication.cc:297] [replication] Succeed sending file 000510.sst to 10.0.1.182
I20240903 09:50:25.392629    63 cmd_replication.cc:297] [replication] Succeed sending file 000388.sst to 10.0.1.182
I20240903 09:50:25.424692    64 cmd_replication.cc:297] [replication] Succeed sending file 000460.sst to 10.0.1.182
I20240903 09:50:25.461529    63 cmd_replication.cc:297] [replication] Succeed sending file 000373.sst to 10.0.1.182
I20240903 09:50:25.463296    63 cmd_replication.cc:297] [replication] Succeed sending file 000410.sst to 10.0.1.182
I20240903 09:50:25.466998    63 cmd_replication.cc:297] [replication] Succeed sending file 000110.sst to 10.0.1.182
I20240903 09:50:25.476197    63 cmd_replication.cc:297] [replication] Succeed sending file 000196.sst to 10.0.1.182
I20240903 09:50:25.476366    63 cmd_replication.cc:297] [replication] Succeed sending file 000783.sst to 10.0.1.182
I20240903 09:50:25.476455    63 cmd_replication.cc:297] [replication] Succeed sending file OPTIONS-000793 to 10.0.1.182
I20240903 09:50:25.601061    62 cmd_replication.cc:297] [replication] Succeed sending file 000487.sst to 10.0.1.182
I20240903 09:50:26.023718    64 cmd_replication.cc:297] [replication] Succeed sending file 000603.sst to 10.0.1.182
I20240903 09:50:26.118242    64 cmd_replication.cc:297] [replication] Succeed sending file 000359.sst to 10.0.1.182
I20240903 09:50:26.121728    62 cmd_replication.cc:297] [replication] Succeed sending file 000605.sst to 10.0.1.182
I20240903 09:50:26.138623    64 cmd_replication.cc:297] [replication] Succeed sending file 000389.sst to 10.0.1.182
I20240903 09:50:26.152069    64 cmd_replication.cc:297] [replication] Succeed sending file 000769.sst to 10.0.1.182
I20240903 09:50:26.155491    64 cmd_replication.cc:297] [replication] Succeed sending file 000153.sst to 10.0.1.182
I20240903 09:50:26.175770    62 cmd_replication.cc:297] [replication] Succeed sending file 000367.sst to 10.0.1.182
I20240903 09:50:26.222126    64 cmd_replication.cc:297] [replication] Succeed sending file 000742.sst to 10.0.1.182
I20240903 09:50:26.222195    64 cmd_replication.cc:297] [replication] Succeed sending file MANIFEST-000791 to 10.0.1.182
I20240903 09:50:26.285246    62 cmd_replication.cc:297] [replication] Succeed sending file 000390.sst to 10.0.1.182
I20240903 09:50:26.337620    62 cmd_replication.cc:297] [replication] Succeed sending file 000034.sst to 10.0.1.182
I20240903 09:50:26.344663    62 cmd_replication.cc:297] [replication] Succeed sending file 000176.sst to 10.0.1.182
I20240903 09:50:26.344722    62 cmd_replication.cc:297] [replication] Succeed sending file 000789.sst to 10.0.1.182
I20240903 09:50:26.344758    62 cmd_replication.cc:297] [replication] Succeed sending file CURRENT to 10.0.1.182
I20240903 09:50:47.163534    33 cmd_replication.cc:60] Slave 10.0.1.182:45912, listening port: 6666, announce ip: 10.0.1.182 asks for synchronization with next sequence: 25585720 replication id: not supported, and local sequence: 25585719
I20240903 09:50:47.163610    33 cmd_replication.cc:113] New replica: 10.0.1.182:45912 was added, start incremental syncing
I20240903 09:50:48.675273    36 compaction_checker.cc:34] [compaction checker] Start the compact the column family: pubsub
I20240903 09:50:48.675350    36 compaction_checker.cc:37] [compaction checker] Compact the column family: pubsub finished, result: OK
I20240903 09:50:48.675361    36 compaction_checker.cc:34] [compaction checker] Start the compact the column family: propagate
I20240903 09:50:48.675710     6 event_listener.cc:79] [event_listener/compaction_begin] column family: propagate, job_id: 3, compaction reason: ManualCompaction, output compression type: no, base input level(files): 0(3), output level(files): 6(0), input bytes: 0, output bytes:0, is_manual_compaction:yes
I20240903 09:50:48.675760     6 event_listener.cc:102] [event_listener/subcompaction_begin] column family: propagate, job_id: 3, compaction reason: Unknown, output compression type: no
I20240903 09:50:48.731853     6 event_listener.cc:177] [event_listener/table_file_created] column family: propagate, file path: /var/lib/kvrocks/db/000794.sst, file size: 1760, job_id: 3, reason: compaction, status: OK
I20240903 09:50:48.731914     6 event_listener.cc:108] [event_listener/subcompaction_completed] column family: propagate, job_id: 3, compaction reason: Unknown, output compression type: no, base input level(files): 0, output level(files): 6, input bytes: 0, output bytes:0, is_manual_compaction:no, elapsed(micro): 0
I20240903 09:50:48.764325     6 event_listener.cc:89] [event_listener/compaction_completed] column family: propagate, job_id: 3, compaction reason: ManualCompaction, output compression type: no, base input level(files): 0(3), output level(files): 6(1), input bytes: 4886, output bytes:1760, is_manual_compaction:yes, elapsed(micro): 56177
I20240903 09:50:48.764454     6 event_listener.cc:166] [event_listener/table_file_deleted] db: /var/lib/kvrocks/db, sst file: /var/lib/kvrocks/db/000660.sst, status: OK
I20240903 09:50:48.764484     6 event_listener.cc:166] [event_listener/table_file_deleted] db: /var/lib/kvrocks/db, sst file: /var/lib/kvrocks/db/000783.sst, status: OK
I20240903 09:50:48.764508     6 event_listener.cc:166] [event_listener/table_file_deleted] db: /var/lib/kvrocks/db, sst file: /var/lib/kvrocks/db/000789.sst, status: OK
I20240903 09:50:48.815032    36 compaction_checker.cc:37] [compaction checker] Compact the column family: propagate finished, result: OK
I20240903 09:50:48.815116     7 event_listener.cc:79] [event_listener/compaction_begin] column family: propagate, job_id: 4, compaction reason: LevelMaxLevelSize, output compression type: snappy, base input level(files): 1(1), output level(files): 2(0), input bytes: 0, output bytes:0, is_manual_compaction:no
I20240903 09:50:48.815174     7 event_listener.cc:102] [event_listener/subcompaction_begin] column family: propagate, job_id: 4, compaction reason: Unknown, output compression type: no
I20240903 09:50:48.863816     7 event_listener.cc:177] [event_listener/table_file_created] column family: propagate, file path: /var/lib/kvrocks/db/000795.sst, file size: 1501, job_id: 4, reason: compaction, status: OK
I20240903 09:50:48.863858     7 event_listener.cc:108] [event_listener/subcompaction_completed] column family: propagate, job_id: 4, compaction reason: Unknown, output compression type: no, base input level(files): 1, output level(files): 2, input bytes: 0, output bytes:0, is_manual_compaction:no, elapsed(micro): 0
I20240903 09:50:48.911970     7 event_listener.cc:89] [event_listener/compaction_completed] column family: propagate, job_id: 4, compaction reason: LevelMaxLevelSize, output compression type: snappy, base input level(files): 1(1), output level(files): 2(1), input bytes: 1760, output bytes:1501, is_manual_compaction:no, elapsed(micro): 48703
I20240903 09:50:48.912083     7 event_listener.cc:166] [event_listener/table_file_deleted] db: /var/lib/kvrocks/db, sst file: /var/lib/kvrocks/db/000794.sst, status: OK
I20240903 09:50:48.912132     7 event_listener.cc:79] [event_listener/compaction_begin] column family: propagate, job_id: 5, compaction reason: LevelMaxLevelSize, output compression type: snappy, base input level(files): 2(1), output level(files): 3(0), input bytes: 0, output bytes:0, is_manual_compaction:no
I20240903 09:50:48.912160     7 event_listener.cc:102] [event_listener/subcompaction_begin] column family: propagate, job_id: 5, compaction reason: Unknown, output compression type: no
I20240903 09:50:48.977860     7 event_listener.cc:177] [event_listener/table_file_created] column family: propagate, file path: /var/lib/kvrocks/db/000796.sst, file size: 1501, job_id: 5, reason: compaction, status: OK
I20240903 09:50:48.977905     7 event_listener.cc:108] [event_listener/subcompaction_completed] column family: propagate, job_id: 5, compaction reason: Unknown, output compression type: no, base input level(files): 2, output level(files): 3, input bytes: 0, output bytes:0, is_manual_compaction:no, elapsed(micro): 0
I20240903 09:50:49.025768     7 event_listener.cc:89] [event_listener/compaction_completed] column family: propagate, job_id: 5, compaction reason: LevelMaxLevelSize, output compression type: snappy, base input level(files): 2(1), output level(files): 3(1), input bytes: 1501, output bytes:1501, is_manual_compaction:no, elapsed(micro): 65767
I20240903 09:50:49.025885     7 event_listener.cc:166] [event_listener/table_file_deleted] db: /var/lib/kvrocks/db, sst file: /var/lib/kvrocks/db/000795.sst, status: OK
I20240903 09:50:49.025926     7 event_listener.cc:79] [event_listener/compaction_begin] column family: propagate, job_id: 6, compaction reason: LevelMaxLevelSize, output compression type: snappy, base input level(files): 3(1), output level(files): 4(0), input bytes: 0, output bytes:0, is_manual_compaction:no
I20240903 09:50:49.025954     7 event_listener.cc:102] [event_listener/subcompaction_begin] column family: propagate, job_id: 6, compaction reason: Unknown, output compression type: no
I20240903 09:50:49.057718     7 event_listener.cc:177] [event_listener/table_file_created] column family: propagate, file path: /var/lib/kvrocks/db/000797.sst, file size: 1501, job_id: 6, reason: compaction, status: OK
I20240903 09:50:49.057749     7 event_listener.cc:108] [event_listener/subcompaction_completed] column family: propagate, job_id: 6, compaction reason: Unknown, output compression type: no, base input level(files): 3, output level(files): 4, input bytes: 0, output bytes:0, is_manual_compaction:no, elapsed(micro): 0
I20240903 09:50:49.089035     7 event_listener.cc:89] [event_listener/compaction_completed] column family: propagate, job_id: 6, compaction reason: LevelMaxLevelSize, output compression type: snappy, base input level(files): 3(1), output level(files): 4(1), input bytes: 1501, output bytes:1501, is_manual_compaction:no, elapsed(micro): 31809
I20240903 09:50:49.089124     7 event_listener.cc:166] [event_listener/table_file_deleted] db: /var/lib/kvrocks/db, sst file: /var/lib/kvrocks/db/000796.sst, status: OK
I20240903 09:50:49.089169     7 event_listener.cc:79] [event_listener/compaction_begin] column family: propagate, job_id: 7, compaction reason: LevelMaxLevelSize, output compression type: snappy, base input level(files): 4(1), output level(files): 5(0), input bytes: 0, output bytes:0, is_manual_compaction:no
I20240903 09:50:49.089195     7 event_listener.cc:102] [event_listener/subcompaction_begin] column family: propagate, job_id: 7, compaction reason: Unknown, output compression type: no
I20240903 09:50:49.136545     7 event_listener.cc:177] [event_listener/table_file_created] column family: propagate, file path: /var/lib/kvrocks/db/000798.sst, file size: 1501, job_id: 7, reason: compaction, status: OK
I20240903 09:50:49.136580     7 event_listener.cc:108] [event_listener/subcompaction_completed] column family: propagate, job_id: 7, compaction reason: Unknown, output compression type: no, base input level(files): 4, output level(files): 5, input bytes: 0, output bytes:0, is_manual_compaction:no, elapsed(micro): 0
I20240903 09:50:49.171208     7 event_listener.cc:89] [event_listener/compaction_completed] column family: propagate, job_id: 7, compaction reason: LevelMaxLevelSize, output compression type: snappy, base input level(files): 4(1), output level(files): 5(1), input bytes: 1501, output bytes:1501, is_manual_compaction:no, elapsed(micro): 47400
I20240903 09:50:49.171315     7 event_listener.cc:166] [event_listener/table_file_deleted] db: /var/lib/kvrocks/db, sst file: /var/lib/kvrocks/db/000797.sst, status: OK
I20240903 09:50:49.171357     7 event_listener.cc:79] [event_listener/compaction_begin] column family: propagate, job_id: 8, compaction reason: LevelMaxLevelSize, output compression type: snappy, base input level(files): 5(1), output level(files): 6(0), input bytes: 0, output bytes:0, is_manual_compaction:no
I20240903 09:50:49.171402     7 event_listener.cc:102] [event_listener/subcompaction_begin] column family: propagate, job_id: 8, compaction reason: Unknown, output compression type: no
I20240903 09:50:49.202711     7 event_listener.cc:177] [event_listener/table_file_created] column family: propagate, file path: /var/lib/kvrocks/db/000799.sst, file size: 1501, job_id: 8, reason: compaction, status: OK
I20240903 09:50:49.202746     7 event_listener.cc:108] [event_listener/subcompaction_completed] column family: propagate, job_id: 8, compaction reason: Unknown, output compression type: no, base input level(files): 5, output level(files): 6, input bytes: 0, output bytes:0, is_manual_compaction:no, elapsed(micro): 0
I20240903 09:50:49.234180     7 event_listener.cc:89] [event_listener/compaction_completed] column family: propagate, job_id: 8, compaction reason: LevelMaxLevelSize, output compression type: snappy, base input level(files): 5(1), output level(files): 6(1), input bytes: 1501, output bytes:1501, is_manual_compaction:no, elapsed(micro): 31359
I20240903 09:50:49.234274     7 event_listener.cc:166] [event_listener/table_file_deleted] db: /var/lib/kvrocks/db, sst file: /var/lib/kvrocks/db/000798.sst, status: OK
I20240903 09:50:58.694487    35 server.cc:814] [server] Clean checkpoint successfully
```

Slave Log:

```
I20240903 09:50:18.853986     1 main.cc:142] kvrocks version 2.9.0
I20240903 09:50:18.901003     1 storage.cc:387] [storage] Success to load the data from disk: 13 ms
I20240903 09:50:18.903291     1 worker.cc:72] [worker] Listening on: 0.0.0.0:6666
I20240903 09:50:18.903457     1 worker.cc:72] [worker] Listening on: 0.0.0.0:6666
I20240903 09:50:18.903563     1 worker.cc:72] [worker] Listening on: 0.0.0.0:6666
I20240903 09:50:18.903661     1 worker.cc:72] [worker] Listening on: 0.0.0.0:6666
I20240903 09:50:18.903757     1 worker.cc:72] [worker] Listening on: 0.0.0.0:6666
I20240903 09:50:18.903856     1 worker.cc:72] [worker] Listening on: 0.0.0.0:6666
I20240903 09:50:18.903975     1 worker.cc:72] [worker] Listening on: 0.0.0.0:6666
I20240903 09:50:18.904074     1 worker.cc:72] [worker] Listening on: 0.0.0.0:6666
W20240903 09:50:18.904390     1 replication.cc:349] Clean old synced checkpoint successfully
I20240903 09:50:18.904466     1 worker.cc:564] [worker] Thread #139711001622208 started
I20240903 09:50:18.904487     1 worker.cc:564] [worker] Thread #139711010014912 started
I20240903 09:50:18.904529     1 worker.cc:564] [worker] Thread #139711064569536 started
I20240903 09:50:18.904559     1 worker.cc:564] [worker] Thread #139711056176832 started
I20240903 09:50:18.904585     1 worker.cc:564] [worker] Thread #139711047784128 started
I20240903 09:50:18.904613     1 worker.cc:564] [worker] Thread #139711039391424 started
I20240903 09:50:18.904659     1 worker.cc:564] [worker] Thread #139711030998720 started
I20240903 09:50:18.904704     1 worker.cc:564] [worker] Thread #139711022606016 started
I20240903 09:50:18.904826     1 server.cc:228] [server] Ready to accept connections
I20240903 09:50:18.905002   133 replication.cc:401] [replication] Auth request was sent, waiting for response
I20240903 09:50:18.905215   133 replication.cc:417] [replication] Auth response was received, continue...
I20240903 09:50:18.905231   133 replication.cc:424] [replication] Check db name request was sent, waiting for response
I20240903 09:50:18.905330   133 replication.cc:444] [replication] DB name is valid, continue...
I20240903 09:50:18.905355   133 replication.cc:462] [replication] replconf request was sent, waiting for response
I20240903 09:50:18.905504   133 replication.cc:488] [replication] replconf is ok, start psync
I20240903 09:50:18.905607   133 replication.cc:518] [replication] Try to use psync, next seq: 1
I20240903 09:50:18.906639   133 replication.cc:551] [replication] Failed to psync, error: -ERR sequence out of range, please use fullsync, switch to fullsync
I20240903 09:50:18.906685   133 replication.cc:401] [replication] Auth request was sent, waiting for response
I20240903 09:50:18.906796   133 replication.cc:417] [replication] Auth response was received, continue...
I20240903 09:50:18.906812   133 replication.cc:613] [replication] Start syncing data with fullsync
I20240903 09:50:18.913395   133 replication.cc:701] [replication] Succeeded fetching full data files info, fetching files in parallel
I20240903 09:50:19.078567   145 replication.cc:805] [fetch] Fetched 000787.sst, crc32: 0, skip count: 0, fetch count: 1, progress: 1/84
I20240903 09:50:19.133827   148 replication.cc:805] [fetch] Fetched 000774.sst, crc32: 0, skip count: 0, fetch count: 2, progress: 2/84
I20240903 09:50:19.180766   145 replication.cc:805] [fetch] Fetched 000647.sst, crc32: 0, skip count: 0, fetch count: 3, progress: 3/84
I20240903 09:50:19.320425   148 replication.cc:805] [fetch] Fetched 000782.sst, crc32: 0, skip count: 0, fetch count: 4, progress: 4/84
I20240903 09:50:19.366942   145 replication.cc:805] [fetch] Fetched 000781.sst, crc32: 0, skip count: 0, fetch count: 5, progress: 5/84
I20240903 09:50:19.436174   148 replication.cc:805] [fetch] Fetched 000613.sst, crc32: 0, skip count: 0, fetch count: 6, progress: 6/84
I20240903 09:50:19.485416   147 replication.cc:805] [fetch] Fetched 000780.sst, crc32: 0, skip count: 0, fetch count: 7, progress: 7/84
I20240903 09:50:19.498481   145 replication.cc:805] [fetch] Fetched 000616.sst, crc32: 0, skip count: 0, fetch count: 8, progress: 8/84
I20240903 09:50:19.599216   147 replication.cc:805] [fetch] Fetched 000764.sst, crc32: 0, skip count: 0, fetch count: 9, progress: 9/84
I20240903 09:50:19.659133   145 replication.cc:805] [fetch] Fetched 000028.sst, crc32: 0, skip count: 0, fetch count: 10, progress: 10/84
I20240903 09:50:19.770090   147 replication.cc:805] [fetch] Fetched 000607.sst, crc32: 0, skip count: 0, fetch count: 11, progress: 11/84
I20240903 09:50:20.721870   146 replication.cc:805] [fetch] Fetched 000784.sst, crc32: 0, skip count: 0, fetch count: 12, progress: 12/84
I20240903 09:50:20.730985   148 replication.cc:805] [fetch] Fetched 000181.sst, crc32: 0, skip count: 0, fetch count: 13, progress: 13/84
I20240903 09:50:20.731966   145 replication.cc:805] [fetch] Fetched 000118.sst, crc32: 0, skip count: 0, fetch count: 14, progress: 14/84
I20240903 09:50:20.930294   145 replication.cc:805] [fetch] Fetched 000650.sst, crc32: 0, skip count: 0, fetch count: 15, progress: 15/84
I20240903 09:50:21.016780   147 replication.cc:805] [fetch] Fetched 000635.sst, crc32: 0, skip count: 0, fetch count: 16, progress: 16/84
I20240903 09:50:21.023801   146 replication.cc:805] [fetch] Fetched 000627.sst, crc32: 0, skip count: 0, fetch count: 17, progress: 17/84
I20240903 09:50:21.098882   145 replication.cc:805] [fetch] Fetched 000677.sst, crc32: 0, skip count: 0, fetch count: 18, progress: 18/84
I20240903 09:50:21.268332   145 replication.cc:805] [fetch] Fetched 000697.sst, crc32: 0, skip count: 0, fetch count: 19, progress: 19/84
I20240903 09:50:21.386924   146 replication.cc:805] [fetch] Fetched 000633.sst, crc32: 0, skip count: 0, fetch count: 20, progress: 20/84
I20240903 09:50:21.423511   145 replication.cc:805] [fetch] Fetched 000735.sst, crc32: 0, skip count: 0, fetch count: 21, progress: 21/84
I20240903 09:50:21.517524   146 replication.cc:805] [fetch] Fetched 000634.sst, crc32: 0, skip count: 0, fetch count: 22, progress: 22/84
I20240903 09:50:21.538806   148 replication.cc:805] [fetch] Fetched 000092.sst, crc32: 0, skip count: 0, fetch count: 23, progress: 23/84
I20240903 09:50:21.590159   145 replication.cc:805] [fetch] Fetched 000754.sst, crc32: 0, skip count: 0, fetch count: 24, progress: 24/84
I20240903 09:50:21.942417   147 replication.cc:805] [fetch] Fetched 000068.sst, crc32: 0, skip count: 0, fetch count: 25, progress: 25/84
I20240903 09:50:22.036463   148 replication.cc:805] [fetch] Fetched 000171.sst, crc32: 0, skip count: 0, fetch count: 26, progress: 26/84
I20240903 09:50:22.086582   148 replication.cc:805] [fetch] Fetched 000676.sst, crc32: 0, skip count: 0, fetch count: 27, progress: 27/84
I20240903 09:50:22.088688   146 replication.cc:805] [fetch] Fetched 000025.sst, crc32: 0, skip count: 0, fetch count: 28, progress: 28/84
I20240903 09:50:22.122203   147 replication.cc:805] [fetch] Fetched 000150.sst, crc32: 0, skip count: 0, fetch count: 29, progress: 29/84
I20240903 09:50:22.205904   148 replication.cc:805] [fetch] Fetched 000694.sst, crc32: 0, skip count: 0, fetch count: 30, progress: 30/84
I20240903 09:50:22.313501   147 replication.cc:805] [fetch] Fetched 000675.sst, crc32: 0, skip count: 0, fetch count: 31, progress: 31/84
I20240903 09:50:22.373884   148 replication.cc:805] [fetch] Fetched 000714.sst, crc32: 0, skip count: 0, fetch count: 32, progress: 32/84
I20240903 09:50:22.380805   145 replication.cc:805] [fetch] Fetched 000334.sst, crc32: 0, skip count: 0, fetch count: 33, progress: 33/84
I20240903 09:50:22.471745   147 replication.cc:805] [fetch] Fetched 000693.sst, crc32: 0, skip count: 0, fetch count: 34, progress: 34/84
I20240903 09:50:22.506485   146 replication.cc:805] [fetch] Fetched 000180.sst, crc32: 0, skip count: 0, fetch count: 35, progress: 35/84
I20240903 09:50:22.542912   148 replication.cc:805] [fetch] Fetched 000738.sst, crc32: 0, skip count: 0, fetch count: 36, progress: 36/84
I20240903 09:50:22.657269   147 replication.cc:805] [fetch] Fetched 000712.sst, crc32: 0, skip count: 0, fetch count: 37, progress: 37/84
I20240903 09:50:22.670325   146 replication.cc:805] [fetch] Fetched 000674.sst, crc32: 0, skip count: 0, fetch count: 38, progress: 38/84
I20240903 09:50:22.680753   147 replication.cc:805] [fetch] Fetched 000736.sst, crc32: 0, skip count: 0, fetch count: 39, progress: 39/84
I20240903 09:50:22.729039   146 replication.cc:805] [fetch] Fetched 000692.sst, crc32: 0, skip count: 0, fetch count: 40, progress: 40/84
I20240903 09:50:22.823185   148 replication.cc:805] [fetch] Fetched 000765.sst, crc32: 0, skip count: 0, fetch count: 41, progress: 41/84
I20240903 09:50:22.885578   147 replication.cc:805] [fetch] Fetched 000763.sst, crc32: 0, skip count: 0, fetch count: 42, progress: 42/84
I20240903 09:50:22.899166   146 replication.cc:805] [fetch] Fetched 000713.sst, crc32: 0, skip count: 0, fetch count: 43, progress: 43/84
I20240903 09:50:23.019675   146 replication.cc:805] [fetch] Fetched 000734.sst, crc32: 0, skip count: 0, fetch count: 44, progress: 44/84
I20240903 09:50:23.034586   145 replication.cc:805] [fetch] Fetched 000284.sst, crc32: 0, skip count: 0, fetch count: 45, progress: 45/84
I20240903 09:50:23.191298   146 replication.cc:805] [fetch] Fetched 000753.sst, crc32: 0, skip count: 0, fetch count: 46, progress: 46/84
I20240903 09:50:23.630498   146 replication.cc:805] [fetch] Fetched 000335.sst, crc32: 0, skip count: 0, fetch count: 47, progress: 47/84
I20240903 09:50:23.683187   145 replication.cc:805] [fetch] Fetched 000444.sst, crc32: 0, skip count: 0, fetch count: 48, progress: 48/84
I20240903 09:50:23.783576   148 replication.cc:805] [fetch] Fetched 000256.sst, crc32: 0, skip count: 0, fetch count: 49, progress: 49/84
I20240903 09:50:24.066447   147 replication.cc:805] [fetch] Fetched 000231.sst, crc32: 0, skip count: 0, fetch count: 50, progress: 50/84
I20240903 09:50:24.605947   145 replication.cc:805] [fetch] Fetched 000599.sst, crc32: 0, skip count: 0, fetch count: 51, progress: 51/84
I20240903 09:50:24.671267   146 replication.cc:805] [fetch] Fetched 000302.sst, crc32: 0, skip count: 0, fetch count: 52, progress: 52/84
I20240903 09:50:24.782250   145 replication.cc:805] [fetch] Fetched 000353.sst, crc32: 0, skip count: 0, fetch count: 53, progress: 53/84
I20240903 09:50:24.840951   145 replication.cc:805] [fetch] Fetched 000374.sst, crc32: 0, skip count: 0, fetch count: 54, progress: 54/84
I20240903 09:50:24.847146   145 replication.cc:805] [fetch] Fetched 000788.sst, crc32: 0, skip count: 0, fetch count: 55, progress: 55/84
I20240903 09:50:24.847613   145 replication.cc:805] [fetch] Fetched 000133.sst, crc32: 0, skip count: 0, fetch count: 56, progress: 56/84
I20240903 09:50:24.880555   145 replication.cc:805] [fetch] Fetched 000214.sst, crc32: 0, skip count: 0, fetch count: 57, progress: 57/84
I20240903 09:50:24.881171   145 replication.cc:805] [fetch] Fetched 000660.sst, crc32: 0, skip count: 0, fetch count: 58, progress: 58/84
I20240903 09:50:24.917618   148 replication.cc:805] [fetch] Fetched 000411.sst, crc32: 0, skip count: 0, fetch count: 59, progress: 59/84
I20240903 09:50:24.989461   147 replication.cc:805] [fetch] Fetched 000319.sst, crc32: 0, skip count: 0, fetch count: 60, progress: 60/84
I20240903 09:50:25.396998   148 replication.cc:805] [fetch] Fetched 000510.sst, crc32: 0, skip count: 0, fetch count: 61, progress: 61/84
I20240903 09:50:25.405366   148 replication.cc:805] [fetch] Fetched 000388.sst, crc32: 0, skip count: 0, fetch count: 62, progress: 62/84
I20240903 09:50:25.455061   146 replication.cc:805] [fetch] Fetched 000460.sst, crc32: 0, skip count: 0, fetch count: 63, progress: 63/84
I20240903 09:50:25.460081   148 replication.cc:805] [fetch] Fetched 000373.sst, crc32: 0, skip count: 0, fetch count: 64, progress: 64/84
I20240903 09:50:25.460907   148 replication.cc:805] [fetch] Fetched 000410.sst, crc32: 0, skip count: 0, fetch count: 65, progress: 65/84
I20240903 09:50:25.461334   148 replication.cc:805] [fetch] Fetched 000110.sst, crc32: 0, skip count: 0, fetch count: 66, progress: 66/84
I20240903 09:50:25.467180   148 replication.cc:805] [fetch] Fetched 000196.sst, crc32: 0, skip count: 0, fetch count: 67, progress: 67/84
I20240903 09:50:25.467353   148 replication.cc:805] [fetch] Fetched 000783.sst, crc32: 0, skip count: 0, fetch count: 68, progress: 68/84
I20240903 09:50:25.467506   148 replication.cc:805] [fetch] Fetched OPTIONS-000793, crc32: 0, skip count: 0, fetch count: 69, progress: 69/84
I20240903 09:50:25.593780   147 replication.cc:805] [fetch] Fetched 000487.sst, crc32: 0, skip count: 0, fetch count: 70, progress: 70/84
I20240903 09:50:26.014602   146 replication.cc:805] [fetch] Fetched 000603.sst, crc32: 0, skip count: 0, fetch count: 71, progress: 71/84
I20240903 09:50:26.118364   146 replication.cc:805] [fetch] Fetched 000359.sst, crc32: 0, skip count: 0, fetch count: 72, progress: 72/84
I20240903 09:50:26.121237   147 replication.cc:805] [fetch] Fetched 000605.sst, crc32: 0, skip count: 0, fetch count: 73, progress: 73/84
I20240903 09:50:26.139446   146 replication.cc:805] [fetch] Fetched 000389.sst, crc32: 0, skip count: 0, fetch count: 74, progress: 74/84
I20240903 09:50:26.146734   146 replication.cc:805] [fetch] Fetched 000769.sst, crc32: 0, skip count: 0, fetch count: 75, progress: 75/84
I20240903 09:50:26.147277   146 replication.cc:805] [fetch] Fetched 000153.sst, crc32: 0, skip count: 0, fetch count: 76, progress: 76/84
I20240903 09:50:26.181603   147 replication.cc:805] [fetch] Fetched 000367.sst, crc32: 0, skip count: 0, fetch count: 77, progress: 77/84
I20240903 09:50:26.219069   146 replication.cc:805] [fetch] Fetched 000742.sst, crc32: 0, skip count: 0, fetch count: 78, progress: 78/84
I20240903 09:50:26.219228   146 replication.cc:805] [fetch] Fetched MANIFEST-000791, crc32: 0, skip count: 0, fetch count: 79, progress: 79/84
I20240903 09:50:26.278401   147 replication.cc:805] [fetch] Fetched 000390.sst, crc32: 0, skip count: 0, fetch count: 80, progress: 80/84
I20240903 09:50:26.318702   147 replication.cc:805] [fetch] Fetched 000034.sst, crc32: 0, skip count: 0, fetch count: 81, progress: 81/84
I20240903 09:50:26.325289   147 replication.cc:805] [fetch] Fetched 000176.sst, crc32: 0, skip count: 0, fetch count: 82, progress: 82/84
I20240903 09:50:26.325376   147 replication.cc:805] [fetch] Fetched 000789.sst, crc32: 0, skip count: 0, fetch count: 83, progress: 83/84
I20240903 09:50:26.325443   147 replication.cc:805] [fetch] Fetched CURRENT, crc32: 0, skip count: 0, fetch count: 84, progress: 84/84
I20240903 09:50:26.325528   133 replication.cc:717] [replication] Succeeded fetching files in parallel, restoring the backup
I20240903 09:50:26.325563   133 server.cc:1339] [server] Disconnecting slaves...
I20240903 09:50:26.325577   133 server.cc:1343] [server] Stopping the task runner and clear task queue...
I20240903 09:50:26.325742   133 server.cc:1357] [server] Waiting workers for finishing executing commands...
I20240903 09:50:26.325755   133 server.cc:1365] [server] Waiting for closing DB...
I20240903 09:50:47.142118   133 storage.cc:387] [storage] Success to load the data from disk: 331 ms
I20240903 09:50:47.142486   133 replication.cc:732] [replication] Succeeded restoring the backup, fullsync was finish
I20240903 09:50:47.143034   133 replication.cc:401] [replication] Auth request was sent, waiting for response
I20240903 09:50:47.143190   133 replication.cc:417] [replication] Auth response was received, continue...
I20240903 09:50:47.143208   133 replication.cc:401] [replication] Auth request was sent, waiting for response
I20240903 09:50:47.143339   133 replication.cc:417] [replication] Auth response was received, continue...
I20240903 09:50:47.143358   133 replication.cc:424] [replication] Check db name request was sent, waiting for response
I20240903 09:50:47.143453   133 replication.cc:444] [replication] DB name is valid, continue...
I20240903 09:50:47.143471   133 replication.cc:462] [replication] replconf request was sent, waiting for response
I20240903 09:50:47.143574   133 replication.cc:488] [replication] replconf is ok, start psync
I20240903 09:50:47.143678   133 replication.cc:518] [replication] Try to use psync, next seq: 25585720
I20240903 09:50:47.143887   133 replication.cc:555] [replication] PSync is ok, start increment batch loop
```

### Are you willing to submit a PR?

- [ ] I'm willing to submit a PR!

### PR DESCRIPTION
**Pull request by git-hulk**
Namespaces would store inside DB if the repl-namespace-enabled was set to yes.
Then replicas will intercept and parse the increment replication log to
see if it needs to reload namespaces. But it won't have the namespace update log
when doing the full sync, so we need to reload from DB once the full replication is done.

This closes #2520

### CODE REVIEW

File: src/cluster/replication.cc [hunk 1]
```diff
@@ -732,6 +732,13 @@ ReplicationThread::CBState ReplicationThread::fullSyncReadCB(bufferevent *bev) {
       LOG(INFO) << "[replication] Succeeded restoring the backup, fullsync was finish";
       post_fullsync_cb_();
 
+      // It needs to reload namespaces from DB after the full sync is done,
+      // or namespaces are not visible in the replica.
+      s = srv_->GetNamespace()->LoadAndRewrite();
+      if (!s.IsOK()) {
+        LOG(ERROR) << "[replication] Failed to load and rewrite namespace: " << s.Msg();
+      }
+
```
Comment (caipengbo) [inline src/cluster/replication.cc:741]: Extract a `PostFullSync` function, move it to this function?

**Comment by mapleFU** [comment]
> But it won't have the namespace update log when doing the full sync, so we need to reload from DB once the full replication is done.

Can you point out the reason here?

**Review by PragmaTwice — APPROVED** [review]

File: src/cluster/replication.cc (hunk 1 above)
Comment (git-hulk) [reply src/cluster/replication.cc:741]: We have `post_fullsync_cb` now, but it's used for cleaning resources if failed to do the full sync. So it should be not good to put this inside that.

**Comment by git-hulk** [comment]
> > But it won't have the namespace update log when doing the full sync, so we need to reload from DB once the full replication is done.
> 
> Can you point out the reason here?

What's the meaning of this comment? Do you mean why the full sync won't propagate the namespace change log?

File: src/cluster/replication.cc (hunk 1 above)
Comment (caipengbo) [reply src/cluster/replication.cc:741]: Isn't it a callback function after successfully loading the data?

https://github.com/apache/kvrocks/blob/2836bf02877fa9853af6047dc35b206dea7330f6/src/server/server.cc#L284-L290

Comment (git-hulk) [reply src/cluster/replication.cc:741]: No indeed, it should be used for resetting resources corresponding to `pre_fullsync_cb`. That said, it must be called once if the `pre_fullsync_cb` was invoked. I will submit another PR to fix #2511 which is caused by that didn't call `post_fullsync_cb` while failing to restore DB.

**Comment by mapleFU** [comment]
> Do you mean why the full sync won't propagate the namespace change log?

Yes I'm learning the code here, it would help if you can point the reason out

**Review by caipengbo — APPROVED** [review]

**Review by mapleFU — APPROVED** [review]
Ah I got to know this, since https://github.com/apache/kvrocks/pull/1776 do not reload when ns is added...
