### PR TITLE
Fix modernize-make-unique warning reported by clang-tidy

### LINKED ISSUE #1096: Fix `modernize-make-unique` warning reported by clang-tidy
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-kvrocks/issues) and found no similar issues.

### Motivation

*This issue is tracked by #1029.*

***We welcome new contributors to take these issues as a beginning of a deep dive to kvrocks***

Currently we have enabled lots of clang-tidy checks, but there are so many reports already exist in the kvrocks code, so we cannot treat these report as errors to block future PR with some clang-tidy reported warnings in CI.

Hence the goal of this issue is to solve all `modernize-make-unique` tagged clang-tidy reports, and then enable `warnings-as-errors` for this specific check in `.clang-tidy`.

To get clang-tidy reports for latest kvrocks code, there are several ways: you can run `./x.py check tidy` locally, or check the log of the latest run of GitHub Actions on the unstable branch (e.g. https://github.com/apache/incubator-kvrocks/actions/runs/3449328741/jobs/5757148924#step:8:916). To be friendly for new contributors, we list all `modernize-make-unique` tagged reports below, so in normal cases you can just follow the log below and fix them one by one.

```log
/home/runner/work/incubator-kvrocks/incubator-kvrocks/src/server/server.cc:233:25: warning: use std::make_unique instead [modernize-make-unique]
  replication_thread_ = std::unique_ptr<ReplicationThread>(new ReplicationThread(host, master_listen_port, this));
                        ^~~~~~~~~~~~~~~                    ~~~~~~~~~~~~~~~~~~~~~~                              ~
                        std::make_unique
/home/runner/work/incubator-kvrocks/incubator-kvrocks/src/storage/storage.cc:950:14: warning: use std::make_unique instead [modernize-make-unique]
  src_reader.reset(new rocksdb::SequentialFileWrapper(src_file.get()));
            ~^~~~~ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~              ~
             = std::make_unique<rocksdb::SequentialFileWrapper>
```

Some of these reports will give modification suggestions in the log, you can refer to them directly; otherwise, you need to understand the content of the warning and combine your C++ knowledge to fix it. (Fortunately, most reports (except those by clang static analyzer) are intuitive and easy to fix.)

When you fixed these all reports listed above, you can now add the check `modernize-make-unique` to `warnings-as-errors` in `.clang-tidy` (in the root dir of the repo): We show a sample diff below to illustrate how to modify `.clang-tidy`:

```diff
--- a/.clang-tidy
+++ b/.clang-tidy
@@ -1,7 +1,7 @@
 # refer to https://clang.llvm.org/extra/clang-tidy/checks/list.html
 Checks: ...

-WarningsAsErrors: ...
+WarningsAsErrors: ..., modernize-make-unique
```

Then, if all of the above are completed, congratulations, you can submit a PR for your changes now!

### Solution

_No response_

### Are you willing to submit a PR?

- [ ] I'm willing to submit a PR!

### PR DESCRIPTION
**Pull request by dl239**
fix #1096

### CODE REVIEW

File: src/storage/storage.cc [hunk 1]
```diff
@@ -946,8 +946,7 @@ bool Storage::ReplDataManager::FileExists(Storage *storage, const std::string &d
   uint64_t size;
   s = storage->env_->GetFileSize(file_path, &size);
   if (!s.ok()) return false;
-  std::unique_ptr<rocksdb::SequentialFileWrapper> src_reader;
-  src_reader.reset(new rocksdb::SequentialFileWrapper(src_file.get()));
+  auto src_reader = std::make_unique<rocksdb::SequentialFileWrapper>(rocksdb::SequentialFileWrapper(src_file.get()));
```
Comment (PragmaTwice) [inline src/storage/storage.cc]:
```suggestion
  auto src_reader = std::make_unique<rocksdb::SequentialFileWrapper>(src_file.get());
```

File: src/server/server.cc [hunk 2]
```diff
@@ -230,7 +230,7 @@ Status Server::AddMaster(std::string host, uint32_t port, bool force_reconnect)
   // replication, and uses 'listen-port + 1' as thread listening port.
   uint32_t master_listen_port = port;
   if (GetConfig()->master_use_repl_port) master_listen_port += 1;
-  replication_thread_ = std::unique_ptr<ReplicationThread>(new ReplicationThread(host, master_listen_port, this));
+  replication_thread_ = std::make_unique<ReplicationThread>(ReplicationThread(host, master_listen_port, this));
```
Comment (PragmaTwice) [inline src/server/server.cc]:
```suggestion
  replication_thread_ = std::make_unique<ReplicationThread>(host, master_listen_port, this);
```

**Review by PragmaTwice — APPROVED** [review]

**Comment by PragmaTwice** [comment]
Thanks for your contribution!
