### PR TITLE
fix: replication tests should wait for server restarted

### LINKED ISSUE #656: Executing test client: couldn't open socket: connection refused
Report: https://github.com/apache/incubator-kvrocks/runs/6981007645?check_suite_focus=true#step:10:703

### PR DESCRIPTION
**Pull request by tisonkun**
This fixes #656.

This patch is uncompleted. @git-hulk it seems `$stdout` in tcl files doesn't mean stdout from tty. Do you have any background about this test logic?

The issue we should overcome here is to determinately wait for kvrocks server up, instead of sleep 1 second which is unstable.

### CODE REVIEW

File: src/server.cc [hunk 1]
```diff
@@ -167,6 +167,8 @@ Status Server::Start() {
     }
   });
 
+  std::cout << "Ready to accept connections\n";
```
Comment (tisonkun) [inline src/server.cc]: Perhaps we should send this line to log and find a way for tests reading logs.

Comment (PragmaTwice) [inline src/server.cc]:
```suggestion
  LOG(INFO) << "Ready to accept connections";
```
Is this what you need?

**Comment by git-hulk** [comment]
@tisonkun You're right, we supported to send logs to stdout recently. Need to set `log-dir` to `stdout` on https://github.com/apache/incubator-kvrocks/blob/unstable/tests/tcl/tests/assets/default.conf

File: src/server.cc (hunk 1 above)
Comment (tisonkun) [reply src/server.cc]: However TCL tests handle log files hacky and I tend to send this information to stdout now.

**Comment by tisonkun** [comment]
> @tisonkun You're right, we supported to send logs to stdout recently. Need to set `log-dir` to `stdout` on https://github.com/apache/incubator-kvrocks/blob/unstable/tests/tcl/tests/assets/default.conf

Actually if you search `kvrocks.INFO` we hardcode several file path to the default log path..

I'm sending the "Ready to accept connections"  info to stdout for now and see whether we don't suffer from the flaky test. We may later improve stdout and logging logic.

File: tests/tcl/tests/support/server.tcl [hunk 2]
```diff
@@ -403,7 +403,6 @@ proc start_server {options {code undefined}} {
 
     set unixsocket [file normalize [format "%s/%s" [dict get $config "dir"] "socket"]]
     dict set config "unixsocket" $unixsocket
-    dict set config "log-dir" [format "%s/%s" [dict get $config "dir"] "stdout"]
```
Comment (tisonkun) [inline tests/tcl/tests/support/server.tcl]: We can redirect log to stdout by setting "log-dir" to "stdout", but we should later update all reference hardcode to `$dir/kvrocks.INFO`

**Comment by PragmaTwice** [comment]
A related problem: I think that kvrocks should not output anything on stdout if we set a log file (which is a regular file).

Currently kvrocks still outputs something to stdout when the log file is set, which is confusing (to have multiple output locations), e.g. we could output the version to log file or via `kvrocks -v`.

Of course we can consider this issue later so in this PR stdout is still a possible output location.

@git-hulk @tisonkun

**Comment by tisonkun** [comment]
OK. Let me push a followup commit to switch to `LOG(INFO)` version.

**Comment by PragmaTwice** [comment]
> OK. Let me push a followup commit to switch to `LOG(INFO)` version.

Just address an already-exist problem, so feel free to use stdout. 
I think we can consider this problem later, and it should not block this PR.

**Comment by tisonkun** [comment]
It seems logs are fragmented among files and we should find another way to determinately confirm server has been restarted.

**Comment by tisonkun** [comment]
@git-hulk @PragmaTwice I think this patch is ready to merge. You can give it a review now :)

File: src/server.cc [hunk 3]
```diff
@@ -167,6 +167,8 @@ Status Server::Start() {
     }
   });
 
+  LOG(INFO) << "Ready to accept connections\n";
```
Comment (PragmaTwice) [inline src/server.cc]:
```suggestion
  LOG(INFO) << "Ready to accept connections";
```
newline is automatically applied in glog

Comment (tisonkun) [reply src/server.cc]: Updated.

**Review by git-hulk — APPROVED** [review]

**Review by PragmaTwice — APPROVED** [review]
LGTM
