### PR TITLE
Fix add/delete repeated members error in zset/set/hash types

### LINKED ISSUE #1651: Add/delete repeated members will result in incorrect metadata in zset/set/hash types
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/kvrocks/issues) and found no similar issues.

### Version

OS: macOS 12.1
kvrocks branch: unstable
commitID: 60bcc3fac32d0df45e9a06ca0616d9d8d36fa579

### Minimal reproduce step

1. Execute `sadd` with multiple members including repetition. 
`sadd skey m1 m1 m2 m3`
2. Execute `srem` on the same way. 
`srem skey m1 m1`
3. Check the result of `sadd/srem` and check metadata of key `skey` with `scard`. 
`scard skey`

### What did you expect to see?

The result that execute `sadd` on redis
image

The result that execute `srem` on redis
image

### What did you see instead?

Add members with repetition into a set key
image
image

Remove members with repetition
image

As shown above, the repetitions members can't be filtered in `sadd/srem` commands, which will result in wrong metadata.

### Anything Else?

This bug is also existing in `zrem/hset/hmset/hdel`.
Using `zrem` as an example, if `zrem` is executed with repeated members, `zcard/zcount` will get inconsistent results.
image

### Are you willing to submit a PR?

- [X] I'm willing to submit a PR!

### PR DESCRIPTION
**Pull request by ChrisZMF**
Closes #1651 
Fix that zrem/sadd/srem/hset/hmset/hdel commands get incorrect results when repeated members are passed.
Use `sadd/srem` as example
```
127.0.0.1:6666> sadd skey m1 m1 m2 m3
(integer) 4
127.0.0.1:6666> scard skey
(integer) 4
127.0.0.1:6666> srem skey m1 m1
(integer) 2
127.0.0.1:6666> scard skey
(integer) 2
```
The right results should be
```
127.0.0.1:6666> sadd skey m1 m1 m2 m3
(integer) 3
127.0.0.1:6666>  scard skey
(integer) 3
127.0.0.1:6666> srem skey m1 m1
(integer) 1
127.0.0.1:6666> scard skey
(integer) 2
```
This bug will result in incorrect metadata of  zset/set/hash keys, consequently leading to wrong results while accessing keys related to the corresponding types.  More details in #1651

### CODE REVIEW

**Comment by git-hulk** [comment]
@ChrisZMF Very happy to see you back again!

File: src/types/redis_set.cc [hunk 1]
```diff
@@ -70,7 +70,11 @@ rocksdb::Status Set::Add(const Slice &user_key, const std::vector<Slice> &member
   WriteBatchLogData log_data(kRedisSet);
   batch->PutLogData(log_data.Encode());
   std::string sub_key;
+  std::unordered_set<std::string> mset;
```
Comment (mapleFU) [inline src/types/redis_set.cc]: Would `set` or `unordered_set` for `Slice` be ok here?

**Review by mapleFU — COMMENTED** [review]
So, this is because the input is first input in batch, and then, write to store. Should we insert to set only when the key is not existed, and should be insert to batch?

File: src/types/redis_hash.cc [hunk 2]
```diff
@@ -250,10 +254,14 @@ rocksdb::Status Hash::MSet(const Slice &user_key, const std::vector<FieldValue>
   auto batch = storage_->GetWriteBatchBase();
   WriteBatchLogData log_data(kRedisHash);
   batch->PutLogData(log_data.Encode());
+  std::unordered_set<std::string> field_set;
+  for (int32_t i = static_cast<int32_t>(field_values.size() - 1); i >= 0; i--) {
```
Comment (torwig) [inline src/types/redis_hash.cc]: Could we use `size_t` instead of `int32_t` here and omit the `static_cast` usage?

**Comment by git-hulk** [comment]
> So, this is because the input is first input in batch, and then, write to store. Should we insert to set only when the key is not existed, and should be insert to batch?

It may have a partial commit if the instance is broken in the middle of the operation.

File: src/types/redis_hash.cc (hunk 2 above)
Comment (mapleFU) [reply src/types/redis_hash.cc]: `std::unordered_set<std::string> field_set(field_values.begin(), field_values.end());`

I think this is ok.

**Comment by enjoy-binbin** [comment]
IMO, if you already have a fix, there is no need to open an issue here.
Although there is already an issue associated with the PR, please also update the top comment (it can be copied from issue, pictures are not so convenient, those can actually be copied with block text)

Good catch btw, did not CR

File: src/types/redis_hash.cc (hunk 2 above)
Comment (caipengbo) [reply src/types/redis_hash.cc]: Can use `for (auto it = field_values.rbegin(); it != field_values.rend(); it++)` ?

File: src/types/redis_set.cc (hunk 1 above)
Comment (ChrisZMF) [reply src/types/redis_set.cc]: `rocksdb::Slice` is not ok, it can't pass the compiling.

File: src/types/redis_hash.cc (hunk 2 above)
Comment (ChrisZMF) [reply src/types/redis_hash.cc]: `size_t` is not ok, it is unsigned type,  always `>= 0`.

`for (auto it = field_values.rbegin(); it != field_values.rend(); it++) ` could be a good choice.

**Comment by ChrisZMF** [comment]
> IMO, if you already have a fix, there is no need to open an issue here. Although there is already an issue associated with the PR, please also update the top comment (it can be copied from issue, pictures are not so convenient, those can actually be copied with block text)
> 
> Good catch btw, did not CR

Issue is used to record and describe the details of the problem. It's more convenient to get and check it in the future.
Top comment should be updated, thx.

**Comment by enjoy-binbin** [comment]
> Issue is used to record and describe the details of the problem. It's more convenient to get and check it in the future.

yean, i get your point.

PR also can record the details (in the top comment) and then merge them in as a squash commit message.
it (commit or PR or the details) also can be got and checked in the future.
In other words, a PR can actually do everything that a issue can do.

File: src/types/redis_set.cc (hunk 1 above)
Comment (mapleFU) [reply src/types/redis_set.cc]: Yeah, seems it doesn't implement `std::hash`. Lets leave it for future optimizations

**Comment by mapleFU** [comment]
This code LGTM. Would you mind format the code using `./x.py format`? Seems that CI failed here.

File: src/types/redis_hash.cc [hunk 3]
```diff
@@ -217,7 +217,11 @@ rocksdb::Status Hash::Delete(const Slice &user_key, const std::vector<Slice> &fi
   if (!s.ok()) return s.IsNotFound() ? rocksdb::Status::OK() : s;
 
   std::string sub_key, value;
+  std::unordered_set<std::string> field_set;
```
Comment (PragmaTwice) [inline src/types/redis_hash.cc]: Why do we store std::string here rather than Slice? I think it is unnecessary to store a copy of string.

File: src/types/redis_hash.cc [hunk 4]
```diff
@@ -250,28 +254,31 @@ rocksdb::Status Hash::MSet(const Slice &user_key, const std::vector<FieldValue>
   auto batch = storage_->GetWriteBatchBase();
   WriteBatchLogData log_data(kRedisHash);
   batch->PutLogData(log_data.Encode());
+  std::unordered_set<std::string> field_set;
+  for (auto it = field_values.rbegin(); it != field_values.rend(); it++) {
```
Comment (PragmaTwice) [inline src/types/redis_hash.cc:258]: Any reason to iterator the set in reverse order?

**Comment by ChrisZMF** [comment]
> > Issue is used to record and describe the details of the problem. It's more convenient to get and check it in the future.
> 
> yean, i get your point.
> 
> PR also can record the details (in the top comment) and then merge them in as a squash commit message. it (commit or PR or the details) also can be got and checked in the future. In other words, a PR can actually do everything that a issue can do.

**Comment by ChrisZMF** [comment]
> > Issue is used to record and describe the details of the problem. It's more convenient to get and check it in the future.
> 
> yean, i get your point.
> 
> PR also can record the details (in the top comment) and then merge them in as a squash commit message. it (commit or PR or the details) also can be got and checked in the future. In other words, a PR can actually do everything that a issue can do.

OK

File: src/types/redis_hash.cc (hunk 3 above)
Comment (ChrisZMF) [reply src/types/redis_hash.cc]: Slice is not supported to use as type in std::unordered_set or std::set. Any suggestions to solve it?

File: src/types/redis_hash.cc (hunk 4 above)
Comment (ChrisZMF) [reply src/types/redis_hash.cc:258]: If duplicates appear,  we have to use the last one of same member. Like in `hset hkey f1 v1 f1 v11`, 'f1 v11' should be kept.

File: src/types/redis_hash.cc (hunk 3 above)
Comment (mapleFU) [reply src/types/redis_hash.cc]: Personally I think `std::set` might works. `std::unordered_set` requires a `std::hash` or self-defined hash function.

Comment (PragmaTwice) [reply src/types/redis_hash.cc]: You can use std::string_view instead of Slice.

File: src/types/redis_hash.cc (hunk 4 above)
Comment (PragmaTwice) [reply src/types/redis_hash.cc:258]: Thanks. Got it.

File: src/types/redis_hash.cc (hunk 3 above)
Comment (ChrisZMF) [reply src/types/redis_hash.cc]: std::set is not ok either. std::string_view is a good choice, thx

**Review by caipengbo — DISMISSED** [review]

File: src/types/redis_set.cc [hunk 5]
```diff
@@ -70,7 +70,11 @@ rocksdb::Status Set::Add(const Slice &user_key, const std::vector<Slice> &member
   WriteBatchLogData log_data(kRedisSet);
   batch->PutLogData(log_data.Encode());
   std::string sub_key;
+  std::unordered_set<std::string_view> mset;
   for (const auto &member : members) {
+    if (!mset.insert(member.ToString()).second) {
```
Comment (mapleFU) [inline src/types/redis_set.cc]: better remove `ToString()`, `rocksdb::Slice` might has `ToStringView()`, or you can use `emplace({member.data(), member.size()})`

File: src/types/redis_set.cc [hunk 6]
```diff
@@ -101,7 +105,11 @@ rocksdb::Status Set::Remove(const Slice &user_key, const std::vector<Slice> &mem
   auto batch = storage_->GetWriteBatchBase();
   WriteBatchLogData log_data(kRedisSet);
   batch->PutLogData(log_data.Encode());
+  std::unordered_set<std::string_view> mset;
   for (const auto &member : members) {
+    if (!mset.insert(member.ToString()).second) {
```
Comment (mapleFU) [inline src/types/redis_set.cc]: ditto

File: src/types/redis_zset.cc [hunk 7]
```diff
@@ -545,7 +543,11 @@ rocksdb::Status ZSet::Remove(const Slice &user_key, const std::vector<Slice> &me
   batch->PutLogData(log_data.Encode());
   int removed = 0;
   std::string member_key, score_key;
+  std::unordered_set<std::string_view> mset;
   for (const auto &member : members) {
+    if (!mset.insert(member.ToString()).second) {
```
Comment (mapleFU) [inline src/types/redis_zset.cc]: ditto

**Review by mapleFU — COMMENTED** [review]
Rest LGTM, thanks!

File: src/types/redis_set.cc (hunk 5 above)
Comment (PragmaTwice) [reply src/types/redis_set.cc]: Good catch. ToString here will result in dangling reference (you cannot first construct a temporary string and then store its reference). So I think it is not "better to remove" but "need to remove".

Dangling reference is UB and may cause program to crash. And I think that is why the CI failed.

File: src/types/redis_zset.cc [hunk 8]
```diff
@@ -52,24 +52,12 @@ rocksdb::Status ZSet::Add(const Slice &user_key, ZAddFlags flags, MemberScores *
...
-    // column family many times and cause problems in the ZRANGE command.
-    //
-    // For example, we add members with `ZADD mykey 1 a 2 a` and `ZRANGE mykey 0 1`
-    // return only one member(`a`) was expected but got the member `a` twice now.
-    //
-    // The root cause of this issue was the score key was composed by member and score,
-    // so the last one can't overwrite the previous when the score was different.
-    // A simple workaround was add those members with reversed order and skip the member if has added.
-    if (added_member_keys.find(member_key) != added_member_keys.end()) {
+  std::unordered_set<std::string_view> added_member_keys;
```
Comment (mapleFU) [inline src/types/redis_zset.cc:55]: So previously, `added_member_keys` is a "decoded" key, now, it becomes a "user-key"?

**Review by mapleFU — APPROVED** [review]
Thanks!

**Review by torwig — APPROVED** [review]

**Review by PragmaTwice — APPROVED** [review]

File: src/types/redis_zset.cc (hunk 8 above)
Comment (ChrisZMF) [reply src/types/redis_zset.cc:55]: Previously, the repeated members are filtered by encoded member_key, but using the original member_key can achieve the same effect.

**Comment by ChrisZMF** [comment]
Thanks @mapleFU @PragmaTwice
