### PR TITLE
Use a consistent way to get the current time

### LINKED ISSUE #983: Flaky test on expire precision
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-kvrocks/issues) and found no similar issues.

### Version

https://github.com/apache/incubator-kvrocks/pull/981/commits/461d0e8cc95cf959df50db2d75fecffbfd919875

### Minimal reproduce step

Flaky test on CI env.

### What did you expect to see?

Tests passed.

### What did you see instead?

```
--- FAIL: TestString (12.24s)
    --- FAIL: TestString/GETEX_EXAT_option (0.00s)
        assertions.go:36: 
            	Error Trace:	/home/runner/work/incubator-kvrocks/incubator-kvrocks/tests/gocase/unit/type/strings/assertions.go:36
            	            				/home/runner/work/incubator-kvrocks/incubator-kvrocks/tests/gocase/unit/type/strings/strings_test.go:155
            	Error:      	"11s" is not less than or equal to "10s"
            	Test:       	TestString/GETEX_EXAT_option
    --- FAIL: TestString/GETEX_PXAT_option (0.00s)
        assertions.go:36: 
            	Error Trace:	/home/runner/work/incubator-kvrocks/incubator-kvrocks/tests/gocase/unit/type/strings/assertions.go:36
            	            				/home/runner/work/incubator-kvrocks/incubator-kvrocks/tests/gocase/unit/type/strings/strings_test.go:162
            	Error:      	"11s" is not less than or equal to "10s"
            	Test:       	TestString/GETEX_PXAT_option
```

### Anything Else?

cc @git-hulk please take a look.

### Are you willing to submit a PR?

- [ ] I'm willing to submit a PR!

### PR DESCRIPTION
**Pull request by git-hulk**
As mentioned in https://github.com/apache/incubator-kvrocks/issues/983#issuecomment-1288931255, @mapleFU also figured out that Kvrocks use three ways to get the current time and confused developers, so we fixed it here by using a consistent way. 

This also may close #983, since I suspect the root cause is the different behavior of getting current time, so using the new way `clock_gettime` to keep consistent with Go will never be got any random failure in the expiry test cases.

### CODE REVIEW

**Comment by mapleFU** [comment]
Hi, `clock_gettime` is a posix api. maybe `std::steady_clock` is better here.

File: src/common/util.h [hunk 1]
```diff
@@ -68,6 +68,7 @@ std::vector<std::string> TokenizeRedisProtocol(const std::string &value);
 
 void ThreadSetName(const char *name);
 int aeWait(int fd, int mask, uint64_t milliseconds);
+int64_t GetTimeStamp();
 uint64_t GetTimeStampMS();
 uint64_t GetTimeStampUS();
```
Comment (PragmaTwice) [inline src/common/util.h]:
```suggestion
template <typename Duration = std::chrono::seconds>
auto GetTimeStamp() -> typename Duration::rep {
  return std::chrono::duration_cast<Duration>(std::chrono::system_clock::now().time_since_epoch()).count();
}
uint64_t GetTimeStampMS() { return GetTimeStamp<std::chrono::milliseconds>(); }
uint64_t GetTimeStampUS() { return GetTimeStamp<std::chrono::microseconds>(); }
```

Comment (PragmaTwice) [reply src/common/util.h]: We can get second/millisecond/microsecond directly without manual division.

File: src/common/util.h [hunk 2]
```diff
@@ -68,7 +68,11 @@ std::vector<std::string> TokenizeRedisProtocol(const std::string &value);
 
 void ThreadSetName(const char *name);
 int aeWait(int fd, int mask, uint64_t milliseconds);
-uint64_t GetTimeStampMS();
-uint64_t GetTimeStampUS();
+template <typename Duration = std::chrono::seconds>
+auto GetTimeStamp() -> typename Duration::rep {
```
Comment (PragmaTwice) [inline src/common/util.h]:
```suggestion
auto GetTimeStamp() -> Duration::rep {
```

Comment (PragmaTwice) [reply src/common/util.h]: Sorry, a typo :rofl:

**Comment by git-hulk** [comment]
> Hi, `clock_gettime` is a posix api. maybe `std::steady_clock` is better here.

@mapleFU Yes, we are using C++ `std::chrono::system_clock` API instead of `clock_gettime` directly, can see `Util::GetTimeStamp*`.

File: src/common/util.h (hunk 2 above)
Comment (git-hulk) [reply src/common/util.h]: aha, never mind, just append a new commit.

**Comment by PragmaTwice** [comment]
> > Hi, `clock_gettime` is a posix api. maybe `std::steady_clock` is better here.
> 
> @mapleFU Yes, we are using C++ `std::chrono::system_clock` API instead of `clock_gettime` directly, can see `Util::GetTimeStamp*`.

Maybe it is [steady_clock](https://en.cppreference.com/w/cpp/chrono/steady_clock), which is a monotonic clock rather than [system_clock](https://en.cppreference.com/w/cpp/chrono/system_clock) (a system-wide real time wall clock) in c++11 and later.

File: src/common/util.h (hunk 2 above)
Comment (PragmaTwice) [reply src/common/util.h]: Maybe we need also remove these old definitions in `util.cc`. @git-hulk

**Comment by PragmaTwice** [comment]
@mapleFU But I have a question. I notice that unlike `system_clock`, standard of `steady_clock` does not specify that it measures Unix Time.

File: src/common/util.h [hunk 3]
```diff
@@ -68,7 +68,11 @@ std::vector<std::string> TokenizeRedisProtocol(const std::string &value);
 
 void ThreadSetName(const char *name);
 int aeWait(int fd, int mask, uint64_t milliseconds);
-uint64_t GetTimeStampMS();
-uint64_t GetTimeStampUS();
+template <typename Duration = std::chrono::seconds>
+auto GetTimeStamp() -> Duration::rep {
```
Comment (PragmaTwice) [inline src/common/util.h]:
```suggestion
auto GetTimeStamp() {
```
So sorry, the `typename` is needed. But I now just want to remove the type.

File: src/common/util.cc [hunk 4]
```diff
@@ -673,6 +673,8 @@ int aeWait(int fd, int mask, uint64_t timeout) {
   }
 }
 
+int64_t GetTimeStamp() { return static_cast<int64_t>(GetTimeStampMS() / 1000); }
```
Comment (tisonkun) [inline src/common/util.cc]: Add a comment that the return value is in seconds? Also, why cannot we ass this method as `GetTimeStampSeconds` in the `.h` file? And thus `GetTimeStampMillis`/`GetTimeStampMicros`. At least I guess the common default of timestamp is in milliseconds.

Comment (PragmaTwice) [reply src/common/util.cc]: We need to remove this function definition. It is already defined in `.h`.

File: src/common/util.h [hunk 5]
```diff
@@ -68,7 +68,11 @@ std::vector<std::string> TokenizeRedisProtocol(const std::string &value);
...
 void ThreadSetName(const char *name);
 int aeWait(int fd, int mask, uint64_t milliseconds);
-uint64_t GetTimeStampMS();
-uint64_t GetTimeStampUS();
+template <typename Duration = std::chrono::seconds>
+auto GetTimeStamp() {
+  return std::chrono::duration_cast<Duration>(std::chrono::system_clock::now().time_since_epoch()).count();
+}
+uint64_t GetTimeStampMS() { return GetTimeStamp<std::chrono::milliseconds>(); }
+uint64_t GetTimeStampUS() { return GetTimeStamp<std::chrono::microseconds>(); }
```
Comment (PragmaTwice) [inline src/common/util.h]:
```suggestion
inline uint64_t GetTimeStampMS() { return GetTimeStamp<std::chrono::milliseconds>(); }
inline uint64_t GetTimeStampUS() { return GetTimeStamp<std::chrono::microseconds>(); }
```

**Comment by mapleFU** [comment]
> But I have a question. I notice that unlike `system_clock`, standard of `steady_clock` does not specify that it measures Unix Time.

`time_point` can call `time_since_epoch`. Like the case here: https://github.com/facebook/rocksdb/blob/main/env/env_posix.cc#L142-L162

File: src/common/util.h (hunk 3 above)
Comment (git-hulk) [reply src/common/util.h]: Looks we can't put the function body in header file, it will cause duplicate symbol conflicts.

**Comment by PragmaTwice** [comment]
> > But I have a question. I notice that unlike `system_clock`, standard of `steady_clock` does not specify that it measures Unix Time.
> 
> `time_point` can call `time_since_epoch`. Like the case here: https://github.com/facebook/rocksdb/blob/main/env/env_posix.cc#L142-L162

`time_since_epoch` DOES NOT imply the Unix epoch.

File: src/common/util.cc (hunk 4 above)
Comment (git-hulk) [reply src/common/util.cc]: re @tisonkun, Yes, I think the timestamp is usually referred as the timestamp second.

**Comment by mapleFU** [comment]
> `time_since_epoch` DOES NOT imply the Unix epoch.

You're right. C++20 says that `time_since_epoch` should follow the system epoch, and C++17's `time_since_epoch` is de facto unix epoch. But standard doesn't force it. I think just follow rocksdb's code is ok. Do you have any ideas? @PragmaTwice

**Comment by PragmaTwice** [comment]
> > `time_since_epoch` DOES NOT imply the Unix epoch.
> 
> You're right. C++20 says that `time_since_epoch` should follow the system epoch, and C++17's `time_since_epoch` is de facto unix epoch. But standard doesn't force it. I think just follow rocksdb's code is ok. Do you have any ideas? @PragmaTwice

I notice that although no guarantee, most of implementations do use Unix time, so I think it is fine.

**Review by tisonkun — APPROVED** [review]

**Comment by PragmaTwice** [comment]
But another problem is that, even in c++20, the `system_clock` is guaranteed to use Unix Time, but it seems `steady_clock` does not have this guarantee.

**Review by PragmaTwice — APPROVED** [review]

**Comment by PragmaTwice** [comment]
Thanks all. Merging...
