### PR TITLE
Fix the inconsistent response behavior with Redis in memory usage  command

### LINKED ISSUE #1538: Running the `memory usage` command against a non-existent key resulted in an error
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/kvrocks/issues) and found no similar issues.

### Version

kvrocks 2.4.0

### Minimal reproduce step

```sh
memory usage key-not-exist
```

### What did you expect to see?

return `nil`

### What did you see instead?

```sh
(error) ERROR NotFound: Not found : key-not-exist
```

### Anything Else?

This is not compatible with redis, which return `nil` when the key does not exist, and will cause [asynqmon](https://github.com/hibiken/asynqmon) failed sometimes when using `memory usage` command.

### Are you willing to submit a PR?

- [ ] I'm willing to submit a PR!

### PR DESCRIPTION
**Pull request by git-hulk**
This fixes #1538

### CODE REVIEW

**Comment by mapleFU** [comment]
Seems that when key not found or expired, `Database::Type(const Slice &user_key, RedisType *type)` would return `kRedisNone`, and get `Disk::GetKeySize` with `kRedisNone` would raise not found rather than return `Nil`?

(It's interesting that "type" fixed it in another patch: https://github.com/apache/kvrocks/commit/3cea04515a3d9cf15cd9a968b38cd919f3c5ef8e )

**Review by mapleFU — APPROVED** [review]
The patch LGTM. I also checked all place using `Database::Type`, they're:

1. `Set::Move`
2. `List::RPopLPush`
3. `CommandDisk::Execute`
4. `CommandType::Execute`

Seems they have all been handled after this patch

**Review by PragmaTwice — DISMISSED** [review]

File: src/commands/cmd_server.cc [hunk 1]
```diff
@@ -289,6 +289,13 @@ class CommandDisk : public Commander {
...
+    // Redis returns the Nil string when the key does not exist,
+    // so we need to check the type here to check if the key is not exists.
+    if (type == RedisType::kRedisNone) {
+      *output = redis::NilString();
+      return Status::OK();
+    }
+
     uint64_t result = 0;
     s = disk_db.GetKeySize(args_[2], type, &result);
     if (!s.ok()) return {Status::RedisExecErr, s.ToString()};
```
Comment (torwig) [inline src/commands/cmd_server.cc]: I would recommend checking the returned status after the call to the `GetKeySize` as well (or only after this call) because, in theory, something can happen between the call to `Type` and `GetKeySize` (key deletion, expiration, etc.).

Comment (torwig) [reply src/commands/cmd_server.cc]: @git-hulk Thank you for quick fix :+1:

Comment (mapleFU) [reply src/commands/cmd_server.cc]: Sounds ok, RocksDB Snapshot might helps for this, but I after `GetKeySize` would be more easily

Comment (git-hulk) [reply src/commands/cmd_server.cc]: > I would recommend checking the returned status after the call to the `GetKeySize` as well (or only after this call) because, in theory, something can happen between the call to `Type` and `GetKeySize` (key deletion, expiration, etc.).

good suggestion.

**Review by mapleFU — APPROVED** [review]

**Review by enjoy-binbin — APPROVED** [review]

**Review by PragmaTwice — APPROVED** [review]

**Review by tisonkun — APPROVED** [review]

**Review by torwig — APPROVED** [review]

**Comment by tisonkun** [comment]
Merging...

Thanks for the quick fix :D
