### PR TITLE
fix(hscan): HSCAN support NOVALUES

### LINKED ISSUE #3103: Support for NOVALUES for HSCAN
### Search before asking

- [x] I had searched in the [issues](https://github.com/apache/kvrocks/issues) and found no similar issues.

### Motivation

When the NOVALUES flag (since Redis 7.4) is used, only the field names are returned. https://redis.io/docs/latest/commands/hscan/

Is there any plan to match this redis feature?

### Solution

_No response_

### Are you willing to submit a PR?

- [ ] I'm willing to submit a PR!

### PR DESCRIPTION
**Pull request by LiuQhahah**
It closes https://github.com/apache/kvrocks/issues/3103

```
127.0.0.1:6666> HMSET langhash lang1 "PHP" lang2 "JavaScript" lang3 "Python" lang4 "GoLanguage"
OK
127.0.0.1:6666> HSCAN langhash 0 
1) "0"
2) 1) "lang1"
   2) "PHP"
   3) "lang2"
   4) "JavaScript"
   5) "lang3"
   6) "Python"
   7) "lang4"
   8) "GoLanguage"
127.0.0.1:6666> HSCAN langhash 0  NOVALUES
1) "0"
2) 1) "lang1"
   2) "lang2"
   3) "lang3"
   4) "lang4"

```

@git-hulk Please review the code, thank you.

### CODE REVIEW

File: src/storage/redis_db.cc [hunk 1]
```diff
@@ -575,8 +576,10 @@ rocksdb::Status SubKeyScanner::Scan(engine::Context &ctx, RedisType type, const
     }
     InternalKey ikey(iter->key(), storage_->IsSlotIdEncoded());
     keys->emplace_back(ikey.GetSubKey().ToString());
-    if (values != nullptr) {
-      values->emplace_back(iter->value().ToString());
+    if (!no_values_) {
+      if (values != nullptr) {
+        values->emplace_back(iter->value().ToString());
+      }
     }
```
Comment (PragmaTwice) [inline src/storage/redis_db.cc]: `no_values_` seems useless. We can just pass a `nullptr` as `values` to indicate that we don't want values.

**Review by PragmaTwice — COMMENTED** [review]
See comments.

File: src/storage/redis_db.cc (hunk 1 above)
Comment (git-hulk) [reply src/storage/redis_db.cc]: Good suggestion.

**Comment by git-hulk** [comment]
@LiuQhahah Could you please also add the Go tests to ensure it works as expected.

**Comment by LiuQhahah** [comment]
> @LiuQhahah Could you please also add the Go tests to ensure it works as expected.

got it , i will add go test

**Review by git-hulk — APPROVED** [review]

**Comment by PragmaTwice** [comment]
BTW we should also support NOVALUES for zset and set, since now `*SCAN` accepts the parameter `NOVALUES`.
