### PR TITLE
Allow default username and fix case sensitive check in HELLO

### LINKED ISSUE #1403: Syntax of HELLO is different from Redis
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-kvrocks/issues) and found no similar issues.

### Version

2.3.0

### Minimal reproduce step

1. Set `requirepass mypass`
2. Send command: `HELLO 2 AUTH default mypass` after connected.

### What did you expect to see?

mypass should be accepted.

### What did you see instead?

`invalid password` error.

### Anything Else?

Hi, 

According to https://redis.io/commands/hello, the syntax of `HELLO` should be 
```
HELLO [protover [AUTH username password] [SETNAME clientname]]
```
and the default username should be `default`.

However, kvrocks' syntax seems to lack the username part:
https://github.com/apache/incubator-kvrocks/blob/6889b5916ab560ecd5eed79bb9786e36342f0e17/src/commands/cmd_server.cc#L660

Not sure if this is intended? But I think it will be great if matching redis' syntax.

### Are you willing to submit a PR?

- [x] I'm willing to submit a PR!

### PR DESCRIPTION
**Pull request by rueian**
Hi, following the conversation https://github.com/apache/incubator-kvrocks/issues/1403

* This closes #1403.

This PR makes the `HELLO` command:
1.  accept the `default` username as well.
2. use case insensitive check on the `AUTH` and `SETNAME`. Clients may send these options in lower or upper cases. For example, go-redis sends them in lower cases.

I think this PR won't break any existing Kvrocks clients but will remove barriers for other clients to adapt Kvrocks by aligning HELLO syntax with Redis.

Please let me know if these changes make sense.

### CODE REVIEW

**Review by PragmaTwice — DISMISSED** [review]
LGTM, thanks for your contribution!

**Review by torwig — DISMISSED** [review]

File: src/commands/cmd_server.cc [hunk 1]
```diff
@@ -657,7 +657,7 @@ class CommandTime : public Commander {
   }
 };
 
-/* HELLO [<protocol-version> [AUTH <password>] [SETNAME <name>] ] */
+/* HELLO [<protocol-version> [AUTH [<password>|<username> <password>]] [SETNAME <name>] ] */
```
Comment (tisonkun) [inline src/commands/cmd_server.cc]: Perhaps add a comment that `username` should be always `default` otherwise it fails. And such syntax is for compatible only.

**Review by tisonkun — DISMISSED** [review]
Thank you! One comment to convey the background discussion into code.

File: src/commands/cmd_server.cc (hunk 1 above)
Comment (rueian) [reply src/commands/cmd_server.cc]: Sure!

**Review by git-hulk — APPROVED** [review]
LGTM

**Review by tisonkun — APPROVED** [review]

**Comment by PragmaTwice** [comment]
Merging. Thanks for your contribution.

**Comment by mapleFU** [comment]
Seems that only "hello" support authenticate with user, should  https://redis.io/commands/auth/ support that?

**Comment by PragmaTwice** [comment]
> Seems that only "hello" support authenticate with user, should https://redis.io/commands/auth/ support that?

I think it is not urgent as HELLO, since HELLO in redis just does not allow the username to be omitted, but `AUTH password` is valid in redis.

**Comment by mapleFU** [comment]
Ok, reasonable. LGTM!
