### PR TITLE
PSYNC based on Unique Replication Sequence ID

### LINKED ISSUE #462: [BUG] Incorrect data after SLAVEOF
**Describe the bug**
After SLAVEOF, 2 instances can contain different values for a given key.

**To Reproduce**
Start 2 kvrocks instances and execute the following commands in the respective instances.

- **SERVER2**: SLAVEOF SERVER1
- **SERVER2**: SLAVEOF NO ONE
- **SERVER2**: SET test 222
- **SERVER1**: SET test 111
- **SERVER2**: SLAVEOF SERVER1
- **SERVER2**: GET test
  - Returns "222". However, it should return "111".

If a new SET command is used on SERVER1, SERVER2 immediately picks up the latest value.
This issue doesn't occur if, on the "test" key, SERVER1 executed multiple SET commands while SERVER2 was not a slave.

**Expected behavior**
After SLAVEOF command, SERVER2 should always contain identical data to SERVER1.

### PR DESCRIPTION
**Pull request by ShooterIT**
### Background
Currently, master only checks sequence number when replica asks for PSYNC, that is not enough since they may have different replication history even the replica asking sequence is in the range of the master current WAL.

Bug report in https://github.com/KvrocksLabs/kvrocks/issues/462

PS: Master check also DB name before checking sequence number, but it is also not enough since it is setting in conf, and don't change when role is changed.
 
### Solution

We design 'PSYNC based on Unique Replication Sequence ID', we add unique replication id for every write batch (the operation of each command on the storage engine), so the combination of replication id and sequence is unique for write batch. The master can identify whether the replica has the same replication history by checking replication id and sequence. 
Like Redis, replicas can partially resynchronize with new master if old master is failed and new selected master has largest offset, and replicas can also partially resynchronize with master after restarting if the replicas' conf file has the its origin master.

Unique replication id will be changed when replicas become master.

By default, it is not enabled since this stricter check may easily lead to full synchronization. You should enable it if you want to data correctness, maybe we enable it by default in kvrocks 3.0.

### CODE REVIEW

File: src/server.cc [hunk 1]
```diff
@@ -1422,3 +1412,24 @@ void Server::AdjustOpenFilesLimit() {
...
+Status ServerLogData::Decode(const rocksdb::Slice &blob) {
+  if (blob.size() == 0) {
+    return Status(Status::NotOK);
+  }
+
+  const char *header = blob.data();
+  if (*header == kReplIdTag) {
+    type_ = kReplIdLog;
+  }
+  content_ = std::string(blob.data()+2, blob.size()-2);
```
Comment (git-hulk) [inline src/server.cc]: should check the blob data length before using it?

File: src/replication.cc [hunk 2]
```diff
@@ -466,10 +468,39 @@ ReplicationThread::CBState ReplicationThread::replConfReadCB(
...
+  // Get replication id
+  std::string replid_in_wal = self->storage_->GetReplIdFromWalBySeq(cur_seq);
+  // Set if valid replication id
+  if (replid_in_wal.length() == kReplIdLength) {
+    replid = replid_in_wal;
+  } else {
+    // Maybe there is no WAL, we can get replication id from db since master
+    // always write replication id into db before any operation when starting
+    // new "replication history".
+    std::string replid_in_db = self->storage_->GetReplIdFromDbEngine();
```
Comment (git-hulk) [inline src/replication.cc:484]: The slave also can't get replid from DB as well if there's no WAL(empty slave db), so propagating the replication id would never be used?

File: src/main.cc [hunk 3]
```diff
@@ -324,6 +324,10 @@ int main(int argc, char* argv[]) {
       srv->Stop();
     }
   };
+
+  // Generate new replication id if not a replica
+  if (!srv->IsSlave()) storage.ShiftReplId();
+
```
Comment (git-hulk) [inline src/main.cc]: Master was added after starting the server, so it should always be true here.

Comment (ShooterIT) [reply src/main.cc]: you are right, i missed this, we set master info in `Server::Start ` instead of loading config file.

File: src/replication.cc (hunk 2 above)
Comment (ShooterIT) [reply src/replication.cc:484]: Maybe empty WAL, as we know, wal may be not persistent in disk after restarting server.

File: src/server.cc (hunk 1 above)
Comment (ShooterIT) [reply src/server.cc]: ok, it is more strict

File: src/replication.cc (hunk 2 above)
Comment (ShooterIT) [reply src/replication.cc:484]: And one checkpoint from master, WAL may be flushed when creating checkpoint

Comment (git-hulk) [reply src/replication.cc:484]: Cool, got it.

Comment (git-hulk) [reply src/replication.cc:484]: Cool, got it.

**Comment by git-hulk** [comment]
@ShooterIT Need to add the License Header for new files

**Review by git-hulk — DISMISSED** [review]
LGTM

**Review by git-hulk — APPROVED** [review]
