### PR TITLE
Fix use after free  and some memory leaks which reported by ASan

### LINKED ISSUE #713: BUG: Use after free in `CommandFetchFile` reported by ASan
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-kvrocks/issues) and found no similar issues.

### Version

unstable

### Minimal reproduce step

```
./build.sh build -DENABLE_ASAN=ON
cd tests/tcl
./runtest --dont-clean
grep Sanitizer tests/tmp -r
```

### What did you expect to see?

No ASAN reports

### What did you see instead?

For more detail can see: https://github.com/apache/incubator-kvrocks/runs/7174515538?check_suite_focus=true

```
\o/ All tests passed without errors!
tests/tmp/server.21550.23/stderr:==30422==ERROR: AddressSanitizer: heap-use-after-free on address 0x606000003500 at pc 0x7f97aad45733 bp 0x7f97961e5840 sp 0x7f97961e4fe8
tests/tmp/server.21550.23/stderr:SUMMARY: AddressSanitizer: heap-use-after-free (/usr/lib/x86_64-linux-gnu/libasan.so.4+0x79732) 
\ndetail reports:\n
E20220704 05:25:13.181370 29782 replication.cc:162] [replication] connection error/eof, reconnect the master
E20220704 05:25:14.181675 29782 replication.cc:248] [replication] Failed to connect the master, err: Connection refused
E20220704 05:25:59.096598  1453 replication.cc:162] [replication] connection error/eof, reconnect the master
E20220704 05:26:01.526546  1765 replication.cc:162] [replication] connection error/eof, reconnect the master
E20220704 05:25:40.944598 31108 slot_migrate.cc:476] [migrate] Failed to read response, Err: Connection reset by peer
E20220704 05:25:40.944772 31108 slot_migrate.cc:792] [migrate] Wrong response
E20220704 05:25:40.944813 31108 slot_migrate.cc:588] [migrate] Failed to migrate complex key: 0QG
E20220704 05:25:40.944831 31108 slot_migrate.cc:310] [migrate] Failed to migrate key: 0QG
E20220704 05:25:40.944859 31108 slot_migrate.cc:181] [migrate] Failed to send snapshot
E20220704 05:25:40.944891 31108 slot_migrate.cc:420] [migrate] Failed to send import command to destination, slot: 8, error: Broken pipe
E20220704 05:24:59.634393 26964 replication.cc:77] Ping slave[127.0.0.1:41322] err: Broken pipe, would stop the thread
WARNING: Logging before InitGoogleLogging() is written to STDERR
I20220704 05:25:50.447059 21587 event_listener.cc:132] [event_listener/table_file_deleted] db: ./tests/tmp/server.21553.1/db, sst file: ./tests/tmp/server.21553.1/db/000017.sst, status: OK
=================================================================
==30422==ERROR: AddressSanitizer: heap-use-after-free on address 0x606000003500 at pc 0x7f97aad45733 bp 0x7f97961e5840 sp 0x7f97961e4fe8
READ of size 38 at 0x606000003500 thread T103 (feed-repl-file)
    #0 0x7f97aad45732  (/usr/lib/x86_64-linux-gnu/libasan.so.4+0x79732)
    #1 0x5560df5a4ece in void std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::_M_construct<char*>(char*, char*, std::forward_iterator_tag) (/home/runner/work/incubator-kvrocks/incubator-kvrocks/tests/tcl/redis-server+0xaabece)
    #2 0x5560df5a4f0e in std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::basic_string(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) (/home/runner/work/incubator-kvrocks/incubator-kvrocks/tests/tcl/redis-server+0xaabf0e)
    #3 0x5560df048ff1 in std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > std::operator+<char, std::char_traits<char>, std::allocator<char> >(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, char const*) /usr/include/c++/7/bits/basic_string.h:5928
    #4 0x5560df012557 in Engine::Storage::ReplDataManager::OpenDataFile(Engine::Storage*, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, unsigned long*) /home/runner/work/incubator-kvrocks/incubator-kvrocks/src/storage.cc:836
    #5 0x5560dedaf46d in Redis::CommandFetchFile::Execute(Server*, Redis::Connection*, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >*)::{lambda()#1}::operator()() const /home/runner/work/incubator-kvrocks/incubator-kvrocks/src/redis_cmd.cc:4395
    #6 0x5560dedb0a3c in void std::__invoke_impl<void, Redis::CommandFetchFile::Execute(Server*, Redis::Connection*, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >*)::{lambda()#1}>(std::__invoke_other, Redis::CommandFetchFile::Execute(Server*, Redis::Connection*, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >*)::{lambda()#1}&&) /usr/include/c++/7/bits/invoke.h:60
    #7 0x5560dedb0a3c in std::__invoke_result<Redis::CommandFetchFile::Execute(Server*, Redis::Connection*, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >*)::{lambda()#1}>::type std::__invoke<Redis::CommandFetchFile::Execute(Server*, Redis::Connection*, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >*)::{lambda()#1}>(std::__invoke_result&&, (Redis::CommandFetchFile::Execute(Server*, Redis::Connection*, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >*)::{lambda()#1}&&)...) /usr/include/c++/7/bits/invoke.h:95
    #8 0x5560dedb0a3c in decltype (__invoke((_S_declval<0ul>)())) std::thread::_Invoker<std::tuple<Redis::CommandFetchFile::Execute(Server*, Redis::Connection*, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >*)::{lambda()#1}> >::_M_invoke<0ul>(std::_Index_tuple<0ul>) /usr/include/c++/7/thread:234
    #9 0x5560dedb0a3c in std::thread::_Invoker<std::tuple<Redis::CommandFetchFile::Execute(Server*, Redis::Connection*, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >*)::{lambda()#1}> >::operator()() /usr/include/c++/7/thread:243
    #10 0x5560dedb0a3c in std::thread::_State_impl<std::thread::_Invoker<std::tuple<Redis::CommandFetchFile::Execute(Server*, Redis::Connection*, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >*)::{lambda()#1}> > >::_M_run() /usr/include/c++/7/thread:186
    #11 0x5560df5a07de in execute_native_thread_routine (/home/runner/work/incubator-kvrocks/incubator-kvrocks/tests/tcl/redis-server+0xaa77de)
    #12 0x7f97aaab46da in start_thread (/lib/x86_64-linux-gnu/libpthread.so.0+0x76da)
    #13 0x7f97aa43f61e in __clone (/lib/x86_64-linux-gnu/libc.so.6+0x12161e)
0x606000003500 is located 0 bytes inside of 55-byte region [0x606000003500,0x606000003537)
freed by thread T0 here:
    #0 0x7f97aadad2c0 in operator delete(void*) (/usr/lib/x86_64-linux-gnu/libasan.so.4+0xe12c0)
    #1 0x5560debe9a12 in __gnu_cxx::new_allocator<char>::deallocate(char*, unsigned long) /usr/include/c++/7/ext/new_allocator.h:125
    #2 0x5560debe9a12 in std::allocator_traits<std::allocator<char> >::deallocate(std::allocator<char>&, char*, unsigned long) /usr/include/c++/7/bits/alloc_traits.h:462
    #3 0x5560debe9a12 in std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::_M_destroy(unsigned long) /usr/include/c++/7/bits/basic_string.h:226
    #4 0x5560debe9a12 in std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::_M_dispose() /usr/include/c++/7/bits/basic_string.h:221
    #5 0x5560debe9a12 in std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::~basic_string() /usr/include/c++/7/bits/basic_string.h:647
    #6 0x5560debe9a12 in Config::~Config() /home/runner/work/incubator-kvrocks/incubator-kvrocks/src/config.h:66
    #7 0x5560deb9b44c in main /home/runner/work/incubator-kvrocks/incubator-kvrocks/src/main.cc:316
    #8 0x7f97aa33fc86 in __libc_start_main (/lib/x86_64-linux-gnu/libc.so.6+0x21c86)
previously allocated by thread T0 here:
    #0 0x7f97aadac448 in operator new(unsigned long) (/usr/lib/x86_64-linux-gnu/libasan.so.4+0xe0448)
    #1 0x5560df5a28f9 in std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::_M_mutate(unsigned long, unsigned long, char const*, unsigned long) (/home/runner/work/incubator-kvrocks/incubator-kvrocks/tests/tcl/redis-server+0xaa98f9)
Thread T103 (feed-repl-file) created by T97 (worker) here:
    #0 0x7f97aad03d2f in __interceptor_pthread_create (/usr/lib/x86_64-linux-gnu/libasan.so.4+0x37d2f)
    #1 0x5560df5a0ac4 in std::thread::_M_start_thread(std::unique_ptr<std::thread::_State, std::default_delete<std::thread::_State> >, void (*)()) (/home/runner/work/incubator-kvrocks/incubator-kvrocks/tests/tcl/redis-server+0xaa7ac4)
    #2 0x5560dee1f8a4 in Redis::Connection::ExecuteCommands(std::vector<std::vector<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > >, std::allocator<std::vector<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > > > > const&) /home/runner/work/incubator-kvrocks/incubator-kvrocks/src/redis_connection.cc:422
    #3 0x5560dee233f5 in Redis::Connection::OnRead(bufferevent*, void*) /home/runner/work/incubator-kvrocks/incubator-kvrocks/src/redis_connection.cc:89
    #4 0x5560df4df61d in bufferevent_run_deferred_callbacks_unlocked /home/runner/work/incubator-kvrocks/incubator-kvrocks/build/_deps/libevent-src/bufferevent.c:208
Thread T97 (worker) created by T0 here:
    #0 0x7f97aad03d2f in __interceptor_pthread_create (/usr/lib/x86_64-linux-gnu/libasan.so.4+0x37d2f)
    #1 0x5560df5a0ac4 in std::thread::_M_start_thread(std::unique_ptr<std::thread::_State, std::default_delete<std::thread::_State> >, void (*)()) (/home/runner/work/incubator-kvrocks/incubator-kvrocks/tests/tcl/redis-server+0xaa7ac4)
    #2 0x5560def939bb in Server::Start() /home/runner/work/incubator-kvrocks/incubator-kvrocks/src/server.cc:121
    #3 0x5560deb9b2ee in main /home/runner/work/incubator-kvrocks/incubator-kvrocks/src/main.cc:354
    #4 0x7f97aa33fc86 in __libc_start_main (/lib/x86_64-linux-gnu/libc.so.6+0x21c86)
SUMMARY: AddressSanitizer: heap-use-after-free (/usr/lib/x86_64-linux-gnu/libasan.so.4+0x79732) 
Shadow bytes around the buggy address:
  0x0c0c7fff8650: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
  0x0c0c7fff8660: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
  0x0c0c7fff8670: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
  0x0c0c7fff8680: fa fa fa fa fa fa fa fa fd fd fd fd fd fd fd fa
  0x0c0c7fff8690: fa fa fa fa fd fd fd fd fd fd fd fa fa fa fa fa
=>0x0c0c7fff86a0:[fd]fd fd fd fd fd fd fa fa fa fa fa fd fd fd fd
  0x0c0c7fff86b0: fd fd fd fa fa fa fa fa fd fd fd fd fd fd fd fa
  0x0c0c7fff86c0: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
  0x0c0c7fff86d0: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
  0x0c0c7fff86e0: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
  0x0c0c7fff86f0: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
Shadow byte legend (one shadow byte represents 8 application bytes):
  Addressable:           00
  Partially addressable: 01 02 03 04 05 06 07 
  Heap left redzone:       fa
  Freed heap region:       fd
  Stack left redzone:      f1
  Stack mid redzone:       f2
  Stack right redzone:     f3
  Stack after return:      f5
  Stack use after scope:   f8
  Global redzone:          f9
  Global init order:       f6
  Poisoned by user:        f7
  Container overflow:      fc
  Array cookie:            ac
  Intra object redzone:    bb
  ASan internal:           fe
  Left alloca redzone:     ca
  Right alloca redzone:    cb
==30422==ABORTING
E20220704 05:25:13.181382 29785 replication.cc:162] [replication] connection error/eof, reconnect the master
E20220704 05:24:53.779562 25091 replication.cc:128] Write error while sending batch to slave: Broken pipe. batches: 0x2433380D0A02000000000000000100000003013105010D0B5F5F6E616D65737061636561060100000000620D0A
E20220704 05:24:53.780030 25099 replication.cc:128] Write error while sending batch to slave: Broken pipe. batches: 0x2433380D0A02000000000000000100000003013105010D0B5F5F6E616D65737061636561060100000000620D0A
E20220704 05:24:53.780268 25131 replication.cc:128] Write error while sending batch to slave: Broken pipe. batches: 0x2433380D0A02000000000000000100000003013105010D0B5F5F6E616D65737061636561060100000000620D0A
E20220704 05:24:56.222230 25861 slot_migrate.cc:241] [migrate] Failed to connect destination server
E20220704 05:24:56.222508 25861 slot_migrate.cc:170] [migrate] Failed to start migrating
E20220704 05:24:49.706113 24751 replication.cc:162] [replication] connection error/eof, reconnect the master
E20220704 05:25:52.255283 32602 slot_migrate.cc:288] [migrate] Stop migrating snapshot due to the thread stoped
E20220704 05:25:52.255439 32602 slot_migrate.cc:181] [migrate] Failed to send snapshot
E20220704 05:25:04.225044 26691 replication.cc:162] [replication] connection error/eof, reconnect the master
E20220704 05:25:56.253038   591 slot_migrate.cc:494] [migrate] Got invalid response: -NOAUTH Authentication required., line length: 32
E20220704 05:25:56.253249   591 slot_migrate.cc:256] [migrate] Failed to notify the destination to prepare to import data
E20220704 05:25:56.253271   591 slot_migrate.cc:170] [migrate] Failed to start migrating
E20220704 05:25:56.253386   591 slot_migrate.cc:494] [migrate] Got invalid response: -NOAUTH Authentication required., line length: 32
E20220704 05:25:56.254267   591 slot_migrate.cc:494] [migrate] Got invalid response: -ERR invalid password, line length: 21
E20220704 05:25:56.254307   591 slot_migrate.cc:406] [migrate] Failed to auth destination server with 'pass', stop migrating slot 22
E20220704 05:25:56.254325   591 slot_migrate.cc:170] [migrate] Failed to start migrating
E20220704 05:25:56.254431   591 slot_migrate.cc:494] [migrate] Got invalid response: -NOAUTH Authentication required., line length: 32
E20220704 05:25:10.059321 29194 replication.cc:162] [replication] connection error/eof, reconnect the master
E20220704 05:25:06.633349 28188 replication.cc:162] [replication] connection error/eof, reconnect the master
E20220704 05:24:59.645223 27469 replication.cc:248] [replication] Failed to connect the master, err: Connection refused
E20220704 05:25:02.869042 27470 replication.cc:162] [replication] connection error/eof, reconnect the master
E20220704 05:24:46.901080 23284 redis_cmd.cc:1582] Failed to execute redis command: blpop, err: Invalid argument: WRONGTYPE Operation against a key holding the wrong kind of value
E20220704 05:24:48.914759 23284 redis_cmd.cc:1582] Failed to execute redis command: brpop, err: Invalid argument: WRONGTYPE Operation against a key holding the wrong kind of value
E20220704 05:25:41.277627 30700 replication.cc:698] [replication] Failed to parallel fetch files while fetch file err: read size: File exists
E20220704 05:25:51.290735 30700 replication.cc:162] [replication] connection error/eof, reconnect the master
E20220704 05:25:48.578738 31962 slot_migrate.cc:494] [migrate] Got invalid response: -MOVED 10 127.0.0.1:28122, line length: 25
E20220704 05:25:48.5[790](https://github.com/apache/incubator-kvrocks/runs/7174515538?check_suite_focus=true#step:9:791)25 31962 slot_migrate.cc:792] [migrate] Wrong response
E20220704 05:25:48.579075 31962 slot_migrate.cc:588] [migrate] Failed to migrate complex key: 7Ok
E20220704 05:25:48.5[791](https://github.com/apache/incubator-kvrocks/runs/7174515538?check_suite_focus=true#step:9:792)13 31962 slot_migrate.cc:310] [migrate] Failed to migrate key: 7Ok
E20220704 05:25:48.57[913](https://github.com/apache/incubator-kvrocks/runs/7174515538?check_suite_focus=true#step:9:914)8 31962 slot_migrate.cc:181] [migrate] Failed to send snapshot
sanitizer error was reported, exiting...
Error: Process completed with exit code 1.
```

### Anything Else?

_No response_

### Are you willing to submit a PR?

- [X] I'm willing to submit a PR!

### PR DESCRIPTION
**Pull request by git-hulk**
Fixes #713 and #699

### CODE REVIEW

**Comment by git-hulk** [comment]
Last failure was caused by the monitor command, will fix it

File: src/redis_request.h [hunk 1]
```diff
@@ -55,7 +55,7 @@ class Request {
   int64_t multi_bulk_len_ = 0;
   size_t bulk_len_ = 0;
   CommandTokens tokens_;
-  std::vector<CommandTokens> commands_;
+  std::list<CommandTokens> commands_;
```
Comment (PragmaTwice) [inline src/redis_request.h]: Is `std::deque` a good choice here?

Comment (git-hulk) [reply src/redis_request.h]: Do you mean deque will performance better than list in this case?
I used the list since what we need is the FIFO operation and list
seems better than array type container.

Comment (PragmaTwice) [reply src/redis_request.h]: Yeah, I think `std::deque` is more cache-friendly and the complexity of its `push/pop_front/back` operations is also a constant like `std::list`.

Comment (git-hulk) [reply src/redis_request.h]: After taking a look at how `std::deque` works, I think you are right.
I thought `std::deque` will cause memory realloc since my memory
tells me it's an array type container. Will update this.

File: src/redis_connection.cc [hunk 2]
```diff
@@ -426,6 +426,12 @@ void Connection::ExecuteCommands(const std::vector<Redis::CommandTokens> &to_pro
     svr_->SlowlogPushEntryIfNeeded(current_cmd_->Args(), duration);
     svr_->stats_.IncrLatency(static_cast<uint64_t>(duration), cmd_name);
     svr_->FeedMonitorConns(this, cmd_tokens);
+
+    // Break the execution loop when occurring the blocking command like BLPOP or BRPOP,
+    // it will suspend the connection and wait for the wakeup signal.
```
Comment (PragmaTwice) [inline src/redis_connection.cc:431]: Do wakeup signals here include new commands received from users?
I am unfamiliar with these code so correct me if I am wrong.

Comment (git-hulk) [reply src/redis_connection.cc:431]: No, it will remove the read callback: https://github.com/apache/incubator-kvrocks/blob/unstable/src/redis_cmd.cc#L1574, we can prevent the `current_cmd` being free in this case, even though it's a bit tricky.

Comment (PragmaTwice) [reply src/redis_connection.cc:431]: Got it. I understood the solution now.

**Review by PragmaTwice — APPROVED** [review]

File: src/redis_connection.cc (hunk 2 above)
Comment (git-hulk) [reply src/redis_connection.cc:431]: Cool, I think we should add some comments/docs for how the blocking pop works later to make it clear. 

The basic mechanism is below:

1. new connection will only enable `EV_READ`
2. remove the read callback when entering the blocking mode and add the write/timer callback 
3. wake up the connection by making the socket writable(command push was called) or timeout event was triggered, then re-enable and reset read callback again.
