### PR TITLE
fix(stream): make consumer decrement pending number when message is acknowledged.

### LINKED ISSUE #2350: [Bug] XINFO overflow when deleting pending message and consumer
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/kvrocks/issues) and found no similar issues.

### Version

version: unstable
kvrocks_version: unstable
redis_version:4.0.0
git_sha1: d2e0feb
kvrocks_git_sha1: d2e0feb
redis_mode: standalone
kvrocks_mode: standalone
os: Linux 5.14.0-162.6.1.el9_1.0.1.x86_64 x86_64
gcc_version: 11.2.1
arch_bits: 64
process_id: 1
tcp_port: 6666
uptime_in_seconds: 1444
uptime_in_days: 0

### Minimal reproduce step

Here is the step using redis-cli:

```bash
~ redis-cli -h kvrocks-server -p 6666
kvrocks-server:6666> xgroup create overflow-test info-count-test $ MKSTREAM
OK
kvrocks-server:6666> xgroup createconsumer overflow-test info-count-test consumer-1
(integer) 1
kvrocks-server:6666> xinfo groups overflow-test
1)  1) "name"
    2) "info-count-test"
    3) "consumers"
    4) (integer) 1
    5) "pending"
    6) (integer) 0
    7) "last-delivered-id"
    8) "0-0"
    9) "entries-read"
   10) (nil)
   11) "lag"
   12) (integer) 0
kvrocks-server:6666> xadd overflow-test * testing overflow
"1717248597227-0"
kvrocks-server:6666> xinfo groups overflow-test
1)  1) "name"
    2) "info-count-test"
    3) "consumers"
    4) (integer) 1
    5) "pending"
    6) (integer) 0
    7) "last-delivered-id"
    8) "0-0"
    9) "entries-read"
   10) (nil)
   11) "lag"
   12) (integer) 1
kvrocks-server:6666> xreadgroup group info-count-test consumer-1 count 1 streams overflow-test >
1) 1) "overflow-test"
   2) 1) 1) "1717248597227-0"
         2) 1) "testing"
            2) "overflow"
kvrocks-server:6666> xinfo groups overflow-test
1)  1) "name"
    2) "info-count-test"
    3) "consumers"
    4) (integer) 1
    5) "pending"
    6) (integer) 1
    7) "last-delivered-id"
    8) "1717248597227-0"
    9) "entries-read"
   10) (integer) 0
   11) "lag"
   12) (integer) 1
kvrocks-server:6666> xack overflow-test info-count-test 1717248597227-0
(integer) 1
kvrocks-server:6666> xinfo groups overflow-test
1)  1) "name"
    2) "info-count-test"
    3) "consumers"
    4) (integer) 1
    5) "pending"
    6) (integer) 0
    7) "last-delivered-id"
    8) "1717248597227-0"
    9) "entries-read"
   10) (integer) 0
   11) "lag"
   12) (integer) 1
kvrocks-server:6666> xgroup delconsumer overflow-test info-count-test consumer-1
(integer) 1
kvrocks-server:6666> xinfo groups overflow-test
Error: Bad integer value
```

The redis-cli refuses to display the response value.

So, I use telnet to run the command and got response below.

```bash
xinfo groups overflow-test
*1
*12
$4
name
$15
info-count-test
$9
consumers
:0
$7
pending
:18446744073709551615
$17
last-delivered-id
$15
1717248597227-0
$12
entries-read
:0
$3
lag
:1
```

### What did you expect to see?

This is output from redis-cli.

```bash
redis-server:6379>xinfo groups overflow-test
1)  1) "name"
    2) "info-count-test"
    3) "consumers"
    4) (integer) 0
    5) "pending"
    6) (integer) 0
    7) "last-delivered-id"
    8) "1717249449175-0"
    9) "entries-read"
   10) (integer) 1
   11) "lag"
   12) (integer) 0
```

This output from telnet.

```bash
xinfo groups overflow-test
*1
*12
$4
name
$15
info-count-test
$9
consumers
:0
$7
pending
:0
$17
last-delivered-id
$15
1717249449175-0
$12
entries-read
:1
$3
lag
:0
```

### What did you see instead?

redis-cli refuses to display the response.

```bash
kvrocks-server:6666> xinfo groups overflow-test
Error: Bad integer value
```

telnet get the response from kvrocks-server.

```bash
xinfo groups overflow-test
*1
*12
$4
name
$15
info-count-test
$9
consumers
:0
$7
pending
:18446744073709551615
$17
last-delivered-id
$15
1717248597227-0
$12
entries-read
:0
$3
lag
:1
```

### Anything Else?

Hi kvrocks team,

  I find the way to produce the bug during reading the PR of `XPENDING` #2190 .

  In conversations of the PR, it's suggested to use a separate PR to solve this problem.

  I want to fix the bug and add related unit tests with it.

Best Regards,

Edward

### Are you willing to submit a PR?

- [X] I'm willing to submit a PR!

### PR DESCRIPTION
**Pull request by LindaSummer**
# Issue

close #2350 

# Proposed Changes

- update consumer `pending_number` when consumer group has acknowledged entry.
- add test case for `XINFO`.

### CODE REVIEW

**Review by PragmaTwice — COMMENTED** [review]
PTAL cc @Yangsx-1 @torwig

**Review by Yangsx-1 — DISMISSED** [review]
Good catch! LGTM.

File: src/types/redis_stream.cc [hunk 1]
```diff
@@ -339,20 +339,40 @@ rocksdb::Status Stream::DeletePelEntries(const Slice &stream_name, const std::st
...
     std::string entry_key = internalPelKeyFromGroupAndEntryId(ns_key, metadata, group_name, id);
     std::string value;
     s = storage_->Get(rocksdb::ReadOptions(), stream_cf_handle_, entry_key, &value);
     if (s.ok()) {
       *acknowledged += 1;
       batch->Delete(stream_cf_handle_, entry_key);
+
+      // increment ack for each related consumer
+      auto pel_entry = decodeStreamPelEntryValue(value);
+      if (consumer_acknowledges.find(pel_entry.consumer_name) == consumer_acknowledges.cend()) {
```
Comment (torwig) [inline src/types/redis_stream.cc]: We can simplify this if-else:
`consumer_acknowledges[pel_entry.consumer_name]++;`

This leverages the fact that consumer_acknowledges[pel_entry.consumer_name] will automatically initialize to 0 if pel_entry.consumer_name is not already a key in the map, and then increments it by 1.

Comment (LindaSummer) [reply src/types/redis_stream.cc]: Thanks very much.

I will update it with automatic construction if not existed.

**Comment by LindaSummer** [comment]
Hi @torwig ,

  Thanks for your suggestion.  I have updated the related code.

  Please take a look.

  Thanks very much.

**Review by torwig — DISMISSED** [review]

**Review by Yangsx-1 — DISMISSED** [review]

**Comment by mapleFU** [comment]
CI failed is unrelated, rerun

**Comment by LindaSummer** [comment]
Maybe I need to rebase on unstable branch rather than merge, it involved merge commit in this PR.

**Comment by mapleFU** [comment]
> Maybe I need to rebase on unstable branch rather than merge, it involved merge commit in this PR.

We can squash and merge it in one patch, don't worry about that

**Comment by LindaSummer** [comment]
Thanks very much for your warm help. 😊

The merge commit seems to make coverage calculated more code blocks than my commits.

Do I need to solve it with rebase in this PR to re-trigger the coverage workflow?

File: src/types/redis_stream.cc [hunk 2]
```diff
@@ -339,20 +339,36 @@ rocksdb::Status Stream::DeletePelEntries(const Slice &stream_name, const std::st
...
+      consumer_acknowledges[pel_entry.consumer_name]++;
     }
   }
   if (*acknowledged > 0) {
     StreamConsumerGroupMetadata group_metadata = decodeStreamConsumerGroupMetadataValue(get_group_value);
     group_metadata.pending_number -= *acknowledged;
     std::string group_value = encodeStreamConsumerGroupMetadataValue(group_metadata);
     batch->Put(stream_cf_handle_, group_key, group_value);
+
+    for (const auto &consumer : consumer_acknowledges) {
```
Comment (mapleFU) [inline src/types/redis_stream.cc]:
```suggestion
    for (const auto &[consumer_name, count] : consumer_acknowledges) {
```

File: src/types/redis_stream.cc [hunk 3]
```diff
@@ -339,20 +339,36 @@ rocksdb::Status Stream::DeletePelEntries(const Slice &stream_name, const std::st
...
+      auto consumer_meta_key = internalKeyFromConsumerName(ns_key, metadata, group_name, consumer.first);
+      std::string consumer_meta_original;
+      s = storage_->Get(rocksdb::ReadOptions(), stream_cf_handle_, consumer_meta_key, &consumer_meta_original);
+      if (s.ok()) {
```
Comment (mapleFU) [inline src/types/redis_stream.cc:372]: what if `!s.ok() && !s.IsNotFound()`?

**Review by mapleFU — DISMISSED** [review]

File: src/types/redis_stream.cc (hunk 2 above)
Comment (mapleFU) [reply src/types/redis_stream.cc]: This is reported by sonar, maybe we should fix that

Comment (LindaSummer) [reply src/types/redis_stream.cc]: got it, I will update the loop with this syntax.

File: src/types/redis_stream.cc (hunk 3 above)
Comment (LindaSummer) [reply src/types/redis_stream.cc:372]: Thanks very for your correction.

It should be an internal error and I think that I need to return the error. This function's return type is a `rocksdb::Status` so I don't need to wrap it to another format.

Do I need to add golang integration test for this error handling case? This may be hard to produce a case for it.

Comment (mapleFU) [reply src/types/redis_stream.cc:372]: > Do I need to add golang integration test for this error handling case? 

Currently it's a bit hard to modify this, especially in integration tests. We can just handle this without testing.

Comment (LindaSummer) [reply src/types/redis_stream.cc:372]: Got it! I have corrected my wording above.

This function returns `rocksdb::Status` and I think I should return the status immediately in the function when `!s.ok() && !s.IsNotFound()`.

Comment (mapleFU) [reply src/types/redis_stream.cc:372]: There're two gets here, right? `if (s.ok())` in the loop should also adds this checks(Though errors merely happens)

Comment (LindaSummer) [reply src/types/redis_stream.cc:372]: Thanks for your correction!

Sorry for missing another error handling. I have added it with a new commit.

**Comment by mapleFU** [comment]
Would merge if ci passes

**Review by torwig — APPROVED** [review]

**Comment by git-hulk** [comment]
No worry about this flaky test failure, can rerun to avoid blocking the PR.

**Review by Yangsx-1 — APPROVED** [review]
