### PR TITLE
Fix ZRANGE command should return an empty array when count = 0

### LINKED ISSUE #1483: ZRANGE with LIMIT and COUNT=0
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-kvrocks/issues) and found no similar issues.

### Version

The latest `unstable`.

### Minimal reproduce step

```
127.0.0.1:6666> zadd zset11 1 a 2 b 3 c 4 d 5 e 6 f 7 g
(integer) 7
127.0.0.1:6666> zrange zset11 0 6 byscore limit 0 0
```

### What did you expect to see?

Redis:

```
127.0.0.1:6379> zadd zset11 1 a 2 b 3 c 4 d 5 e 6 f 7 g
(integer) 7
127.0.0.1:6379> zrange zset11 0 6 byscore limit 0 0
(empty array)
```

### What did you see instead?

Kvrocks:

```
127.0.0.1:6666> zrange zset11 0 6 byscore limit 0 0
1) "a"
2) "b"
3) "c"
4) "d"
5) "e"
6) "f"
```

### Anything Else?

_No response_

### Are you willing to submit a PR?

- [ ] I'm willing to submit a PR!

### PR DESCRIPTION
**Pull request by infdahai**
closes #1483

we parse the all procedure and return the empty array quickly when the count of limit is zero. The output is same as `redis`.

### CODE REVIEW

**Comment by infdahai** [comment]
```sh
=== RUN   TestZset/ZRANGE_basics_-_skiplist
    zset_test.go:445: 
                Error Trace:    ~/incubator-kvrocks/tests/gocase/unit/type/zset/zset_test.go:445
                Error:          Not equal: 
                                expected: []string{}
                                actual  : []string(nil)
                            
                                Diff:
                                --- Expected
                                +++ Actual
                                @@ -1,3 +1,2 @@
                                -([]string) {
                                -}
                                +([]string) <nil>
                                 
                Test:           TestZset/ZRANGE_basics_-_skiplist
```
How can I solve this?

**Comment by infdahai** [comment]
Can I ask if we use nilString and we use what to match the value or the err?

**Comment by infdahai** [comment]
```sh
ok  	github.com/apache/incubator-kvrocks/tests/gocase/unit/type/strings	45.094s
--- FAIL: TestZset (6.78s)
    --- FAIL: TestZset/ZRANGE_basics_-_skiplist (0.00s)
        zset_test.go:445: 
            	Error Trace:	/Users/runner/work/incubator-kvrocks/incubator-kvrocks/tests/gocase/unit/type/zset/zset_test.go:445
            	Error:      	Not equal: 
            	            	expected: []string{}
            	            	actual  : []string(nil)
            	            	
            	            	Diff:
            	            	--- Expected
            	            	+++ Actual
            	            	@@ -1,3 +1,2 @@
            	            	-([]string) {
            	            	-}
            	            	+([]string) <nil>
            	            	 
            	Test:       	TestZset/ZRANGE_basics_-_skiplist
    --- FAIL: TestZset/ZRANGEBYLEX_with_LIMIT (0.00s)
        zset_test.go:778: 
            	Error Trace:	/Users/runner/work/incubator-kvrocks/incubator-kvrocks/tests/gocase/unit/type/zset/zset_test.go:778
            	Error:      	Not equal: 
            	            	expected: []interface {}([]interface {}{})
            	            	actual  : <nil>(<nil>)
            	Test:       	TestZset/ZRANGEBYLEX_with_LIMIT
FAIL
```

Hi, if I return the nil string in the redis server, how can I match this msg in go-redis? 
just Use Errorf("redis: nil")?

**Comment by git-hulk** [comment]
@infdahai You can use expression like `require.EqualError(t, r.Err(), redis.Nil.Error())`

**Comment by infdahai** [comment]
> @infdahai You can use expression like `require.EqualError(t, r.Err(), redis.Nil.Error())`

Yeah. I find the correct msg is

File: src/commands/cmd_zset.cc [hunk 1]
```diff
@@ -513,6 +520,8 @@ class CommandZRangeGeneric : public Commander {
       max_idx = 2;
     }
 
+    if (count == 0) zero_count_ = true;
```
Comment (git-hulk) [inline src/commands/cmd_zset.cc]: I think it'd be better to use `spec.count == 0` to check if the count is zero instead of adding a new variable.

File: tests/gocase/unit/type/zset/zset_test.go [hunk 2]
```diff
@@ -439,6 +440,23 @@ func basicTests(t *testing.T, rdb *redis.Client, ctx context.Context, encoding s
 			{4, "d"},
 		}, rdb.ZRangeWithScores(ctx, "ztmp", 0, -1).Val())
 
+		for i := 0; i < 10; i++ {
+			cmd := rdb.ZRangeArgs(ctx, redis.ZRangeArgs{Key: "ztmp", Count: 0, ByScore: true, Start: 0, Stop: -1, Offset: int64(i)})
+			require.Equal(t, []string{}, cmd.Val())
```
Comment (git-hulk) [inline tests/gocase/unit/type/zset/zset_test.go:446]: https://github.com/redis/go-redis/blame/0bdc7dd8986e4923b3309f880245b9311d09f273/commands.go#L2790 won't append the `LIMIT offset,count` if the offset and counter are zero. So for the kvrocks side, it will regard it as the default value which is offset = 0 and count = -1.

By the way, we should check the error first before comparing the value. Same as the following lines, we need to prevent the limit and counter are 0 at the same time.

Comment (infdahai) [reply tests/gocase/unit/type/zset/zset_test.go:446]: Thanks. I didn't read the process in go-redis.

File: src/commands/cmd_zset.cc (hunk 1 above)
Comment (infdahai) [reply src/commands/cmd_zset.cc]: https://github.com/apache/incubator-kvrocks/blob/e89af5289d5c3d12c47628394c72f0d67e652800/src/commands/cmd_zset.cc#L552-L566
Ok, I will add three statements in here.

File: src/commands/cmd_zset.cc [hunk 3]
```diff
@@ -555,9 +561,17 @@ class CommandZRangeGeneric : public Commander {
...
       case kZRangeScore:
+        if (score_spec_.count == 0) {
+          *output = redis::EmptyArray();
+          return Status::OK();
+        }
         s = zset_db.RangeByScore(key_, score_spec_, &member_scores, nullptr);
         break;
       case kZRangeLex:
+        if (lex_spec_.count == 0) {
+          *output = redis::EmptyArray();
```
Comment (infdahai) [inline src/commands/cmd_zset.cc]: we can use `std::vector<std::string> values; *output =MultiBulkString(values, false)` or `*output=redis::MultiLen(0)` to do the same thing.
I should remove the specific `EmptyArray`.

Comment (git-hulk) [reply src/commands/cmd_zset.cc]: Yes, can remove it. Others are good to me.

Comment (torwig) [reply src/commands/cmd_zset.cc]: The third option is just `*output = MultiBulkString({});` since the array is empty and there is no need to care whether use an empty string or nil.
Other changes are good to me as well.

**Review by torwig — APPROVED** [review]
LGTM

**Review by git-hulk — APPROVED** [review]

**Comment by git-hulk** [comment]
Thanks all, merging..
