### PR TITLE
fix(tests): flaky test cases due to the command execution order in WAIT command

### LINKED ISSUE #3197: Flaky test in the WAIT command
### Search before asking

- [x] I had searched in the [issues](https://github.com/apache/kvrocks/issues) and found no similar issues.

### Version

unstable

### Minimal reproduce step

See https://github.com/apache/kvrocks/actions/runs/17882037777/job/50851521027?pr=3196#step:20:171

```
--- FAIL: TestWaitBlockExecutingCommand (3.34s)
    wait_test.go:279: 
        	Error Trace:	/home/runner/work/kvrocks/kvrocks/tests/gocase/unit/wait/wait_test.go:279
        	Error:      	Not equal: 
        	            	expected: "v3"
        	            	actual  : "v2"
        	            	
        	            	Diff:
        	            	--- Expected
        	            	+++ Actual
        	            	@@ -1 +1 @@
        	            	-v3
        	            	+v2
        	Test:       	TestWaitBlockExecutingCommand
FAIL
exit status 1
```

### What did you expect to see?

CI passed

### What did you see instead?

The CI failed due to the flaky test.

### Anything Else?

_No response_

### Are you willing to submit a PR?

- [ ] I'm willing to submit a PR!

### PR DESCRIPTION
**Pull request by git-hulk**
This closes #3197.

### CODE REVIEW

File: tests/gocase/unit/wait/wait_test.go [hunk 1]
```diff
@@ -186,7 +186,7 @@ func TestWaitCommand(t *testing.T) {
 		select {
 		case <-done:
 			// Success - command completed after replica connected
-		case <-time.After(5 * time.Second):
+		case <-time.After(15 * time.Second):
```
Comment (git-hulk) [inline tests/gocase/unit/wait/wait_test.go:189]: Wait for more than the connection timeout (10 seconds by default).

**Review by PragmaTwice — APPROVED** [review]
