### PR TITLE
fix: gcc15 compiler warning `free-nonheap-object` in `cmd_search.cc`

### LINKED ISSUE #3165: Calling ``delete`` on unallocated object.
### Search before asking

- [x] I had searched in the [issues](https://github.com/apache/kvrocks/issues) and found no similar issues.

### Version

OS: Manjaro 6.6.103-3-MANJARO
Kvrocks: unstable branch.

### Minimal reproduce step

Git clone the repository and build using
``./x.py build --ninja -j$(nproc)``
Using GNU gcc for compiling with ninja.

### What did you expect to see?

The build should succeed without any errors.

### What did you see instead?

https://pastebin.com/ypWBs6NW

The build error can be found in the pastebin. As you can see i git cloned the repository and was building normally.

The build fails when building with ninja + gcc. But succeeds if i change compiler and build with ``--compiler=clang`` flag.

The [workflows](https://github.com/SharonIV0x86/kvrocks/actions/runs/17517543435) are passing on my fork's branch with the changes i made. 

### Anything Else?

I am not sure whether this is a problem but a few days back this error was consistent until i changed the compiler from gcc to clang.

### Are you willing to submit a PR?

- [ ] I'm willing to submit a PR!

### PR DESCRIPTION
**Pull request by LindaSummer**
# Issue

fix #3165

# Root cause

This root cause is a new feature in gcc15.2 `free-nonheap-object`.

Here is the error message. It's in link stage.
IMHO it makes me confused at the first time I saw errors like this.

```
[5/7] Linking CXX executable kvrocks
In member function 'deallocate',
    inlined from 'deallocate' at /usr/local/include/c++/15.2.0/bits/alloc_traits.h:649:23,
    inlined from '_M_destroy' at /usr/local/include/c++/15.2.0/bits/basic_string.h:305:34,
    inlined from '_M_dispose' at /usr/local/include/c++/15.2.0/bits/basic_string.h:299:14,
    inlined from '__dt_base ' at /usr/local/include/c++/15.2.0/bits/basic_string.h:896:19,
    inlined from '__dt_base ' at /build/src/common/status.h:170:3,
    inlined from '__dt_base ' at /build/src/common/status.h:362:23,
    inlined from 'Execute' at /build/src/commands/cmd_search.cc:543:25:
/usr/local/include/c++/15.2.0/bits/new_allocator.h:172:66: warning: 'operator delete' called on unallocated object '<anonymous>' [-Wfree-nonheap-object]
  172 |         _GLIBCXX_OPERATOR_DELETE(_GLIBCXX_SIZED_DEALLOC(__p, __n));
      |                                                                  ^
/build/src/commands/cmd_search.cc: In member function 'Execute':
/build/src/commands/cmd_search.cc:543:25: note: declared here
  543 |     auto field_values = GET_OR_RET(srv->index_mgr.TagValues(ctx, index_name, tag_field_name, conn->GetNamespace()));
      |                         ^
In member function 'deallocate',
    inlined from 'deallocate' at /usr/local/include/c++/15.2.0/bits/alloc_traits.h:649:23,
    inlined from '_M_destroy' at /usr/local/include/c++/15.2.0/bits/basic_string.h:305:34,
    inlined from '_M_dispose' at /usr/local/include/c++/15.2.0/bits/basic_string.h:299:14,
    inlined from '__dt_base ' at /usr/local/include/c++/15.2.0/bits/basic_string.h:896:19,
    inlined from '__dt_base ' at /build/src/common/status.h:170:3,
    inlined from '__dt_base ' at /build/src/common/status.h:362:23,
    inlined from 'Execute' at /build/src/commands/cmd_search.cc:543:25:
/usr/local/include/c++/15.2.0/bits/new_allocator.h:172:66: warning: 'operator delete' called on unallocated object '<anonymous>' [-Wfree-nonheap-object]
  172 |         _GLIBCXX_OPERATOR_DELETE(_GLIBCXX_SIZED_DEALLOC(__p, __n));
      |                                                                  ^
/build/src/commands/cmd_search.cc: In member function 'Execute':
/build/src/commands/cmd_search.cc:543:25: note: declared here
  543 |     auto field_values = GET_OR_RET(srv->index_mgr.TagValues(ctx, index_name, tag_field_name, conn->GetNamespace()));
      |                         ^
[6/7] Linking CXX executable kvrocks2redis
In member function 'deallocate',
    inlined from 'deallocate' at /usr/local/include/c++/15.2.0/bits/alloc_traits.h:649:23,
    inlined from '_M_destroy' at /usr/local/include/c++/15.2.0/bits/basic_string.h:305:34,
    inlined from '_M_dispose' at /usr/local/include/c++/15.2.0/bits/basic_string.h:299:14,
    inlined from '__dt_base ' at /usr/local/include/c++/15.2.0/bits/basic_string.h:896:19,
    inlined from '__dt_base ' at /build/src/common/status.h:170:3,
    inlined from '__dt_base ' at /build/src/common/status.h:362:23,
    inlined from 'Execute' at /build/src/commands/cmd_search.cc:543:25:
/usr/local/include/c++/15.2.0/bits/new_allocator.h:172:66: warning: 'operator delete' called on unallocated object '<anonymous>' [-Wfree-nonheap-object]
  172 |         _GLIBCXX_OPERATOR_DELETE(_GLIBCXX_SIZED_DEALLOC(__p, __n));
      |                                                                  ^
/build/src/commands/cmd_search.cc: In member function 'Execute':
/build/src/commands/cmd_search.cc:543:25: note: declared here
  543 |     auto field_values = GET_OR_RET(srv->index_mgr.TagValues(ctx, index_name, tag_field_name, conn->GetNamespace()));
      |                         ^
In member function 'deallocate',
    inlined from 'deallocate' at /usr/local/include/c++/15.2.0/bits/alloc_traits.h:649:23,
    inlined from '_M_destroy' at /usr/local/include/c++/15.2.0/bits/basic_string.h:305:34,
    inlined from '_M_dispose' at /usr/local/include/c++/15.2.0/bits/basic_string.h:299:14,
    inlined from '__dt_base ' at /usr/local/include/c++/15.2.0/bits/basic_string.h:896:19,
    inlined from '__dt_base ' at /build/src/common/status.h:170:3,
    inlined from '__dt_base ' at /build/src/common/status.h:362:23,
    inlined from 'Execute' at /build/src/commands/cmd_search.cc:543:25:
/usr/local/include/c++/15.2.0/bits/new_allocator.h:172:66: warning: 'operator delete' called on unallocated object '<anonymous>' [-Wfree-nonheap-object]
  172 |         _GLIBCXX_OPERATOR_DELETE(_GLIBCXX_SIZED_DEALLOC(__p, __n));
      |                                                                  ^
/build/src/commands/cmd_search.cc: In member function 'Execute':
/build/src/commands/cmd_search.cc:543:25: note: declared here
  543 |     auto field_values = GET_OR_RET(srv->index_mgr.TagValues(ctx, index_name, tag_field_name, conn->GetNamespace()));
      | 
```

If I understand correctly, it should caused by the dtor of `Status`.

https://github.com/apache/kvrocks/blob/dfdd2105df3b206e95accea217d50d70dbbee220/src/common/status.h#L358-L364

# Proposed Changes

Mitigate this problem by implicitly checking the status without the `GET_OR_RET` macro.

### CODE REVIEW

**Comment by LindaSummer** [comment]
Hi @PragmaTwice ,

Sorry to bother you. 😊

I'm not sure current code change is a good enough way to solve this. Do you have any idea on this? 😊

Plus, do we need to pin the version of Arch Linux in CI since this problem is found in Manjaro?
This problem has happened once due to an unstable rolling update toolchain version.

Best Regards,
Edward

**Comment by mapleFU** [comment]
Curious that if this caused by `Status`, why other `GET_OR_RET` is works on other places and only report error here?

**Comment by LindaSummer** [comment]
> Curious that if this caused by `Status`, why other `GET_OR_RET` is works on other places and only report error here?

Yes, it also makes me confused. If the dtor is invalid, why manually expand the macro, then it was fixed? 😵
The detecting stage also seems to be strange. The macro should be expanded in the preprocessor stage, and the warning is in the link stage.

**Comment by PragmaTwice** [comment]
I prefer that it is a false positive. Although the change looks fine.

File: src/commands/cmd_search.cc [hunk 1]
```diff
@@ -540,9 +540,12 @@ class CommandFTTagVals : public Commander {
   Status Execute(engine::Context &ctx, Server *srv, Connection *conn, std::string *output) override {
     const auto &index_name = args_[1];
     const auto &tag_field_name = args_[2];
-    auto field_values = GET_OR_RET(srv->index_mgr.TagValues(ctx, index_name, tag_field_name, conn->GetNamespace()));
+    auto field_values = srv->index_mgr.TagValues(ctx, index_name, tag_field_name, conn->GetNamespace());
+    if (!field_values.IsOK()) {
+      return field_values.ToStatus();
+    }
```
Comment (PragmaTwice) [inline src/commands/cmd_search.cc]:
```suggestion
    if (!field_values) {
      return field_values;
    }
```

Comment (LindaSummer) [reply src/commands/cmd_search.cc]: Hi @PragmaTwice ,

Thanks for your update and suggestion!😊

Best Regards,
Edward

**Comment by LindaSummer** [comment]
Hi @PragmaTwice ,

Sorry to bother you again. 
Could you help take a look at the change? 😊

Best Regards,
Edward

**Review by PragmaTwice — APPROVED** [review]
I'm fine with this change. But still need to mention that it's probably a false positive.
