### PR TITLE
Fix flaky test in migration timeout

### LINKED ISSUE #1452: migrate timeout in Go Integration Cases
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-kvrocks/issues) and found no similar issues.

### Version

unstable

### Minimal reproduce step

the ref to CI jobs: https://github.com/infdahai/incubator-kvrocks/actions/runs/5032023303/jobs/9025509337

The change is on https://github.com/infdahai/incubator-kvrocks/compare/fb0e3d4...7a5a2c2. I only run 10  tests in a loop.

### What did you expect to see?

All tests pass， especially the `Migrate_sync_with_(or_without)_all_kinds_of_timeouts` test.

### What did you see instead?

  --- FAIL: TestSlotMigrateSync/MIGRATE_-_Migrate_sync_with_(or_without)_all_kinds_of_timeouts#09 (0.01s)
        slotmigrate_test.go:426: 
            	Error Trace:	/home/runner/work/incubator-kvrocks/incubator-kvrocks/tests/gocase/integration/slotmigrate/slotmigrate_test.go:426
            	Error:      	Not equal: 
            	            	expected: string("OK")
            	            	actual  : <nil>(<nil>)
            	Test:       	TestSlotMigrateSync/MIGRATE_-_Migrate_sync_with_(or_without)_all_kinds_of_timeouts#09

### Anything Else?

_No response_

### Are you willing to submit a PR?

- [ ] I'm willing to submit a PR!

### PR DESCRIPTION
**Pull request by git-hulk**
This closes #1452

### CODE REVIEW

**Comment by git-hulk** [comment]
We have reproduced this flaky error: https://github.com/apache/incubator-kvrocks/actions/runs/5044728692/jobs/9055654883. It's caused by the slot conflict when running the migration, let's increase the start slot to avoid this.

File: tests/gocase/integration/slotmigrate/slotmigrate_test.go [hunk 1]
```diff
@@ -412,23 +412,19 @@ func TestSlotMigrateSync(t *testing.T) {
...
-
-		slot++
-		require.Equal(t, "OK", rdb0.Do(ctx, "clusterx", "migrate", slot, id1, "sync", 10).Val())
-
-		slot++
-		require.Equal(t, "OK", rdb0.Do(ctx, "clusterx", "migrate", slot, id1, "sync", 0.5).Val())
-
-		slot++
-		require.Equal(t, "OK", rdb0.Do(ctx, "clusterx", "migrate", slot, id1, "sync", -3.14).Val())
+		slot := 1024
```
Comment (tisonkun) [inline tests/gocase/integration/slotmigrate/slotmigrate_test.go]: Can we add a comment for this magic number? From the description it's to avoid slot num conflict.

Comment (git-hulk) [reply tests/gocase/integration/slotmigrate/slotmigrate_test.go]: Sure. To be honest, we didn't take care of those slot distributions when writing test cases, so it's a bit confusing for using which slot now.

Comment (infdahai) [reply tests/gocase/integration/slotmigrate/slotmigrate_test.go]: The reason for this error is that the sync time is too small such as `0.5s` and CI often runs failed while local machines run successful. And the commit https://github.com/apache/incubator-kvrocks/commit/635dd311e5d07007826ae5338eae4cefb88ccc55 also improves read success rate.

Comment (infdahai) [reply tests/gocase/integration/slotmigrate/slotmigrate_test.go]: So when I use a very small time parameter causing a failure, the program calls `resume` func and returns `nil` value. Maybe we need the following test. But the following statements may fail from my tests with throwing `There is already a migrating slot`.

```go
				// for result.Val() == nil && timeout < 15 {
				// 	timeout += 5
				// 	result := rdb0.Do(ctx, "clusterx", "migrate", slot, id1, "sync", timeout)
				// 	require.NoError(t, result.Err())
				// }
				// 	require.Equal(t, "OK", result.Val())

```

Comment (git-hulk) [reply tests/gocase/integration/slotmigrate/slotmigrate_test.go]: Yes, [8c76f33](https://github.com/apache/incubator-kvrocks/pull/1464/commits/8c76f3339b344b13a9964a075d08737c9e95bb56) this commit has increased the timeout.

**Review by infdahai — DISMISSED** [review]

**Review by torwig — DISMISSED** [review]

File: tests/gocase/integration/slotmigrate/slotmigrate_test.go [hunk 2]
```diff
@@ -422,7 +422,7 @@ func TestSlotMigrateSync(t *testing.T) {
 		for _, timeout := range timeouts {
 			slot++
 			result := rdb0.Do(ctx, "clusterx", "migrate", slot, id1, "sync", timeout)
-			require.NoError(t, result.Err())
+			require.NoError(t, result.Err(), "without timeout: %v", timeout)
```
Comment (ellutionist) [inline tests/gocase/integration/slotmigrate/slotmigrate_test.go]: Should the message be "with timeout"?

File: tests/gocase/integration/slotmigrate/slotmigrate_test.go [hunk 3]
```diff
@@ -422,7 +422,7 @@ func TestSlotMigrateSync(t *testing.T) {
...
 			require.Equal(t, "OK", result.Val())
```
Comment (ellutionist) [inline tests/gocase/integration/slotmigrate/slotmigrate_test.go]: Perhaps add "with timeout" message here also?

File: tests/gocase/integration/slotmigrate/slotmigrate_test.go (hunk 2 above)
Comment (git-hulk) [reply tests/gocase/integration/slotmigrate/slotmigrate_test.go]: Yes, it's a typo.

File: tests/gocase/integration/slotmigrate/slotmigrate_test.go [hunk 4]
```diff
@@ -413,22 +413,18 @@ func TestSlotMigrateSync(t *testing.T) {
...
+		result := rdb0.Do(ctx, "clusterx", "migrate", slot, id1, "sync")
+		require.NoError(t, result.Err())
+		require.Equal(t, "OK", result.Val())
+
+		timeouts := []interface{}{-1, 0, 20, 10.5, -3.14}
+		for _, timeout := range timeouts {
+			slot++
+			result := rdb0.Do(ctx, "clusterx", "migrate", slot, id1, "sync", timeout)
+			require.NoError(t, result.Err(), "without timeout: %v", timeout)
+			require.Equal(t, "OK", result.Val())
```
Comment (git-hulk) [inline tests/gocase/integration/slotmigrate/slotmigrate_test.go]:
```suggestion
			require.NoError(t, result.Err(), "with timeout: %v", timeout)
			require.Equal(t, "OK", result.Val(), "with timeout: %v", timeout)
```

File: tests/gocase/integration/slotmigrate/slotmigrate_test.go [hunk 5]
```diff
@@ -413,22 +413,18 @@ func TestSlotMigrateSync(t *testing.T) {
...
-		require.Equal(t, "OK", rdb0.Do(ctx, "clusterx", "migrate", slot, id1, "sync", 0.5).Val())
-
-		slot++
-		require.Equal(t, "OK", rdb0.Do(ctx, "clusterx", "migrate", slot, id1, "sync", -3.14).Val())
+		// migrate sync without explicitly specify the timeout
+		result := rdb0.Do(ctx, "clusterx", "migrate", slot, id1, "sync")
+		require.NoError(t, result.Err())
+		require.Equal(t, "OK", result.Val())
+
+		timeouts := []interface{}{-1, 0, 20, 10.5, -3.14}
```
Comment (torwig) [inline tests/gocase/integration/slotmigrate/slotmigrate_test.go]: Could we use `[]float64` here instead of `[]interface{}`?
If the timeout is a negative value, should it be an error?

Comment (torwig) [reply tests/gocase/integration/slotmigrate/slotmigrate_test.go]: I see that right now timeout < 0 doesn't produce an error. Should we introduce an error in this case? Or just treat it as an absence of a timeout?

Comment (git-hulk) [reply tests/gocase/integration/slotmigrate/slotmigrate_test.go]: For the negative timeout, I also prefer retrieving an error instead of regarding it as 0. But I think we can submit another PR to fix this.

> Could we use []float64 here instead of []interface{}?

It's intent to use the interface{} since I wanna make sure that the int and float types are working well.

Comment (torwig) [reply tests/gocase/integration/slotmigrate/slotmigrate_test.go]: @git-hulk Do we ever need floats there? I see that float is cast to int in the code, so I think we should consider timeout as an integer number of seconds and prohibit float and negative values.

Comment (git-hulk) [reply tests/gocase/integration/slotmigrate/slotmigrate_test.go]: Good catch, I didn't dive into the implementation. For the server side, it allows the float timeout now, but I think it's unnecessary to support that.

Comment (git-hulk) [reply tests/gocase/integration/slotmigrate/slotmigrate_test.go]: I will append a commit to resolve the above comments.

Comment (ellutionist) [reply tests/gocase/integration/slotmigrate/slotmigrate_test.go]: @torwig @git-hulk The original reason to support float timeout is that in the go tests I want to "deliberately let the sync migration timeout" (see [here](https://github.com/apache/incubator-kvrocks/blob/unstable/tests/gocase/integration/slotmigrate/slotmigrate_test.go#L440)). And the minimal integer value of "1" is too large and cannot ensure the timeout happen...

Also I think supporting float timeout is not harmful but provides more precise control to the migration. What do you think?

As for the negative value, returning an error when the server receives an negative value seems acceptable to me. No problem.

Comment (torwig) [reply tests/gocase/integration/slotmigrate/slotmigrate_test.go]: @ellutionist Timeout is in seconds as far as I see so I don't think that making the timeout less than 1 second is reasonable (it's about migrating slot with data from one node to another via network).

Comment (git-hulk) [reply tests/gocase/integration/slotmigrate/slotmigrate_test.go]: @ellutionist Another concern is float timeout may be inconsistent with other commands.

**Review by torwig — DISMISSED** [review]
LGTM

**Comment by git-hulk** [comment]
@torwig I fixed the sync timeout test case as well in the last commit: https://github.com/apache/incubator-kvrocks/pull/1464/commits/bcc7b8509ab69f432f42c5cdeda43855ea066f4f, please take a look again. After changing the timeout to int, then use the float timeout would return an error.

File: tests/gocase/integration/slotmigrate/slotmigrate_test.go [hunk 6]
```diff
@@ -435,17 +435,15 @@ func TestSlotMigrateSync(t *testing.T) {
...
+		cnt := 200000
 		for i := 0; i < cnt; i++ {
 			require.NoError(t, rdb0.LPush(ctx, util.SlotTable[slot], i).Err())
 		}
-		timeout := 0.001
-
-		require.Nil(t, rdb0.Do(ctx, "clusterx", "migrate", slot, id1, "sync", timeout).Val())
 
-		// check the following command on the same connection
-		require.Equal(t, "PONG", rdb0.Ping(ctx).Val())
```
Comment (git-hulk) [inline tests/gocase/integration/slotmigrate/slotmigrate_test.go:445]: This line won' take effect since we're using the connection pool.

Comment (torwig) [reply tests/gocase/integration/slotmigrate/slotmigrate_test.go:445]: @git-hulk Yes, absolutely.

File: src/commands/cmd_cluster.cc [hunk 7]
```diff
@@ -146,7 +146,14 @@ class CommandClusterX : public Commander {
           sync_migrate_ = true;
 
           if (args.size() == 6) {
-            sync_migrate_timeout_ = GET_OR_RET(ParseFloat<float>(args[5]));
+            auto parse_result = ParseInt<int>(args[5], 10);
+            if (!parse_result) {
+              return {Status::RedisParseErr, "timeout is not an integer or out of range"};
+            }
+            if (*parse_result < 0) {
+              return {Status::RedisParseErr, "timeout should not be negative"};
```
Comment (infdahai) [inline src/commands/cmd_cluster.cc]:
```suggestion
              return {Status::RedisParseErr, errTimeoutIsNegative};
```

File: tests/gocase/integration/slotmigrate/slotmigrate_test.go [hunk 8]
```diff
@@ -418,12 +418,19 @@ func TestSlotMigrateSync(t *testing.T) {
 		require.NoError(t, result.Err())
 		require.Equal(t, "OK", result.Val())
 
-		timeouts := []interface{}{-1, 0, 20, 10.5, -3.14}
-		for _, timeout := range timeouts {
+		invalidTimeouts := []interface{}{-2, -1, "abc"}
```
Comment (infdahai) [inline tests/gocase/integration/slotmigrate/slotmigrate_test.go]: Does it need to add a float argument to show the above dicussion?

**Review by infdahai — CHANGES_REQUESTED** [review]

File: src/cluster/sync_migrate_context.h [hunk 9]
```diff
@@ -25,7 +25,7 @@
 class SyncMigrateContext : private EvbufCallbackBase<SyncMigrateContext, false>,
                            private EventCallbackBase<SyncMigrateContext> {
  public:
-  SyncMigrateContext(Server *svr, redis::Connection *conn, float timeout) : svr_(svr), conn_(conn), timeout_(timeout){};
+  SyncMigrateContext(Server *svr, redis::Connection *conn, int timeout) : svr_(svr), conn_(conn), timeout_(timeout){};
```
Comment (infdahai) [inline src/cluster/sync_migrate_context.h:28]: BTW, shall we add a float test to gtests with improving code coverage?

File: tests/gocase/integration/slotmigrate/slotmigrate_test.go [hunk 10]
```diff
@@ -413,36 +413,37 @@ func TestSlotMigrateSync(t *testing.T) {
...
-		require.Equal(t, "OK", rdb0.Do(ctx, "clusterx", "migrate", slot, id1, "sync", 10).Val())
-
-		slot++
-		require.Equal(t, "OK", rdb0.Do(ctx, "clusterx", "migrate", slot, id1, "sync", 0.5).Val())
+		// migrate sync without explicitly specify the timeout
+		result := rdb0.Do(ctx, "clusterx", "migrate", slot, id1, "sync")
+		require.NoError(t, result.Err())
+		require.Equal(t, "OK", result.Val())
+
+		invalidTimeouts := []interface{}{-2, -1, "abc"}
```
Comment (git-hulk) [inline tests/gocase/integration/slotmigrate/slotmigrate_test.go]:
```suggestion
		invalidTimeouts := []interface{}{-2, -1, 1.2, "abc"}
```

File: src/cluster/sync_migrate_context.h (hunk 9 above)
Comment (git-hulk) [reply src/cluster/sync_migrate_context.h:28]: We should do it in util::ParseXXX test cases instead of here.

Comment (infdahai) [reply src/cluster/sync_migrate_context.h:28]: we only use `Parsefloat` now in kvrocks to parse `geo` positions, hash computing, some command with concrete needs, such as `ZADD`, `INCRBYFLOAT`.

**Review by torwig — APPROVED** [review]

**Comment by git-hulk** [comment]
Thanks all, merging...
