### PR TITLE
fix(stream): add `KeyRangeGen` for `XRead` and `XReadGroup`

### LINKED ISSUE #2625: Key range of XREAD/XREADGROUP is not correct
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/kvrocks/issues) and found no similar issues.

### Version

unstable

### Minimal reproduce step

https://github.com/apache/kvrocks/blob/5fccd57c66bc8f0e4138924fe6a0148931e5650f/src/commands/cmd_stream.cc#L1891-L1892

We need to define a KeyRangeGen function to make it produce correct key range.

### What did you expect to see?

--

### What did you see instead?

--

### Anything Else?

_No response_

### Are you willing to submit a PR?

- [ ] I'm willing to submit a PR!

### PR DESCRIPTION
**Pull request by LindaSummer**
# Issue

Close #2625 .

# Proposed Changes

- Refactor `Parse` function for `XRead` and `XReadGroup`.
- Add `KeyRangeGen` for `XRead` and `XReadGroup`.

### CODE REVIEW

File: src/commands/cmd_stream.cc [hunk 1]
```diff
@@ -1715,6 +1684,27 @@ class CommandXReadGroup : public Commander,
     bufferevent_enable(bev, EV_READ);
   }
 
+  static CommandKeyRangeGen KeyRangeGen() {
+    static constexpr auto keyRangeGenFunc = [](const std::vector<std::string> &args) {
+      auto parsed_args = *parse(args);
```
Comment (PragmaTwice) [inline src/commands/cmd_stream.cc]: Hmm actually from my side I don't think we need to reuse the code of `Parse()`, since:
- many fields in `parsed_args` is useless in key range gen, so we made lots of useless string copies.
- in key range gen we can assume that the syntax of the input args is valid, so we can omit many checks.

File: src/commands/cmd_stream.cc [hunk 2]
```diff
@@ -1715,6 +1684,27 @@ class CommandXReadGroup : public Commander,
     bufferevent_enable(bev, EV_READ);
   }
 
+  static CommandKeyRangeGen KeyRangeGen() {
+    static constexpr auto keyRangeGenFunc = [](const std::vector<std::string> &args) {
```
Comment (PragmaTwice) [inline src/commands/cmd_stream.cc]:
```suggestion
  static CommandKeyRange KeyRangeGen(const std::vector<std::string> &args) {
```

Also we don't need to make a function that returns a function here.

File: src/commands/cmd_stream.cc (hunk 1 above)
Comment (LindaSummer) [reply src/commands/cmd_stream.cc]: Hi @PragmaTwice ,

Thanks for your suggestions! 😊

I have reverted the original `Parse` function and add a simple search function for parsing stream key counts.

Best Regards,
Edward

File: src/commands/cmd_stream.cc (hunk 2 above)
Comment (LindaSummer) [reply src/commands/cmd_stream.cc]: Hi @PragmaTwice ,

Got it!

I have changed it to a static variable. 😊

Best Regards,
Edward

File: src/commands/cmd_stream.cc [hunk 3]
```diff
@@ -33,6 +33,22 @@
 #include "types/redis_stream.h"
 
 namespace redis {
+namespace {
+// for XRead and XReadGroup stream range parse.
+CommandKeyRange ParseStreamReadRange(const std::vector<std::string> &args) {
+  // assert here we must have a stream in args since it has been parsed.
+  auto stream_keyword_iter =
+      std::find_if(args.cbegin(), args.cend(), [](const std::string &arg) { return util::ToLower(arg) == "streams"; });
```
Comment (PragmaTwice) [inline src/commands/cmd_stream.cc]:
```suggestion
  auto stream_keyword_iter =
      std::find_if(args.cbegin(), args.cend(), [](const std::string &arg) { return util::EqualICase(arg, "streams"); });
```

Comment (LindaSummer) [reply src/commands/cmd_stream.cc]: Hi @PragmaTwice ,

Thanks very much for your suggestion! 😊

I have replaced the comparison operator to `util::EqualICase`.

Best Regards,
Edward

File: src/commands/cmd_stream.cc [hunk 4]
```diff
@@ -33,6 +33,22 @@
 #include "types/redis_stream.h"
 
 namespace redis {
+namespace {
+// for XRead and XReadGroup stream range parse.
+CommandKeyRange ParseStreamReadRange(const std::vector<std::string> &args) {
+  // assert here we must have a stream in args since it has been parsed.
+  auto stream_keyword_iter =
+      std::find_if(args.cbegin(), args.cend(), [](const std::string &arg) { return util::EqualICase(arg, "streams"); });
```
Comment (PragmaTwice) [inline src/commands/cmd_stream.cc]: For XREADGROUP, I think we need to find from `begin + 4`, to avoid a group or consumer named `streams`.

refer to https://redis.io/docs/latest/commands/xreadgroup/ .

Comment (LindaSummer) [reply src/commands/cmd_stream.cc]: Hi @PragmaTwice ,

Thanks very much for your review! 😊

I have updated the `ParseStreamReadRange` with a begin offset.

Best Regards,
Edward

**Review by PragmaTwice — COMMENTED** [review]
The code looks good to me.

Would you like to write a go test case that calls redis command `COMMAND GETKEYS XREAD/XREADGROUP ...` to confirm the returned keys is correct?

You can add a new test like https://github.com/apache/kvrocks/blob/unstable/tests/gocase/unit/command/command_test.go#L125.

**Comment by LindaSummer** [comment]
> The code looks good to me.
> 
> 
> 
> Would you like to write a go test case that calls redis command `COMMAND GETKEYS XREAD/XREADGROUP ...` to confirm the returned keys is correct?
> 
> 
> 
> You can add a new test like https://github.com/apache/kvrocks/blob/unstable/tests/gocase/unit/command/command_test.go#L125.

Of course! 

I will add unittest later today.😄

Best Regards,
Edward

**Comment by LindaSummer** [comment]
Hi @PragmaTwice ,

I have added related unit tests for different combinations of `XREAD` and `XREADGROUP`. 😊

Best Regards,
Edward

**Review by PragmaTwice — APPROVED** [review]
