### PR TITLE
Fix outdated result in type command for expired keys

### LINKED ISSUE #1278: For the expired key, the TYPE command returns dirty data
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-kvrocks/issues) and found no similar issues.

### Version

kvrocks v2.3.0

### Minimal reproduce step

```
127.0.0.1:31001> set k v ex 10
OK
127.0.0.1:31001> type k
"string"
127.0.0.1:31001> ttl k
(integer) 3
127.0.0.1:31001> ttl k
(integer) -2
127.0.0.1:31001> type k
"string"
127.0.0.1:31001> get k
(nil)
127.0.0.1:31001> type k
"string"
```

### What did you expect to see?

**None** should been returned for the expired key

### What did you see instead?

For the expired key, the TYPE command returns dirty data

### Anything Else?

_No response_

### Are you willing to submit a PR?

- [x] I'm willing to submit a PR!

### PR DESCRIPTION
**Pull request by jjz921024**
1. fix #1278 
2. For compatibility with the redis command format, the type command should return simpleString instead of bulkString

### CODE REVIEW

File: src/storage/redis_db.cc [hunk 1]
```diff
@@ -441,7 +442,12 @@ rocksdb::Status Database::Type(const Slice &user_key, RedisType *type) {
 
   Metadata metadata(kRedisNone, false);
   metadata.Decode(value);
-  *type = metadata.Type();
+  if (metadata.Expired()) {
+    value.clear();
```
Comment (git-hulk) [inline src/storage/redis_db.cc]:
```suggestion
```

**Review by git-hulk — APPROVED** [review]
LGTM, thanks for your contribution.

**Review by PragmaTwice — APPROVED** [review]

**Review by torwig — APPROVED** [review]

**Comment by PragmaTwice** [comment]
@jjz921024 Merged. Thanks for your contribution again!
