### PR TITLE
Fix flaky test failure in TestSlotMigrateSync

### LINKED ISSUE #1679: Flaky test in migration sync timeout
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/kvrocks/issues) and found no similar issues.

### Version

unstable

### Minimal reproduce step

None

### What did you expect to see?

Go tests are green

### What did you see instead?

```
--- FAIL: TestSlotMigrateSync (44.63s)
    --- FAIL: TestSlotMigrateSync/MIGRATE_-_Migrate_sync_with_(or_without)_all_kinds_of_timeouts (0.01s)
        slotmigrate_test.go:477: 
            	Error Trace:	/home/runner/work/kvrocks/kvrocks/tests/gocase/integration/slotmigrate/slotmigrate_test.go:477
            	Error:      	Received unexpected error:
            	            	ERR There is already a migrating slot
            	Test:       	TestSlotMigrateSync/MIGRATE_-_Migrate_sync_with_(or_without)_all_kinds_of_timeouts
            	Messages:   	with timeout: 30
FAIL
exit status 1
```

### Anything Else?

_No response_

### Are you willing to submit a PR?

- [X] I'm willing to submit a PR!

### PR DESCRIPTION
**Pull request by git-hulk**
Currently, go-redis will auto-retry if occurs network timeout error,
and it may duplicate send the migration command. So we can just ignore
this specific error to avoid the flaky failure.

The Ci logs:
```
--- FAIL: TestSlotMigrateSync (44.63s)
    --- FAIL: TestSlotMigrateSync/MIGRATE_-_Migrate_sync_with_(or_without)_all_kinds_of_timeouts (0.01s)
        slotmigrate_test.go:477: 
            	Error Trace:	/home/runner/work/kvrocks/kvrocks/tests/gocase/integration/slotmigrate/slotmigrate_test.go:477
            	Error:      	Received unexpected error:
            	            	ERR There is already a migrating slot
            	Test:       	TestSlotMigrateSync/MIGRATE_-_Migrate_sync_with_(or_without)_all_kinds_of_timeouts
            	Messages:   	with timeout: 30
FAIL
exit status 1
```

This closes #1679

### CODE REVIEW

File: tests/gocase/integration/slotmigrate/slotmigrate_test.go [hunk 1]
```diff
@@ -473,9 +473,12 @@ func TestSlotMigrateSync(t *testing.T) {
...
 			slot++
-			result := rdb0.Do(ctx, "clusterx", "migrate", slot, id1, "sync", timeout)
-			require.NoError(t, result.Err(), "with timeout: %v", timeout)
-			require.Equal(t, "OK", result.Val(), "with timeout: %d", timeout)
+			err := rdb0.Do(ctx, "clusterx", "migrate", slot, id1, "sync", timeout).Err()
+			// go-redis will auto-retry if occurs timeout error, so it may return the already migrated slot error,
+			// so we just allow this error here to prevent the flaky test failure.
+			if err != nil && !strings.Contains(err.Error(), "ERR There is already a migrating slot") {
+				require.NoError(t, err)
+			}
```
Comment (mapleFU) [inline tests/gocase/integration/slotmigrate/slotmigrate_test.go:481]:
```suggestion
			} else {
			require.Equal(t, "OK", result.Val(), "with timeout: %d", timeout)
			}
```

Would this be better?

**Comment by torwig** [comment]
@git-hulk I'm not sure if it makes sense to completely disable retries with the following option:

```
// Maximum number of retries before giving up.
// Default is 3 retries; -1 (not 0) disables retries.
MaxRetries int
```

File: tests/gocase/integration/slotmigrate/slotmigrate_test.go (hunk 1 above)
Comment (git-hulk) [reply tests/gocase/integration/slotmigrate/slotmigrate_test.go:481]: I'm intent to remove this because the value should be always ok if no error.

**Comment by git-hulk** [comment]
> @git-hulk I'm not sure if it makes sense to completely disable retries with the following option:
> 
> ```
> // Maximum number of retries before giving up.
> // Default is 3 retries; -1 (not 0) disables retries.
> MaxRetries int
> ```

Yes, I also considered this solution, but it'll be failed as well if the timeout happened.

**Review by enjoy-binbin — APPROVED** [review]
Make sense to me.
is there a way we can increase the timeout? it is odd that they timeout on the same instance (machine). In this case, our other commands may also have the possibility of repeated sending.

**Comment by git-hulk** [comment]
> Make sense to me.
is there a way we can increase the timeout? it is odd that they timeout on the same instance (machine). In this case, our other commands may also have the possibility of repeated sending.

That's right, we also have the same flaky test in list_test.go which go-redis auto retry may cause LPUSH duplicate elements. Maybe we can increase the timeout and disable retry for all test cases.

**Review by torwig — APPROVED** [review]
