### PR TITLE
Fix parse BITCOUNT

### LINKED ISSUE #1978: `BITCOUNT` return wrong when args > 4
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/kvrocks/issues) and found no similar issues.

### Version

unstable

### Minimal reproduce step

```shell
127.0.0.1:6666> SET mykey "foobar"
OK
127.0.0.1:6666> BITCOUNT mykey 5 30
(integer) 4
127.0.0.1:6666> BITCOUNT mykey 5 30 111
(integer) 26
```

### What did you expect to see?

`BITCOUNT mykey 5 30 111` return 4

### What did you see instead?

`BITCOUNT mykey 5 30 111` return ERROR

### Anything Else?

https://github.com/apache/kvrocks/blob/574d438b9acde7b45b0666564af4450c057aceea/src/commands/cmd_bit.cc#L94-L117

We need return ERROR when `args.size() > 4`

### Are you willing to submit a PR?

- [ ] I'm willing to submit a PR!

### PR DESCRIPTION
**Pull request by tisonkun**
This closes #1978 .

### CODE REVIEW

File: src/commands/cmd_bit.cc [hunk 1]
```diff
@@ -113,6 +118,15 @@ class CommandBitCount : public Commander {
       stop_ = *parse_stop;
     }
 
+    if (args.size() == 5) {
+      if (util::EqualICase(args[4], "BYTE")) {
+      } else if (util::EqualICase(args[4], "BIT")) {
```
Comment (tisonkun) [inline src/commands/cmd_bit.cc:123]: BIT modifier is supported in Redis 7.0.

But we assume counting in bytes everywhere so it's non-trivial to implement. It can be a follow-up issue.

Comment (tisonkun) [reply src/commands/cmd_bit.cc:123]: https://redis.io/commands/bitcount/

**Comment by tisonkun** [comment]
The patch is trivial and it's not worthy to add a test case ..

**Review by git-hulk — APPROVED** [review]

**Review by PragmaTwice — APPROVED** [review]

**Review by mapleFU — APPROVED** [review]
