### PR TITLE
fix(core): potential data race between blocking command and transaction

### LINKED ISSUE #2766: memtable, bg_error: Corruption: WriteBatch has wrong count
### Search before asking

- [x] I had searched in the [issues](https://github.com/apache/kvrocks/issues) and found no similar issues.

### Version

I'm trying to move from Redis to KVRocks as I need a durable storage for a Job Queue system based on python rq.

Everything is working but whenever a restart KVRocks or the python code I receive this error:

E20250203 14:38:03.244154 139655422928576 event_listener.cc:166] [event_listener/background_error] reason: memtable, bg_error: Corruption: WriteBatch has wrong count

I need to start from scratch to solve the issue but this way I loose the data.

### Minimal reproduce step

Start a standalone server and connect a python client doing some continuous operations

### What did you expect to see?

No errors

### What did you see instead?

E20250203 14:38:03.244154 139655422928576 event_listener.cc:166] [event_listener/background_error] reason: memtable, bg_error: Corruption: WriteBatch has wrong count

### Anything Else?

_No response_

### Are you willing to submit a PR?

- [ ] I'm willing to submit a PR!

### LINKED ISSUE #2900: Apache Kvrocks version 2.11.1 got signal: Segmentation fault (11) in list blocking pop
### Search before asking

- [x] I had searched in the [issues](https://github.com/apache/kvrocks/issues) and found no similar issues.

### Version

E20250425 10:07:13.354657 140365197694656 signal_util.h:34] Ooops! Apache Kvrocks version 2.11.1 got signal: Segmentation fault (11)
E20250425 10:07:13.374111 140365197694656 signal_util.h:36] Stack trace (most recent call first):
#0  0x000056521a2553ea in SegvHandler at /usr/bin/kvrocks
#1  0x00007fa95c50504f in __sigaction at /lib/x86_64-linux-gnu/libc.so.6
#2  0x000056521a4a8b1f in engine::Storage::Get(engine::Context&, rocksdb::ReadOptions const&, rocksdb::ColumnFamilyHandle*, rocksdb::Slice const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >*) at /usr/bin/kvrocks
#3  0x000056521a4925b4 in redis::Database::GetMetadata(engine::Context&, RedisTypes, rocksdb::Slice const&, Metadata*) at /usr/bin/kvrocks
#4  0x000056521a4d19ad in redis::List::GetMetadata(engine::Context&, rocksdb::Slice const&, ListMetadata*) at /usr/bin/kvrocks
#5  0x000056521a4d220b in redis::List::PopMulti(engine::Context&, rocksdb::Slice const&, bool, unsigned int, std::vector<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::allocator<std::__cxx11::basic_string<char, std::cha
r_traits<char>, std::allocator<char> > > >*) at /usr/bin/kvrocks
#6  0x000056521a321a40 in redis::CommandBPop::TryPopFromList(engine::Context&) at /usr/bin/kvrocks
#7  0x000056521a322ced in redis::CommandBPop::OnBlockingWrite() at /usr/bin/kvrocks
#8  0x000056521a32cecb in EvbufCallbackBase<redis::BlockingCommander, false, true, true>::writeCB(bufferevent*, void*) at /usr/bin/kvrocks
#9  0x000056521abf6159 in bufferevent_run_deferred_callbacks_unlocked at bufferevent.c
#10 0x000056521abfdf83 in event_process_active_single_queue at event.c
#11 0x000056521abfe61e in event_process_active at event.c
#12 0x000056521ac003d8 in event_base_loop.constprop.0 at event.c
#13 0x000056521a47848d in std::thread::_State_impl<std::thread::_Invoker<std::tuple<util::CreateThread<WorkerThread::Start()::{lambda()#1}>(char const*, WorkerThread::Start()::{lambda()#1})::{lambda()#1}> > >::_M_run() at /usr/bin/kvrocks
#14 0x000056521ae139d2 in execute_native_thread_routine at thread.o
#15 0x00007fa95c5521c3 in pthread_condattr_setpshared at /lib/x86_64-linux-gnu/libc.so.6

### Minimal reproduce step

Null

### What did you expect to see?

Null

### What did you see instead?

Null

### Anything Else?

_No response_

### Are you willing to submit a PR?

- [ ] I'm willing to submit a PR!

### PR DESCRIPTION
**Pull request by git-hulk**
Currently, the EXEC is an exclusive command and will enter the transaction mode when running, but the blocking command's callback function doesn't have this lock. So the callback might get trapped in the wrong transaction mode and break the write batch.

For example, the client A sends the command: `BRPOP list 10` and it will enter the blocking mode due to no data. And the client B uses the transaction to send the command: `MULTI; LPUSH list a; EXEC`. Then the client A's callback will be revoked after the `LPUSH` command is executed, but the EXEC is running. So the callback's operation(removing an element from the list) will be counted in the transaction.

It closes #2900.
It closes #2766.

### CODE REVIEW

File: src/commands/blocking_commander.h [hunk 1]
```diff
@@ -68,6 +69,15 @@ class BlockingCommander : public Commander,
   }
 
   void OnWrite(bufferevent *bev) {
+    {
+      // The blocking command should not be executed when the server is in exclusive state,
+      // because it might have the data race when the server is in transaction mode and run
+      // the callback here might cause the current execution also in transaction mode.
+      //
+      // For more context, please refer to: https://github.com/apache/kvrocks/issues/2900
+      auto concurrency = conn_->GetServer()->WorkConcurrencyGuard();
```
Comment (PragmaTwice) [inline src/commands/blocking_commander.h:79]: It will be destructed immediately if we put it here, so we can move it before `auto guard = GetLocks();`.

Comment (git-hulk) [reply src/commands/blocking_commander.h:79]: Enlarge the scope now.

**Review by PragmaTwice — APPROVED** [review]
