### PR TITLE
Fix config set compression type didn't take effect

### LINKED ISSUE #1560: Dynamic modification of the parameter rocksdb.compression to zstd in version 2.4 may not take effect immediately on newly created files
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/kvrocks/issues) and found no similar issues.

### Version

2.4

### Minimal reproduce step

1.Modify the compression parameters.
2.FlushDB and compact
3.Rewrite the data, but it appears that zstd compression was not applied based on the logs. The output still shows that the compression used is lz4.
"[CompactOnExpiredCollector]", "compression": "LZ4", "compression_options": "window_bits=-14; level=32767; strategy=0; max_dict_bytes=0; zstd_max_train_bytes=0; enabled=0; max_dict_buffer_bytes=0; use_zstd_dict_trainer=1; "

if reboot kvrocks then use zstd

2023/07/05-13:22:43.170822 1        Options.write_buffer_size: 67108864
2023/07/05-13:22:43.170824 1  Options.max_write_buffer_number: 10
2023/07/05-13:22:43.170826 1        Options.compression[0]: NoCompression
2023/07/05-13:22:43.170827 1        Options.compression[1]: NoCompression
2023/07/05-13:22:43.170829 1        Options.compression[2]: ZSTD
2023/07/05-13:22:43.170830 1        Options.compression[3]: ZSTD
2023/07/05-13:22:43.170832 1        Options.compression[4]: ZSTD
2023/07/05-13:22:43.170833 1        Options.compression[5]: ZSTD
2023/07/05-13:22:43.170835 1        Options.compression[6]: ZSTD

"[CompactOnExpiredCollector]", "compression": "ZSTD", "compression_options": "window_bits=-14; level=32767; strategy=0; max_dict_bytes=0; zstd_max_train_bytes=0; enabled=0; max_dict_buffer_bytes=0; use_zstd_dict_trainer=1; "

### What did you expect to see?

Test passed

### What did you see instead?

The compression parameters only take effect after a restart

### Anything Else?

_No response_

### Are you willing to submit a PR?

- [ ] I'm willing to submit a PR!

### PR DESCRIPTION
**Pull request by xiaobiaozhao**
In this PR, we also refactor the c-style ConfigEnum array into the std::vector, the main reason is to make it easier to adopt dynamic config enums like the compression types. And for the test case, it's a bit hard to test if the compression type takes effect in underlying storage because we only enabled it when the levels >= 2. But will check it manually to make sure if works.

This closes https://github.com/apache/kvrocks/issues/1560

### CODE REVIEW

File: src/storage/storage.cc [hunk 1]
```diff
@@ -180,6 +180,29 @@ rocksdb::Options Storage::InitRocksDBOptions() {
 }
 
 Status Storage::SetOptionForAllColumnFamilies(const std::string &key, const std::string &value) {
+  if ("compression" == key) {
```
Comment (git-hulk) [inline src/storage/storage.cc]: I think we can take this into a single function like `SetCompressionOption` since it's a special setting option.

File: src/storage/storage.cc [hunk 2]
```diff
@@ -183,6 +183,29 @@ rocksdb::Options Storage::InitRocksDBOptions() {
...
+    std::unordered_map<std::string, std::string> compression_map = {{"no", "kNoCompression"},
```
Comment (git-hulk) [inline src/storage/storage.cc]: It'd be better to put this text in compression_types, to make it more easy to maintain. Or it needs to take care of many places if we wanna add a new compression type.

Comment (xiaobiaozhao) [reply src/storage/storage.cc]: > It'd be better to put this text in compression_types, to make it more easy to maintain. Or it needs to take care of many places if we wanna add a new compression type.

done

File: src/storage/storage.cc (hunk 1 above)
Comment (xiaobiaozhao) [reply src/storage/storage.cc]: done

File: src/config/config.cc [hunk 3]
```diff
@@ -601,6 +601,11 @@ void Config::initFieldCallback() {
       {"rocksdb.level0_slowdown_writes_trigger", set_cf_option_cb},
       {"rocksdb.level0_stop_writes_trigger", set_cf_option_cb},
       {"rocksdb.level0_file_num_compaction_trigger", set_cf_option_cb},
+      {"rocksdb.compression",
+       [](Server *srv, const std::string &k, const std::string &v) -> Status {
+         if (!srv) return Status::OK();
+         return srv->storage->SetOptionForAllColumnFamilies(TrimRocksDbPrefix(k), v);
+       }},
```
Comment (PragmaTwice) [inline src/config/config.cc]: Why can't we simply write this compression option manipulation code here instead of `Storage::SetOptionForAllColumnFamilies`?

File: src/config/config.h [hunk 4]
```diff
@@ -39,6 +39,7 @@ namespace engine {
 class Storage;
 }
 
+extern ConfigEnum compression_types[];
```
Comment (PragmaTwice) [inline src/config/config.h]: I cannot find the reason to add an extern variable here.

File: src/storage/storage.cc [hunk 5]
```diff
@@ -182,7 +182,61 @@ rocksdb::Options Storage::InitRocksDBOptions() {
...
+    auto s = db_->SetOptions(cf_handle, {{"compression_per_level", compression_levels}});
+    if (!s.ok()) return {Status::NotOK, s.ToString()};
+  }
+  return Status::OK();
+}
+
 Status Storage::SetOptionForAllColumnFamilies(const std::string &key, const std::string &value) {
+  if ("compression" == key) {
+    return SetCompressionOption(key, value);
+  }
```
Comment (PragmaTwice) [inline src/storage/storage.cc]: IMHO we do not want special logic here, please state the reason.

File: src/storage/storage.cc [hunk 6]
```diff
@@ -182,7 +182,61 @@ rocksdb::Options Storage::InitRocksDBOptions() {
...
+  return iter->second;
+}
+
+std::string Storage::CompressString2CompressionString(const std::string &type) {
+  std::unordered_map<std::string, std::string> compression_map = {{"no", "kNoCompression"},
+                                                                  {"snappy", "kSnappyCompression"},
+                                                                  {"lz4", "kLZ4Compression"},
+                                                                  {"zstd", "kZSTD"},
+                                                                  {"zlib", "kZlibCompression"}};
```
Comment (PragmaTwice) [inline src/storage/storage.cc]: please extract these two maps as **static storage-duration**, **const** global variables.

File: src/storage/storage.cc [hunk 7]
```diff
@@ -182,7 +182,61 @@ rocksdb::Options Storage::InitRocksDBOptions() {
...
+  }
+  return iter->second;
+}
+
+Status Storage::SetCompressionOption(const std::string &key, const std::string &value) {
+  std::string compression_string = CompressString2CompressionString(value);
+  if ("unknown" == compression_string) {
+    return {Status::NotOK, "Invalid compression type"};
+  }
+  std::string compression_levels = "kNoCompression:kNoCompression";
```
Comment (PragmaTwice) [inline src/storage/storage.cc]: please write some comment here to state why there is no compression in first two levels.

**Review by PragmaTwice — CHANGES_REQUESTED** [review]
the code does not look well to me, some fixes need to be pushed

File: tests/gocase/unit/config/config_test.go [hunk 8]
```diff
@@ -108,3 +108,33 @@ func TestSetConfigBackupDir(t *testing.T) {
...
+	rList = r.Val().([]interface{})
+	require.EqualValues(t, rList[1], "lz4")
+
+	require.NoError(t, rdb.Do(ctx, "CONFIG", "SET", "rocksdb.compression", "zstd").Err())
+	require.Equal(t, "bar", rdb.Get(ctx, "foo").Val())
+	r = rdb.Do(ctx, "CONFIG", "GET", "rocksdb.compression")
+	rList = r.Val().([]interface{})
+	require.EqualValues(t, rList[1], "zstd")
+
+	require.ErrorContains(t, rdb.Do(ctx, "CONFIG", "SET", "rocksdb.compression", "undefine").Err(), "invalid enum option")
```
Comment (PragmaTwice) [inline tests/gocase/unit/config/config_test.go]: I wonder if these test code can trigger a compaction?

File: src/storage/storage.cc [hunk 9]
```diff
@@ -182,6 +199,41 @@ rocksdb::Options Storage::InitRocksDBOptions() {
...
 
+std::string Storage::CompressType2String(const rocksdb::CompressionType &type) {
+  auto iter = compression_type_string_map.find(type);
+  if (iter == compression_type_string_map.end()) {
+    return "unknown";
+  }
+  return iter->second;
+}
+
+std::string Storage::CompressString2CompressionString(const std::string &type) {
```
Comment (PragmaTwice) [inline src/storage/storage.cc]: i cannot understand the function name `CompressString2CompressionString`.

File: src/storage/storage.cc [hunk 10]
```diff
@@ -56,6 +56,23 @@ const int64_t kIORateLimitMaxMb = 1024000;
 
 using rocksdb::Slice;
 
+const static std::map<std::string, std::string> compression_sort_long_string_map = {{"no", "kNoCompression"},
+                                                                                    {"snappy", "kSnappyCompression"},
+                                                                                    {"lz4", "kLZ4Compression"},
+                                                                                    {"zstd", "kZSTD"},
+                                                                                    {"zlib", "kZlibCompression"}};
+const static std::map<rocksdb::CompressionType, std::string> compression_type_string_map = {
```
Comment (PragmaTwice) [inline src/storage/storage.cc]:
```suggestion
const static std::map<rocksdb::CompressionType, std::string> compression_type_to_string_map = {
```

File: src/storage/storage.cc [hunk 11]
```diff
@@ -56,6 +56,23 @@ const int64_t kIORateLimitMaxMb = 1024000;
 
 using rocksdb::Slice;
 
+const static std::map<std::string, std::string> compression_sort_long_string_map = {{"no", "kNoCompression"},
```
Comment (PragmaTwice) [inline src/storage/storage.cc]:
```suggestion
const static std::map<std::string, std::string> compression_string_to_rocksdb_option_map = {{"no", "kNoCompression"},
```

Comment (caipengbo) [inline src/storage/storage.cc]: I think the following map is sufficient. Why do we need `compression_sort_long_string_map`?

File: src/storage/storage.cc [hunk 12]
```diff
@@ -182,6 +199,41 @@ rocksdb::Options Storage::InitRocksDBOptions() {
...
+  for (size_t i = 2; i < db_->GetOptions().compression_per_level.size(); i++) {
+    compression_levels += ":";
+    compression_levels += compression_string;
+  }
+
+  for (auto &cf_handle : cf_handles_) {
+    auto s = db_->SetOptions(cf_handle, {{"compression_per_level", compression_levels}});
+    if (!s.ok()) return {Status::NotOK, s.ToString()};
+  }
+  return Status::OK();
```
Comment (PragmaTwice) [inline src/storage/storage.cc]:
```suggestion
  return SetOptionForAllColumnFamilies("compression_per_level", compression_levels);
```

File: src/storage/storage.cc (hunk 11 above)
Comment (datavisorxiaobiaozhao) [reply src/storage/storage.cc]: setOptions requires parameters of type string

**Comment by caipengbo** [comment]
I think the `SetCompressionOption` parameter value is the name of the compression algorithm. We get `rocksdb::CompressionType` by `map[name]`(name->CompressionType), and then pass it to `SetOptions`, in `SetOptions` static_cast it to `rocksdb::CompressionType`.

**Comment by git-hulk** [comment]
@PragmaTwice @xiaobiaozhao @caipengbo I minor refactor the PR, PTAL again.

**Comment by git-hulk** [comment]
I have tested if the config set command works on my side:

Set the compression to LZ4:
```
2023/07/14-20:45:08.518174 6158610432 [db/db_impl/db_impl.cc:1195] SetOptions() on column family [default], inputs:
2023/07/14-20:45:08.518210 6158610432 [db/db_impl/db_impl.cc:1198] compression_per_level: kNoCompression:kNoCompression:kLZ4Compression:kLZ4Compression:kLZ4Compression:kLZ4Compression:kLZ4Compression
```

then use `redis-benchmark -p 6666  -n 1000000 -r 5000000 -t set -d 1024` to write the data, and check the db LOG to see if the compression was used:

```
2023/07/14-20:50:15.181736 6156890112 (Original Log Time 2023/07/14-20:50:15.181594) [db/compaction/compaction_job.cc:888] [metadata] compacted to: files[0 1 13 0 0 0 0] 
max score 0.93, MB/sec: 39.1 rd, 4.5 wr, level 2, files in(1, 1) out(1 +0 blob) MB 
in(58.0, 2.6 +0.0 blob) out(7.1 +0.0 blob), read-write-amplify(1.2) write-amplify(0.1) OK, 
records in: 89927, records dropped: 3779 output_compression: LZ4
```

File: src/config/config_type.h [hunk 13]
```diff
@@ -186,15 +186,17 @@ class YesNoField : public ConfigField {
 
 class EnumField : public ConfigField {
  public:
-  EnumField(int *receiver, ConfigEnum *enums, int e) : receiver_(receiver), enums_(enums) { *receiver_ = e; }
+  EnumField(int *receiver, std::vector<ConfigEnum> &enums, int e) : receiver_(receiver), enums_(std::move(enums)) {
```
Comment (PragmaTwice) [inline src/config/config_type.h]:
```suggestion
  EnumField(int *receiver, std::vector<ConfigEnum> enums, int e) : receiver_(receiver), enums_(std::move(enums)) {
```

Comment (PragmaTwice) [reply src/config/config_type.h]: otherwise the passed `enums` will be invalid after the ctor call, which is very counterintuitive since it is passed as lvalue reference.

File: src/config/config.cc [hunk 14]
```diff
@@ -45,42 +45,37 @@ constexpr const char *errBlobDbNotEnabled = "Must set rocksdb.enable_blob_files
...
 std::string TrimRocksDbPrefix(std::string s) {
   if (strncasecmp(s.data(), "rocksdb.", 8) != 0) return s;
   return s.substr(8, s.size() - 8);
 }
 
-int ConfigEnumGetValue(ConfigEnum *ce, const char *name) {
-  while (ce->name != nullptr) {
-    if (strcasecmp(ce->name, name) == 0) return ce->val;
-    ce++;
+int ConfigEnumGetValue(const std::vector<ConfigEnum> &enums, const std::string &name) {
```
Comment (PragmaTwice) [inline src/config/config.cc]: I think this and the next function can be methods of `ConfigEnum`.

File: src/storage/storage.cc [hunk 15]
```diff
@@ -54,8 +54,18 @@ constexpr const char *kReplicationIdKey = "replication_id_";
...
+    {rocksdb::kNoCompression, "no", "kNoCompression"},
+    {rocksdb::kSnappyCompression, "snappy", "kSnappyCompression"},
+    {rocksdb::kZlibCompression, "zlib", "kZlibCompression"},
+    {rocksdb::kLZ4Compression, "lz4", "kLZ4Compression"},
+    {rocksdb::kZSTD, "zstd", "kZSTD"},
+};
+
 using rocksdb::Slice;
 
+std::vector<CompressionOption> GetCompressionOptions() { return compressionOptions; }
```
Comment (PragmaTwice) [inline src/storage/storage.cc]:
```suggestion
const std::vector<CompressionOption>& GetCompressionOptions() { return compressionOptions; }
```

Comment (PragmaTwice) [reply src/storage/storage.cc]: we do not need to construct a vector every time when we call the function, which is expensive. BTW I think it is no difference than just an `inline const` vector in header file.

File: src/config/config_type.h (hunk 13 above)
Comment (git-hulk) [reply src/config/config_type.h]: Thanks @PragmaTwice, it makes a lot of sense

File: src/storage/storage.cc (hunk 15 above)
Comment (git-hulk) [reply src/storage/storage.cc]: Yes, it's better to put this in the header file.

File: src/config/config.cc (hunk 14 above)
Comment (git-hulk) [reply src/config/config.cc]: Good point, will do it soon.

Comment (git-hulk) [reply src/config/config.cc]: I have done this by removing this function since only one place used them.

**Review by caipengbo — DISMISSED** [review]

**Review by caipengbo — APPROVED** [review]
LGTM

**Review by PragmaTwice — APPROVED** [review]
