### PR TITLE
Fix CONFIG REWRITE append duplicate newlines

### LINKED ISSUE #1396: config rewrite bug
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-kvrocks/issues) and found no similar issues.

### Version

2.3.0

### Minimal reproduce step

namespace add xxx
config rewrite

### What did you expect to see?

no extra blank lines in kvrocks.conf

### What did you see instead?

First create 1w namespace, then config rewrite.
There are 1w extra blank lines after config rewrite

### Anything Else?

_No response_

### Are you willing to submit a PR?

- [ ] I'm willing to submit a PR!

### PR DESCRIPTION
**Pull request by enjoy-binbin**
In the old code, everytime we perform a config rewrite, an
additional newline is appended, see #1396

Because iostream::eof will only return true after reading the
end of the stream. It does not indicate, that the next read will
be the end of the stream.

So everytime config rewrite is performed, the old loop will
append a newline in `lines`, and then we will append it to the
conf file.

In addition, the same modification has been made to other similar
places. This PR fixes #1396

### CODE REVIEW

**Comment by enjoy-binbin** [comment]
I tested it locally (with the CONFIG REWRITE)
and the ref: https://stackoverflow.com/questions/5605125/why-is-iostreameof-inside-a-loop-condition-i-e-while-stream-eof-cons

**Comment by git-hulk** [comment]
@enjoy-binbin Thanks for your efforts. ❤️

**Review by git-hulk — DISMISSED** [review]

**Review by torwig — DISMISSED** [review]
LGTM

File: src/config/config.cc [hunk 1]
```diff
@@ -829,8 +829,8 @@ Status Config::Rewrite() {
   std::ifstream file(path_);
   if (file.is_open()) {
     std::string raw_line;
-    while (!file.eof()) {
-      std::getline(file, raw_line);
+    while (std::getline(file, raw_line)) {
+      if (file.eof()) break;
```
Comment (PragmaTwice) [inline src/config/config.cc]: If the text file has no newline after the last line, this line will be ignored.

e.g.
```python
file.write("a\nb\nc"); # the `c` line will be ignored
```

Hence I think it is not a good change.

**Review by PragmaTwice — CHANGES_REQUESTED** [review]
Thanks for your patch, but seems changes are required.

**Comment by PragmaTwice** [comment]
Here is a simple test to demonstrate this point:
```
❯ cat y.cpp
#include <fstream>
#include <iostream>
#include <string>

int main() {
std::ifstream file("hello.txt");
std::string line;
while (std::getline(file, line)) {
    if (file.eof()) break;
    std::cout << "> " << line << std::endl;
}
}

❯ python -c "file=open('hello.txt', 'w');file.write('a\nb\nc');file.close()"

❯ cat hello.txt
a
b
c%

❯ ./y
> a
> b

❯
```

**Comment by enjoy-binbin** [comment]
@PragmaTwice thanks for the detailed explanation! do you have any suggestions? i may need some time to figure it out
do you think if i put the `if (file.eof()) break;` in the last will help?

**Comment by PragmaTwice** [comment]
> @PragmaTwice thanks for the detailed explanation! do you have any suggestions? i may need some time to figure it out do you think if i put the `if (file.eof()) break;` in the last will help?

Not sure the eof check is necessary, maybe something like `while(file.good() && getline(...))` is ok.

The call to `getline` will return the stream itself, so `operator bool` of the stream is called, and it is equal to `!stream.fail()`.

**Comment by enjoy-binbin** [comment]
i change to use `while(file.good() && getline(...))` for now, i also tested it in local, it is fine

File: src/config/config.cc [hunk 2]
```diff
@@ -726,8 +726,7 @@ Status Config::Load(const CLIOptions &opts) {
 
     std::string line;
     int line_num = 1;
-    while (!in->eof()) {
-      std::getline(*in, line);
+    while (in.good() && std::getline(*in, line)) {
```
Comment (git-hulk) [inline src/config/config.cc]:
```suggestion
    while (in->good() && std::getline(*in, line)) {
```

**Review by PragmaTwice — APPROVED** [review]

**Review by torwig — APPROVED** [review]

**Review by git-hulk — APPROVED** [review]

**Comment by git-hulk** [comment]
Thanks all, merging...
