### PR TITLE
Fix rename-command didn't work when using it multiple times

### LINKED ISSUE #1040: rename commands don't work
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-kvrocks/issues) and found no similar issues.

### Version

2.1.0

### Minimal reproduce step

1、add rename-command in kvrocks.conf
rename-command flushall                             dont_run_flushall_rudely
rename-command flushdb                             dont_run_flushdb_rudely
rename-command bgsave                              dont_run_bgsave_rudely
rename-command config                               dont_run_config_rudely
2、start kvrocks

3、exec dont_run_bgsave_rudely
127.0.0.1:6379> dont_run_bgsave_rudely
(error) ERR unknown command dont_run_bgsave_rudely

exec dont_run_config_rudely   can success

127.0.0.1:6379> config get rename-command
1) "rename-command"
2) "config                              dont_run_config_rudely"

as it shows in config info，only dont_run_config_rudely effects。

4、exec config rewrite
127.0.0.1:6379> dont_run_config_rudely rewrite
OK
127.0.0.1:6379> dont_run_config_rudely get rename-command
1) "rename-command"
2) "config                              dont_run_config_rudely"

but rename-commands in kvrocks.conf still are old contents.
root@redis-kvsenior01-290192:/home/redis/etc# grep rename /home/redis/data/conf/kvrocks.conf
# rename
# rename
rename-command flushall                             dont_run_flushall_rudely
rename-command flushdb                             dont_run_flushdb_rudely
rename-command bgsave                              dont_run_bgsave_rudely
...
rename-command config                              dont_run_config_rudely

### What did you expect to see?

all rename commands can work

### What did you see instead?

no

### Anything Else?

_No response_

### Are you willing to submit a PR?

- [ ] I'm willing to submit a PR!

### PR DESCRIPTION
**Pull request by tanruixiang**
This close #1040

### CODE REVIEW

File: src/config/config.cc [hunk 1]
```diff
@@ -723,7 +726,13 @@ void Config::Get(std::string key, std::vector<std::string> *values) {
...
     if (key == "*" || Util::ToLower(key) == iter.first) {
       values->emplace_back(iter.first);
-      values->emplace_back(iter.second->ToString());
+      if (iter.second->GetConfigType() == configType::MultiConfig) {
+        for (const auto &p : Util::Split(iter.second->ToString(), "\n")) {
+          values->push_back(p);
+        }
+      } else {
+        values->emplace_back(iter.second->ToString());
+      }
```
Comment (PragmaTwice) [inline src/config/config.cc]:
```suggestion
      if (iter.second->GetConfigType() == configType::MultiConfig) {
        for (const auto &p : Util::Split(iter.second->ToString(), "\n")) {
          values->emplace_back(iter.first);
          values->push_back(p);
        }
      } else {
        values->emplace_back(iter.first);
        values->emplace_back(iter.second->ToString());
      }
```
I think we need to keep one-key-one-value pairs, in order to make user parse the result of `config get *` easily.

File: src/config/config.cc [hunk 2]
```diff
@@ -723,7 +726,13 @@ void Config::Get(std::string key, std::vector<std::string> *values) {
   for (const auto &iter : fields_) {
     if (key == "*" || Util::ToLower(key) == iter.first) {
       values->emplace_back(iter.first);
```
Comment (PragmaTwice) [inline src/config/config.cc]:
```suggestion
```

File: src/config/config.cc [hunk 3]
```diff
@@ -273,23 +273,26 @@ void Config::initFieldValidator() {
...
-         auto commands = Redis::GetCommands();
-         auto cmd_iter = commands->find(Util::ToLower(args[0]));
-         if (cmd_iter == commands->end()) {
-           return Status(Status::NotOK, "No such command in rename-command");
-         }
-         if (args[1] != "\"\"") {
-           auto new_command_name = Util::ToLower(args[1]);
-           if (commands->find(new_command_name) != commands->end()) {
-             return Status(Status::NotOK, "Target command name already exists");
+         std::vector<std::string> all_args = Util::Split(v, "\n");
```
Comment (git-hulk) [inline src/config/config.cc:276]: The rename command should not support:
```
rename-command a b
c d
e f 
``` 
so it makes no sense to split with newline here?

File: src/config/config.cc [hunk 4]
```diff
@@ -722,8 +725,15 @@ void Config::Get(std::string key, std::vector<std::string> *values) {
   values->clear();
   for (const auto &iter : fields_) {
     if (key == "*" || Util::ToLower(key) == iter.first) {
-      values->emplace_back(iter.first);
-      values->emplace_back(iter.second->ToString());
+      if (iter.second->GetConfigType() == configType::MultiConfig) {
```
Comment (git-hulk) [inline src/config/config.cc]: Can you add a test case for this line, it looks not correct for the rename-command now.

**Comment by PragmaTwice** [comment]
https://github.com/apache/incubator-kvrocks/blob/debd8988d6f6978593ad35b7e06d0c3e773ee825/src/config/config.cc#L767-L771

Since **ALL `MultiStringField` cannot be rewritten**, so I think you need to change it to something like
```
if (iter->second.IsMulti())
```
in case of someone use `MultiStringField` but forget to include the config key in this check.

**Comment by git-hulk** [comment]
> https://github.com/apache/incubator-kvrocks/blob/debd8988d6f6978593ad35b7e06d0c3e773ee825/src/config/config.cc#L767-L771
> 
> Since **ALL `MultiStringField` cannot be rewritten**, so I think you need to change it to something like
> 
> ```
> if (iter->second.IsMulti())
> ```
> 
> in case of someone use `MultiStringField` but forget to include the config key in this check.

Yes, that's right.

File: src/config/config.cc (hunk 3 above)
Comment (tanruixiang) [reply src/config/config.cc:276]: This is because we store the rename-command in the vector, and the code logic is obtained with Tostring. So we used `\n` as delimiter to concat this vector. For example: `KEYS KEYSNEW \n GET  GETNEW \n`

File: src/config/config.cc (hunk 4 above)
Comment (tanruixiang) [reply src/config/config.cc]: Test cases have been added.

File: tests/cppunit/config_test.cc [hunk 5]
```diff
@@ -133,6 +133,33 @@ TEST(Config, GetAndSet) {
...
+
+  std::ostringstream string_stream;
+  string_stream << "rename-command KEYS KEYS_NEW"
+                << "\n";
+  string_stream << "rename-command GET GET_NEW"
+                << "\n";
+  string_stream << "rename-command SET SET_NEW"
+                << "\n";
+  std::ofstream output_file(path, std::ios::out);
+  output_file.write(string_stream.str().c_str(), string_stream.str().size());
```
Comment (PragmaTwice) [inline tests/cppunit/config_test.cc]: You can write something like `output_file << "rename-command KEYS KEYS_NEW\n" << ...` directly.

**Review by PragmaTwice — APPROVED** [review]

File: src/config/config.cc (hunk 3 above)
Comment (git-hulk) [reply src/config/config.cc:276]: Okay, very sad that I made the field value as a string.

**Review by git-hulk — APPROVED** [review]

**Comment by git-hulk** [comment]
Thanks @tanruixiang @PragmaTwice, merging...
